### PR TITLE
Wardentime

### PR DESCRIPTION
**Pull request by Onutsio**
## About The Pull Request

Adds a Warden unique garrison trait, much like GUARDSMAN or KNIGHTSMAN - Called WOODSMAN. Woodsman grants +1 spd, +3 per, and longstrider while in relevant outdoors areas(the grove and coast)

Additionally buffs Warden's skills to better allow them to utilize their environment to their advantage, as they lack in traditional combat strength of MAA/RG. Settling their 'style' of being around wood ambushes and using their environment is probably the best way to give them an actual identity mechanically.

Athletics -> 4
Climbing ->4
Swimming ->4(Hasselhof Aho!)
Sneaking ->4
New Woodsman Trait(Longstrider in relevant areas, +3 per, +1 spd)

## Why It's Good For The Game

Warden is currently mechanically worse at actually engaging in the Wilds than the other garrison members. Despite being literally meant for it. Also area buffs are cool, and now each branch of the garrison has a relevant one.

### CODE REVIEW

**Comment by Cleric2145** [comment]
> pls not longstrider that means people will not be able to escape the rangers

Carry a staff or behave, criminal scum 😘

**Comment by chemistrymain3** [comment]
> pls not longstrider that means people will not be able to escape the rangers

people can still get away from them easily

**Comment by Lutowski** [comment]
nnnnot super sure on longstrider but we can always dial it back

**Comment by Onutsio** [comment]
Yea if Wardens start dunking on every antag with longstrider we can strip it. I don't think it will happen since every antag can just - Kill the warden, fairly easily. They either have WAY more speed(WWs, VLs), or are a team that will probably have some sort of ranged(bandits). Or can just, turn around and kill the wardens.

**Pull request merged**
