### PR TITLE
Nudeshots, but for Azure. Wow!

### PR DESCRIPTION
**Pull request by merawera**
Look at these FREEKS intimately.  But only if you want to.

Requires the one you're examining to be completely exposed before displaying "Examine Intimately".

### CODE REVIEW

**Comment by Kavrick** [comment]
I'd really rather we not devolve to being an ERP server. This isn't particularly good for server quality.

**Comment by bearrrrrrrr** [comment]
ehhh iunno, i'd prefer not. ig it's not a huge deal if it does get in and it does put us on parity, so...no huge objections

**Comment by benj8560** [comment]
idunno what the drama or issue is here behind this. I think I'd rather a big button you gotta push to see things? People are sometimes dumb and don't put NSFW warnings on their borderline traumatizing refs. Or use the headshot for NSFW (even tho your not suppose to) 

This seems fine?? Like. Can you people maybe gives some genuine  thoughtful arguments behind why its bad? Not just ''is horny is bad'' How does this make us a pure ERP server?

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Yeaaah, I think we are good without this.

Closed since people that want to show nude-art can already do so by putting a link in the FT and all.

**Comment by Quink-Fix** [comment]
Sad and unnecessary shutdown of a QoL feature.

**Pull request closed without merging**
