### PR TITLE
Super Important Werewolf Overhaul

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
There is no need to read the contents of this PR.

Trust.

### CODE REVIEW

**Comment by Dino36L** [comment]
yup totally normal overhaul, mhm mhm
mer ge it,,.

**Comment by Onutsio** [comment]
Im Onutsio of the Azure Peak, and I approve this PR

**Comment by Raze500** [comment]
NICE AWEOMSEEEE!! doubles sex damage

**Comment by bearrrrrrrr** [comment]
Approved!

**Pull request closed without merging**
