### PR TITLE
Robes and Kitchen

### PR DESCRIPTION
**Pull request by Kavrick**
Makes robes wearable on more slots
Also redoes the keep kitchen to not be the worst thing ever, took me two rounds of playing butler in that kitchen to swiftly hate it.
StrongDMM_OX8X8fDSW1

### CODE REVIEW

**Comment by Kavrick** [comment]
StrongDMM_psTPh0hl2h
New item! Chef's Knife. Basically the same as cleaver, but it's light and can stab.

**Comment by Kavrick** [comment]
Bloat? The game right now has basically everything _except_ a regular knife.

**Comment by bearrrrrrrr** [comment]
bloat?! we have so few items!!!

(also yea, soap and tray)

**Comment by Kavrick** [comment]
Conflicts should be fixed, also changed the butchers setout sliiiightly. Mostly the issue was the mobs would stand on the pallisades and because they were short you couldn't see them, which was a shame. Also made it so there are some more doors, so you don't have to walk aaaaaall the way around to get to the farm in case you're growing wheat for the stock.

**Pull request merged**
