### PR TITLE
Lockpicking & Smithing Overhaul

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
Ports Lockpicking and Smithing systems from Stonekeep, with big big modifications.

**Smithing**

- Pretty much every smithable has had their smithing level reconsidered.
- Smelting skill added. It has decreased dream point requirement compared to other skills. It determines the quality of smelted bars.
- Bars and finished products have quality modifiers now. Quality for products affects only the name of the item, the sell price, and lockpick integrity + efficiency. Quality of ingots affects bar health, sellprice, and the quality of the products.
- Striking an ingot will begin to automatically continue striking, until you either fail a strike, the bar cools, or the item finishes. You can still manually strike. Auto smithing take 4 times as many strikes as manual smithing.
- Smithing now has non-null stamina usage.
- Trying to smith something that's beyond your level gives you a confirmation window.

**Lockpicking**

- Adds lockpicking skill. Only some roles get it. The pure rogue adventurer class gets expert in it.
- Doors have a lock strength. The more powerful the door, the stronger the lock is, the longer it takes to crack.
- Lockpicks and lockpick rings to hold them are smithable, and lockpick sets can be purchased through the merchant
- As a freshly spawned rogue, it took me 20 seconds to crack a wooden door, 30 for iron bars, and 40 for dungeon doors (the front door of the keep). Bear in mind that a successful lockpicking attempt requires being still for the full duration. Even turning around will cancel it entirely.

**Other Things**

- Treasury considers items inside chests for wealth hoard generation. So you can lock your goodies away extra securely.
- Nerve Master correctly sends messages to paid and fined individuals.
- Increases smithing skill of towner/pilgrim smiths.
- Lucerne integrity and force decreased, so that the eagle's beak can actually be Better.
- Salt is now imported/exported in batches of 5.

Apologies for the gigantic and overreaching PR, but the lockpicking port depended on smithing code, and I had to port the whole thing as a result. Also ADHD.

### CODE REVIEW

**Comment by Kavrick** [comment]
I think this is cool but I'm worried about lowpop rogues just fucking the entire keep in the ass.

**Comment by EvenInDeathIStillServe** [comment]
> I think this is cool but I'm worried about lowpop rogues just fucking the entire keep in the ass.

We remain, as always, a roleplay server.

**Comment by Kavrick** [comment]
> > I think this is cool but I'm worried about lowpop rogues just fucking the entire keep in the ass.
> 
> We remain, as always, a roleplay server.

Yeah true, people can just get jobbanned if they abuse it.

**Comment by EvenInDeathIStillServe** [comment]
> regardless; why smelting?

Was part of the stonekeep smithing system. Better bars mean better product. You can use shitty bars for stuff like frying pans, and save the Good Stuff for making actual valuable items. Better bars also have more health, and can withstand abuse from unskilled smiths much better.

**Comment by EvenInDeathIStillServe** [comment]
> admittedly it's more a case of "why is it a separate skill" when I feel like it could be wrapped into smithing, which already doesn't need to be two separate skills here, but eeeh

Believe it or not, there's *three* smithing skills. Blacksmithing, for everyday items. Maybe I should combine them? I dunno.

**Pull request merged**
