### PR TITLE
The GREAT MAGICIANS APPRENTICE REBRANDING: The MAGICIANS ASSOCIATE

### PR DESCRIPTION
**Pull request by ToasterStrudes**
## About The Pull Request

Today, I introduce a new concept for Apprentices to change things up.

Apprentice roles have always been a bit of a weird concept for me, a bit of a hold-over from when ages were a thing. I think the idea of someone having quite literally no skills what-so-ever is funny, but in actual practice it's a bit annoying (Especially with the introduction of sleep-leveling). In this PR, I'm looking to bring them a bit of variety while also giving them some niches. WORRY NOT PEOPLE WHO ENJOYED THE CHALLENGE, THE MAGICIAN APPRENTICE IS STILL THERE, IT'S ALSO BEEN GIVEN JUST A LITTLE BIT MORE INTELLIGENCE TO HELP COMPENSATE FOR THE LACK OF SKILLS.

Lightning bolt has also been removed from their starting spells, and instead has been have been given an additional 2 points refunded so people can choose what they want.

Another secret feature of this... mage apprentices can now be any age. (Super old mage apprentice rejoice) 
(Also they get an actual belt)

The new classes are as follows:

**_Magicians Associate_**: This class is basically an analog to the Mage Adventurer, you have a bit less combat skills/skills in general than a normal mage adventurer to account for having a nice comfy tower and access to a book right off the bat. You have a bit more arcane skill, and you start WITH a tome in waiting and the gem to place in it. Saves you having to go fist fight a rat in the sewers at the start of every round. (You still can if you want I guess.) In essence, you're no longer a lowly apprentice, you're a friendly associate of your good master, instead there to assist in whatever research assignments they have in mind.

**_Alchemist Associate_**: This is a class that has more focus on alchemy and such, little bit less training in the arcane arts and such. Comes with Smokeleaf seeds and Swamp Weed seeds, and has skills in a bit of farming and mining (For growing and collecting stones for transmutation). This is for the folks who prefer to do a bit of alchemy. Technically slightly better than the Court Magician for alchemy. (Fun fact, apparently the Court Mage has the same alchemical skill as their apprentices currently, journeyman.)

And finally, the **_Magicians Apprentice_**: This is your run of the mill Apprentice, same skills and stats but has the addition of a BIT more intelligence (+3 instead of their +2) due to them having so little skills. Basically, mage hard-mode as usual.

## Why It's Good For The Game

Gone are the hold-over concepts for apprentice roles. Apprentice classes having practically no skills just makes them have a huge handicap, even the concept of them not having that many because it's 'for new players' always didn't sit right for me (Why are we punishing new players with bad stats).

It also gives the folks who prefer to play the HARDMODE VERSION OF THE ROLE a chance to still play it if they'd like. Also lets you play a Old Mage Apprentice (hilarious).

### CODE REVIEW

**Comment by Onutsio** [comment]
U should give Old associates a bonus like advent mages for being old ;3e

**Comment by chemistrymain3** [comment]
they should still outskill adventurers by virtue of not being adventurers

**Comment by SirSwagmeyer** [comment]
Do you think you could give Magician Associates who are Old a small boost to Arcyne/Intelligence/Reading? It's always been like that for the other magical roles.

**Comment by SirSwagmeyer** [comment]
> U should give Old associates a bonus like advent mages for being old ;3e

Nevermind I have zero reading comprehension

**Pull request merged**
