### PR TITLE
Make Nightvision work

### PR DESCRIPTION
**Pull request by wshuwshuwshi**
Changes values for lighting_alpha tags so that things that modify a mobs lighting_alpha to let it see in the dark actually allow the mob to see in the dark
I kept the same basic progression of "Quality" for them, so there's a gap of 10 between each level

## About The Pull Request

Modifies values in the lighting Define so that traits and organs which call lighting alpha to allow darkvision actually make it possible to see in the dark (eg; Elven eyes, Night-eyed virtue, Noc patron trait, etc.)
Do note, it's still hard to see in the dark, but at least you **_CAN_** see

Also, makes it so that elves have elven eyes. Why didn't they already have them? Great question

## Why It's Good For The Game

Broken things are bad, Working things are good.
image
image
image
image

### CODE REVIEW

**Comment by wshuwshuwshi** [comment]
I guess this also technically makes it possible to steal an elves eyes to transplant them into someone else, thus granting them nightvision? But given how things were coding, that should have been possible to begin with

**Comment by Lutowski** [comment]
i would keep the old values on all nightvision traits, as they're set that way to not completely invalidate lampterns, while also having just about enough to see most shapes without it. having sight that's 1:1 to daytime is incredibly strong

**Comment by TheEternalFlame** [comment]
> i would keep the old values on all nightvision traits, as they're set that way to not completely invalidate lampterns, while also having just about enough to see most shapes without it. permanent sight that's 1:1 to daytime is incredibly strong

I don't think that invalidates lampterns. Not everyone's gonna have noc patron/ night eyes / or be an elf.  Besides, I'd rather have the traits actually be useful than broken as they were (Like how the night eye virtue only worked if you had noc as your patron despite being separate from it so you'd sacrifice both your patron and virtue slot to get it)

**Comment by wshuwshuwshi** [comment]
> i would keep the old values on all nightvision traits, as they're set that way to not completely invalidate lampterns, while also having just about enough to see most shapes without it. permanent sight that's 1:1 to daytime is incredibly strong

I used the Nightvision eyes as my baseline (See: Sissean Eyes, etc.) The lowest "Night vision" value for it is '192' so I made the night vision trait give lighting_alpha 190 (I just like round values) and adjusted the other values based on the original differences between them (Lesser night vision was 10 more than night vision, etc, etc.)

**Comment by bearrrrrrrr** [comment]
it's pretty bonkers how good this lets you see. not a huge fan

**Comment by sneksnek** [comment]
wasn't old RT considerably less bright?

**Comment by wshuwshuwshi** [comment]
> it's pretty bonkers how good this lets you see. not a huge fan. may want to reduce it or make it conditional somehow if you really wanna keep it as-is.
> 
> remember that this is so strong that on old RT it was balanced with the insane stat maluses that elves got (-4 STR!!)

I was gonna say that Sisseans have eyes that are incredibly better, but turns out Sisseans also dont have their quirky race specific eyes. I'll adjust the values to be worse, but not negligible after a bit.

**Comment by wshuwshuwshi** [comment]
Knocked each 'tier' of nightvision down by one. Going lower and it gets to the point where the 'lesser night vision' flag isn't even helpful unless I turn off the lights in my room or turn up the brightness of my computer, literally just so I can see on Azure Peak ™️

**Comment by Mannybrado** [comment]
> it's pretty bonkers how good this lets you see. not a huge fan. may want to reduce it or make it conditional somehow if you really wanna keep it as-is.
> 
> remember that this is so strong that on old RT it was balanced with the insane stat maluses that elves got (-4 STR!!)

actually elves didnt get night vision they just had -4 str for no real benefit outside of being an absolutely cracked old wizard

**Comment by Lutowski** [comment]
if you're not going to apply the review as it says and bump the numbers up by a snail's pace each time I ask then I'm just going to close this, sorry. the virtue doesn't work bcs it's using noc sight which likely causes weird, unintended behaviors on noc characters, not because it's too dark. this PR doesn't actually fix it, you've given all traits across the board a crazy buff

**Comment by baldylabs** [comment]
not the only hope for night vision fix, noooo...

**Pull request closed without merging**
