### PR TITLE
Butcher fix

### PR DESCRIPTION
**Pull request by Cleric2145**
## About The Pull Request
Butcher didn't spawn with a coinpurse, nor key to the house he lives in? Strange guy indeed.

## Why It's Good For The Game
Half-baked loadouts aren't fun.

Drafted until I properly test this. Also didn't spawn with cleaver on live branch.

### CODE REVIEW

**Comment by Lutowski** [comment]
I'd take out the key. Butchers were removed & converted into a towner class because they didn't have a strong gameplay loop, so the duties of a butcher were merged into soilson role instead.

**Comment by Cleric2145** [comment]
> I'd take out the key. Butchers were removed & converted into a towner class because they didn't have a strong gameplay loop, so the duties of a butcher were merged into soilson role instead.

You mean not give them a key at all? They wouldn't be able to access their own house. Swapped to a farm key for now.

**Comment by Lutowski** [comment]
> You mean not give them a key at all? They wouldn't be able to access their own house. Swapped to a farm key for now.

No, no keys. Towner subclasses shouldn't have roundstart access to areas that belong to independent classes because their gameplay is freeform. That's why the farmer class doesn't start with farm keys, it's ment for these subclasses to do your own 'thing'. My suggestion is to just ask the farmer for keys in-round if you really want to help, since they sit on spares they can give.

**Comment by Cleric2145** [comment]
> They don't inherently own the farm, as it's an infinite town role. The soilers **own** the farm, any peasants and butchers they pick up is extra. They (used to actually i haven't checked in a bit) have a bunch of extra keys for this purpose.

I guess I'm just confused what the butchers/cheesemakers are supposed to do without the key or soilers? There's one key in the steward's office and that also relies on the steward/keep coming to help the townies get it. Until a butcher gets that key, he's basically useless. No animals, no tools, not even a pouch or a knife, nothing. He's a step above vagabond in terms of equipment. Perhaps we should move butcher/cheesemaker to become soiler subclasses?

**Comment by Cleric2145** [comment]
Removed the farm key, added salt/coppiettes to backpack to mimic the cheesemaker's loadout. With the cleaver, actually makes the subclass a subclass rather than just spawning with the clothes on your back and nothing else.

**Comment by Lutowski** [comment]
lgtm

**Pull request merged**
