### PR TITLE
Revert "Improves the bathhouse theme"

### PR DESCRIPTION
**Pull request by Mannybrado**
Haha funny meme.

But no. This kind of shit only hurts us as a HRP server, for the love of fucking god.

### CODE REVIEW

**Comment by EvenInDeathIStillServe** [comment]
rare manny W pr

**Comment by Mannybrado** [comment]
> rare manny W pr

eats your throat out

**Comment by ThinkArbies** [comment]
Coal reversion. You just can't handle the Meet 'n' Fuck glory.

**Comment by YennyWR** [comment]
Its based.

**Pull request merged**
