### PR TITLE
Legendary Smithing Part 1 - The Great Mining Expansion + Artificer's Guild

### PR DESCRIPTION
**Pull request by Kyogon**
## About The Pull Request

Legendary Smithing is the core of this PR, but there is much more planned for it. It will introduce a ton of new smithable and smeltable items, new ores and alloys, and finally, the Legendary Smithing system, which will allow smiths to create expensive, customized pieces for clients.

As goals are added to the PR, I will list them here. As of now, it includes:

Legendary Smithing, which will be a blacksmith-job-only craft that requires legendary in a respective skill. Legendary Smithing creates customized/personalized items for an expensive price, providing cosmetic options to those who can afford it, such as gold adornments, gem encrusting, engravements, stylizations... ect. 
This is the main focus of this PR.

Part one does not include the Legendary Smithing yet. It focuses on the groundwork for expansion: Making the entire map mineable, adding Artificer and the Guild, new ores, new bars and alloys, an overhaul for engineering, a variety of smithable things, and a fuckton of spring cleaning for the code.

### **Currently implemented:**

Metal belts
Iron silverware and bowls.
Chef's knives and cleavers, as well as the ability to smelt them down.
Gold Masks
Blacksteel Plate, an expensive but more durable armor.
Silver War axe, a one handed silver weapon
Multi-bar items now smelt for their full bar value (Only available in greatforge)
Tin bars, smelted from tin ore.
Copper bars, smelted from copper ore.
Blacksteel bars, an alloy created in the greatforge using one silver and three steel.
Bronze bars, an alloy created in the greatforge using three copper and one tin.
Mineable silver ore, slightly more common than gems but rarer than gold.
Mineable copper and tin ore, about as common as iron.
Much of the anvil_recipes code has been cleaned and re-organized.
Goldface sells some more raw resources, including silver ore (for a pretty zenny.)
Stockpile can import and export copper, tin, and silver ore.

Mason job converted into Artificer job: Artificer is an engineering focused role with building and crafting skills on the side.
Mason's Guild has been converted into the Artificer's Guild.
Farm has been slightly edited to be more difficult to tide into.
Added a training dummy in town, far to the west, between the church and the inn.
Massive overhaul to the entire map outside of town and inside the town mine to make almost every rock wall mineable, and with increased node placement. Some new cave chambers have been made, and the groundwork has been made for more.

Engineering has received a huge overhaul:
Most engineering recipes have had their recipes changed to require bronze, copper, and cogs.
Locks and Keys are now made exclusively by engineers.
Cogs are now only smithed by bronze.
Bronze Lampterns, with a stronger (and eerily green) flame, made from bronze+copper. Expensive but superior.
Wooden Prosthetics are now crafted via the engineering skill.
Bronze prosthetics, which are forged by engineers, are superior limb replacements, allowing for full finger movement (Meaning weapons can be used with them.)
More prosthetics and constructs to come.

### **_Planned:_**
Smithable items added to EACH type of bar.

### **_PSA about some new item's sprites:_**
Due to the sheer size of the update, not every item's sprite is complete
Blacksteel Plate is being worked on currently.
Bronze Prosthetics are scheduled to be worked on soon.

(Not all additions are inside PR as of now. Updates will come as sprites and code are finished.)

## Why It's Good For The Game

This will be a MAJOR update to smithing, mining, and many other town aspects, which will create a load of new opportunities and give lots of things to do even for those who are not smiths. It will also allow for a greater level of customization to gear for those who can afford it. Finally, it will introduce new things for smiths to create and smelt, as well as a true late-game goal.

### Credits as of now

**Code assistance:** 
Randall 
Sigma

**Sprite work:** 
Luto
Olirant
Kavrick

**Map work**
Luto

### CODE REVIEW

**Comment by Kyogon** [comment]
> Gotta admit, adding all these metals and allows feels like bloat to me. Steel already exists, and isn't even necessarily kingshit it's often just more durable. I am not sure most of the playerbase would _care_, and you're just expanding the crafting menu while also drowning miners in extra materials to bring home on the off chance they exist.
> 
> Also we have several set, intentional mining locations, including a whole ass volcano we don't need to expand the map, it funnels miners to where they ought to go. That's good.

Well, the metals are what Pantsu wanted to add. Originally Legendary Smithing was only about smithing, but after discussing it with them they gave me their ideas for those metals and I simply decided to spearhead the progress. 

Also I spoke to Pantsu about the mining locations too, and until the mountain map is done, anywhere outside town was designated as fine to overhaul. Currently mining nodes are less than optimal considering the few locations that can be mined at.

I understand being frightened by change, but a bit of variety is nice to have.

**Comment by AllCorruptingWyrm** [comment]
honestly this doesn't look too bad? Like I understand the mining issue but this could be easily alleviated with a smoke pipe full of swampweed and getting blessed by the Priest, as both last about 45esh minutes and will give +3 fortune, ontop of any moodlet bonuses too.

**Comment by Lutowski** [comment]
> honestly this doesn't look too bad? Like I understand the mining issue but this could be easily alleviated with a smoke pipe full of swampweed and getting blessed by the Priest, as both last about 45esh minutes and will give +3 fortune, ontop of any moodlet bonuses too.

i don't want to smoke ELF weed i want to mine

image

**Comment by Varoxus** [comment]
don't forget to add your new trait to the pilgrim/towner versions of blacksmiths too

**Comment by Varoxus** [comment]
Some notes: I don't think you should be lowering the light radius of the torch/lamp in favor of making the bronze lamp the better choice, especially since not everyone will want to have a green tint on everything. Should keep the old numbers and still have the bronze have that 1 extra range. On the topic of lamps, you need to give the bronze lantern an activated sprite. As it currently is, it will turn invisible once you turn it on because there's no sprite for it to use when it's activated.

A lot of items are missing their smelt_bar_num entries, if you're looking to make it so all items get the same amount of bars out that you need to put in, that will need another pass. The multi-bar smelting also doesn't work on the greatforge, it only works on the regular forge.

Need to add an artificer key to the steward's spare key chest. (it also needs a farm key in there but that's not in the scope of this PR)

Coal costing more to import than metal ores seems a bit strange.

The sprites for the gold mask are all facing the wrong direction save for the southern-facing sprite. It'll make it look like your neck is snapped when you're moving around with it on.

Why did you move the prosthetics from the item crafting file to the structure crafting file? They're items, not structures.

**Pull request merged**
