### PR TITLE
Unapologetic Merchant Buff - doesn't actually buff the merchant, but fixes a bug with coins and replaces chud-tier combat music. also fixes flammable steel and improves workplace safety in accordance with OSHA standards.

### PR DESCRIPTION
**Pull request by kittysmooch**
## About The Pull Request

an old roguecode feature was that piles of coins would scatter if tossed onto the ground. an old roguecode bug is that they would delete themselves if you threw them onto a table. at some point the bug was partially fixed by preventing table deletes, but it only had piles of coins drop one sole singular coin when thrown on the floor. that's boring! so now coins piles properly scatter into an equal amount of individual coins on the floor. yipee!! you can still safely pile coins on the floor by dropping them, and of course you can pass piles of coins with the give function, but now you can throw piles of coins at people and theyll have to pick them all up.

this also replaces the merchant combat music, which was a shitty techno remix of hava nagila. aside from being a shitty antisemitic joke it's also an aggressively mid track that doesn't fit the vibe. it has been replaced with a fancy and frenetic little piano track:

https://www.youtube.com/watch?v=0MRdtZFqwok

this is off the Daggerfall soundtrack, which has been free to download for over a decade, so I wouldn't sweat Todd Howard coming after us for it. Because it's such a fancy track I also gave it as combat music to a couple of noble and courtier roles, where it felt fitting.

## Why It's Good For The Game

bugs suck! i hate chuds!

### CODE REVIEW

**Comment by kittysmooch** [comment]
new commits:
- hearths now have density, but can be climbed or have items thrown over them like tables. You can still throw someone on top of one if you'd like, but they're less of a ridiculous laghazard now and will no longer need any fences mapped around them.
- did you know this can happen?
image
well, it can't anymore. i gave fireproofness to items where i thought it might make sense.

**Comment by kittysmooch** [comment]
Removed stun maces from the merchant's cargo packs because instant win sticks are boring.

**Comment by kittysmooch** [comment]
fixed onmob transforms for the flamberge

**Comment by ChungusGamer666** [comment]
not the heccin' antisemitic jokes! 

from the river to the sea in bio doe

**Pull request merged**
