### PR TITLE
allows renaming of everything childed to obj/item/rogueweapon, crossbows and bows, and all clothing and armor items

### PR DESCRIPTION
**Pull request by kittysmooch**
## About The Pull Request

image

you can now rename anything childed to rogueweapon by using a feather on it. yay!

## Why It's Good For The Game

its cool :3c

### CODE REVIEW

**Comment by space-dad** [comment]
I really like the idea of being able to rename stuff, but I think having it be based around an item that encourages cooperation / interaction would be for the benefit of RP. Why not have it be, for example, a Chisel or Maker's Mark Stamp that can be used by someone with the relevant skills to then stamp the item? This would bring people together at best, and put another person in the blacksmith's line at worst. (But as far as I know blacksmiths like it when they do something that isn't make full plate for the 4th adventurer within ten minutes.)

**Comment by Onutsio** [comment]
How does this work with umm, examining ppl? Like can u still tell a sword is a sword if its renamed

**Comment by kittysmooch** [comment]
> How does this work with umm, examining ppl? Like can u still tell a sword is a sword if its renamed. Cool stuff

it'll return the rename, you'll have to rely on our relatively good onmob sprites to tell what they're carrying. This PR would probably be more problematic if we killed experimental onmobs.

**Comment by kittysmooch** [comment]
> I really like the idea of being able to rename stuff, but I think having it be based around an item that encourages cooperation / interaction would be for the benefit of RP. Why not have it be, for example, a Chisel or Maker's Mark Stamp that can be used by someone with the relevant skills to then stamp the item? This would bring people together at best, and put another person in the blacksmith's line at worst. (But as far as I know blacksmiths like it when they do something that isn't make full plate for the 4th adventurer within ten minutes.)

i could ponder it, though i think being able to do it yourself is good for e.g. bandits and other people who might want a cool name but not go into town to do it

**Comment by kittysmooch** [comment]
surely we'll just kill people who do that @Ollanius

**Comment by kittysmooch** [comment]
image

it has the original item name now, yipee!

**Comment by kittysmooch** [comment]
went ahead and added renames to bows, crossbows, and all children of obj/item/clothing, so you could rename special armor. if we ever get a clothing enchantment system you could go ahead and make shoes of the biliferous rat or whatever too.

**Pull request merged**
