### PR TITLE
INQUISITION PT 1 - THE ROLENING

### PR DESCRIPTION
**Pull request by Onutsio**
## About The Pull Request

The First Step of a Great, Inquisitorial revamp.  Does the following:

Re-adds Inquisitorial assistants, under the role ORTHODOXIST(2 of these max). These are split into an advclass selection between the Psydonian Templar, who's service is ensured to the Inquisitor and the Inquisition of Otava, and the Confessor, a sneaky eyes in the dark/backstabbing type.  Comes with BRAND NEW, COOL:TM: Armor by cre!

New Tutorial text for Inquisitor, reinforcing the divide between Psydonism and the Church. Inquisition still is based under the church.

_tutorial = "PSYDON YET LIVES. PSYDON YET ENDURES. You have been sent by the High Bishop of Otava, leader of a radical denomination of the Holy See that still believes in the endurance of PSYDON, and holds him above the Ten. Officially, you are here on diplomatic business. /n /n Unofficially, you work to cast out the sinners from God's house. Heresy of all kinds must be corrected; from Ten-worshippers that stray too far from doctrine, to Ecclesial fools that worship Ascendants. The Duchy tolerates you due to your ability to fight the inhumen, and the Church tolerates you due to your aligned goals...but it is probably best to not let them peer too closely._

PSYDONIAN Templars are 1:1 Templars, + a Silver psycross and a new fit. Additionally being bound to the Inquisitor, rather than the church.

Inquisitionred
psydonarmor1
psydonarmor2
psydonarmor3

## Why It's Good For The Game

Separates the Inquisition, giving it more identity -disconnected- from the Church. Sets up for Inquisitors to have some lackeys to help with their rather stressful role. 

Next to come: Inquisitorial Toys and borderline Heretical relics!

### CODE REVIEW

**Comment by Onutsio** [comment]
> Hear me out, instead of Templar. Adjudicator.

This rocks u right

**Comment by Cleric2145** [comment]
Faith Militant? 😁

**Comment by Ollanius** [comment]
> Ten PQ is probably a bit much what even is bandit but whatever, levers for admins to decree

I disagree.
It's important to emphasize that the Inquisition's capacity for causing round-altering consequences _(through subterfuge, interfactional conflict and outright murder)_ rivals - if not exceeds - the Bandit's own. A high threshold of 'player quality' points helps to minimize the chance that these roles are taken by irresponsible, inexperienced, or outright malicious players.


> As a concept itself, though... eh. I feel like this'll just make Psydonites and everyone else inherently hostile by the implication, as well as encourage people fighting within the church itself which, sure, the templars might have a hoot with but I am not sure that'll be highly regarded the rest of the roles, all staunchly non-combat, there. I would recommend pushing the tutorial text to be more diplomatic or something, but having a "secret" soft-antag directly attached within the town is going to faceplant after two or three rounds of continuity. They'll get airstriked as fast as a CM who openly Zizzles.

I partially agree.
The Inquisition being given the greenlight to explicitly function as 'soft antagonists' would be nice, but I think giving people the option to simply play them straight _(as genuinely good - if somewhat archaic-and-prudish - people)_ would be great. This would also make it much easier for the Inquistion to 'fly under the radar', so to speak, if they need to pull some antagonistic actions.

**Comment by Vexcint** [comment]
"PSYDON YET LIVES. PSYDON YET ENDURES. You know this well. Sent by the High Bishop of Otava, you are tolerated by the Duchy and Church, with a pleasant lie to the citizens."

This makes it sound like both the Duchy and Church _knows_ the new intentions of this Inquisitor (Aka doing whatever they want to rid the town of the Ten Worship). Why in the hell would both these Factions even allow such a person to be there and basically kidnap and re-educate the township when both these factions are Ten followers?

**Comment by Onutsio** [comment]
Tutorial text changed. Also, just removing the mapping changes for now. Will get them later bcuz maintaining a pr that takes a bit to merge and mapping dun manor in the same one is Incredible Pain

**Comment by Onutsio** [comment]
MAP stuff BACK IN. Unarmed class(equal to templar monk) IN. GOOD 2 MERGE

**Comment by UncleBourbon** [comment]
please bro let the smith be able to make the helmets and such and not just the haubark, the armet is pure drip. If smiths can make astrata helmets and noc helmets, Psydon helmets should be smithable as well....

**Pull request merged**
