### PR TITLE
Armory Key

### PR DESCRIPTION
**Pull request by Kavrick**
Adds an armory key to a bunch of keychains and locks the armory behind it.

Every single person with a garrison key can just waltz into the armory and raid it, I didn't knee-jerk make this PR, I gave it some time but it has become a round-after-round issue of people doing it. If you need access to the armory you can talk to; The guard captain, the hand, the steward, the marshal, or the monarch. This is plenty of people to still give people access to the armory if it's _needed_.

### CODE REVIEW

**Comment by kittysmooch** [comment]
i had the same thought and would have done this already if i wasnt deep in another pr for another base, +1 on that front, though i wonder if we really need to keep all of the garrison out of there or whether the ring that RGs MAAs and Squires get could have it added too

**Comment by Kavrick** [comment]
> i had the same thought and would have done this already if i wasnt deep in another pr for another base, +1 on that front, though i wonder if we really need to keep all of the garrison out of there or whether the ring that RGs MAAs and Squires get could have it added too

So, both royal guard and MAA start with perfectly functional gear. It's better to actually have to get a superior to let you in and check what you're taking rather than it just being a free-for-all. This also means it's harder for people to steal keys to the armory. I gave the key to a good few roles so the keep really should never go without at least a couple of people with an armory key.

**Comment by HeroWithYay** [comment]
At the very least Royal Guards should have this. Removing the keys from squires is justifiable, even though squires start with literally no gear and must go to the armory at the start of every round. So this just adds more pointless roundstart busywork.

This is just going to get the door broken down every time.

**Comment by Kavrick** [comment]
> At the very least Royal Guards should have this. Removing the keys from squires is justifiable, even though squires start with literally no gear and must go to the armory at the start of every round. So this just adds more pointless roundstart busywork.
> 
> This is just going to get the door broken down every time.
> 
> God forbid someone latejoin.

Armory access isn't a right. Lots of roles still spawn with perfectly good gear. If it's really that big of a labor to ask one of the five roles to let you into the armory then I don't really know what to say?

**Comment by ThinkArbies** [comment]
> > At the very least Royal Guards should have this. Removing the keys from squires is justifiable, even though squires start with literally no gear and must go to the armory at the start of every round. So this just adds more pointless roundstart busywork.
> > This is just going to get the door broken down every time.
> > God forbid someone latejoin.
> 
> Armory access isn't a right. Lots of roles still spawn with perfectly good gear. If it's really that big of a labor to ask one of the five roles to let you into the armory then I don't really know what to say?

And yet those roles are never guaranteed to spawn most of the time, and they have even less of a need to go visit the armory let alone start paying attention to it.

**Comment by UncleBourbon** [comment]
the keep gonna run out of money for how many iron gates they need to replace in future rounds

**Comment by GeneralPantsuIsBadAtCoding** [comment]
After a bit of having it merged I gotta say: This sucks. Reverting.

**Pull request merged**
