### PR TITLE
Update rogue STAT +1 SPE +1 END.dm

### PR DESCRIPTION
**Pull request by lalaria1**
## About The Pull Request
Ads +1 SPE and +1 END to Duelist stats

## Why It's Good For The Game
I compared a few classes, and Duelist, which is meant to go toe-to-toe with bigger opponents, seems very weak stat-wise. I think this changes it in the right direction, but I feel it might not be enough.

### CODE REVIEW

**Comment by MaSvedish** [comment]
yeah no, duelist is quite literally amongst the strongest for sword fighting classes. I play Duelist For This Reason. It doesnt need bonuses.

**Comment by Lutowski** [comment]
No. Duelist is a cracked subclass that comes equipped with a rapier and buckler shield, and you just gave them better strength than Warrior and in total, bonuses in five different stats. They're in a good place right now, don't need to make them good-er. Closing with that in mind.

**Comment by lalaria1** [comment]
> No. Duelist is a cracked subclass that comes equipped with a rapier and buckler shield, and you just gave them better strength than Warrior and in total, bonuses to five different stats. They're in a good place right now, don't need to make them good-er. Closing with that in mind.

..I didn't change thier strength though, what do you mean?

**Comment by Lutowski** [comment]
> > No. Duelist is a cracked subclass that comes equipped with a rapier and buckler shield, and you just gave them better strength than Warrior and in total, bonuses to five different stats. They're in a good place right now, don't need to make them good-er. Closing with that in mind.
> 
> ..I didn't change thier strength though, what do you mean?

speed* lmao

**Pull request closed without merging**
