### PR TITLE
 Adding subclasses to Forlorn Hope - The Tools of Their (former) Masters

### PR DESCRIPTION
**Pull request by MicroMinty**
Adds more variety to forlorn hope mercs, using less than oft seen weapons.

## About The Pull Request
Adds three subclasses to Forlorn Hope mercs. Names are being worked on, but I would appreciate input on them.

Bindbreaker: Default forlorn hope loadout, nothing changed.
Lashturner: Trades mace skill for flail/whip skill, and spawns with a whip instead of a warhammer. Turn the tools of confinement into tools of freedom.
Bladehand: Uses a dagger and parrying dagger, trading shield and hammer for them. Less shield and mace skill, but of course, it's daggers. Wondrous daggers. Use the oldest bladed weapon, the humble knife. One of the easiest to hide.

## Why It's Good For The Game
Nice to have diversity, and puts a showcase to less-often seen weapons.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
uhhh maybe not a good idea
not everything needs an archetype and whips are lowkey super busted and it is a rly good thing that they are not more available. crit resist medium armor whip sounds hellish.

**Comment by MicroMinty** [comment]
Don't merge until I differentiate them better, as well as take the above suggestion into consideration.

**Comment by MicroMinty** [comment]
classes changed and differentiated. whip users no longer get skill to parry with practically anything, and stats have been shifted for all subclasses to reflect what role they should play in combat and such, as well as just to add flavour.

**Comment by LittleEvil9** [comment]
I don't think they need subclasses, medium armor + crit resist is already absurdly strong.

**Comment by radarseas** [comment]
not sure how I feel for the lack of stat differing for some pretty meta weapon choices...

I'd give a speed malus for the whip class, otherwise these guys can just get a steel flail, ignore your critical strikes and absolutely dunk on you with a whip trying to run because they have high endurance to let them keep up sprinting plus warrior strength.

they're decently scary but whips can't parry so if they lose their shield they're pretty screwed, that's fair, crit resistance is a bit wacky but nothing too out of sorts since vitues exist.

however even battle paladin and old-now-gone flail bandit has/had this weakness. I don't include inquis/dungeoneer as they have a 3 tile one-off whip and are exclusive one-slot jobs.

---
that third class though...

medium armor fair because rogue exists but urm...? crit resist, a little wacky? but +2 strength AND KNIVES ON TOP? uhhhhhhhh... 40% AP is pretty strong but if you're stacking this with thuggish or the likes for 14 strength stats... you're able to fight pretty much everyone consistantly regardless of armor solo but legendary swordsmen with decent wrestling. That's a bit fucked for a non-antag.

Journeyman wrestling makes them pretty hard to counter too, unlike most people that use daggers because you can't easily just... tackle them down, since strength stacking can be a thing on top, uhhh. yeah...

that third class is a bit silly, assassin rogues are strong but these guys have crossbow stats too, they are... a bit too good...? that's not even counting they can still use shields with knives against the ranged option that normally defeats dagger users.

urm... yeah... that's a problem for a non-antag role

**Comment by radarseas** [comment]
I've taken a look at the weapons myself again

---

Remember these weapons have high armor peircing ratings. 40% damage, 2 tile whip is pretty strong especally without critical hit stuns, but mallie, shield stats and no differing con or strength stats, plus wrestling so you can't even disarm these guys.

---

I'd lower the whip class's con or their strength stats, these guys can basically facetank everything with crit resistance, make them spend a virtue for it instead.

They get crossbow stats. Being shot in the leg and beaten with a 40% AP weapon from 2 tiles away sounds like an instant 1v1 win combo nobody can really counter.

Yeah, that's pretty strong.

---

As for knives without easily tackable stats, that's pretty strong but now I've looked at whips... its... not as busted but still strong. You might be able to do something with it but I'd be careful with their crit-resist still, make them spend a virtue for it, give them something to make up for it or a gimmic than just different weapons.

I still think it can work, but you'll need to account for the fact knives can do insane damage aimed at hands, since they pierce a lot of armor and bypass parries well because they can strike fast inherrently.

**Comment by Lutowski** [comment]
not really sure on my stance with this one, forlorn doesn't need subclasses. in fact I don't think a lot of classes do at the moment so closing this until the need changes

**Pull request closed without merging**
