### PR TITLE
Poop Filter Removal

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
Removes the grainy filter effect.

Port of https://github.com/russ-money/subterra/pull/35 by @kaylexis

### CODE REVIEW

**Comment by WatermelonsEverywhere** [comment]
the poopendarken era is ending

**Comment by bearrrrrrrr** [comment]
the pooplightening ...

**Comment by kittysmooch** [comment]
can we have a little grimshart.... as a treat?

**Comment by cdb-is-not-good** [comment]
tbh i like the filter, but i do agree it'd be better if it were toned down a bit

**Comment by bearrrrrrrr** [comment]
actually minor request, can we keep the filter in but just not apply it to folk on spawn? i kinda wanna fuck around w/ it to maybe apply for dark areas or smth

**Comment by Ollanius** [comment]
I prefer the grit.

Keeping the Grimshart™ vision as a toggleable option _(in the same tab-and-vein that the 'CRT' filter occupies)_ would be very nice. Like what Bear and Kaylexis said, it shouldn't be too hard to make it disabled by default for those who prefer a more clean-and-unassailed view.

**Comment by ChungusGamer666** [comment]
lmfao

**Comment by Hemlock32** [comment]
Don't see the need for this. It fits a particular artstyle/aesthetic quite well, sets a certain tone/mood, doesn't detract from anything.
It doesn't even remotely come off as "Poopdark" as people would say. It comes off as like, slightly gritty and dark at most.

And, when combined with the CRT filter it feels, incredibly flavourful like some old fantasy RPG game.

**Comment by chemistrymain3** [comment]
> Don't see the need for this. It fits a particular artstyle/aesthetic quite well, sets a certain tone/mood, doesn't detract from anything. It doesn't even remotely come off as "Poopdark" as people would say. It comes off as like, slightly gritty and dark at most.
> 
> And, when combined with the CRT filter it feels, incredibly flavourful like some old fantasy RPG game.

The reason is that it looks ugly and isn't done well and detracts from everything. Glad to clear this up.

**Comment by bearrrrrrrr** [comment]
my opinion on this kinda reversed. the game looks like hot dogshit without the filter because the people that made this code were talentless hacks that couldn't make something look good to save their lives.

i'd like if this was a toggle a la crt i think. thanks i love u

**Comment by lpeapnni** [comment]
Just merge this shit bruh

**Comment by Lutowski** [comment]
Closing this because I'm about to PR in a toggle that should work.

**Pull request closed without merging**
