### PR TITLE
Physician's Move

### PR DESCRIPTION
**Pull request by Kavrick**
barber

So with the more recent changes, I decided that if the physician's aren't going to be a full part of the keep, I'd move them to a place where they're more likely to get interaction, not only that, but I've sprited in an entirely new physician's sign which is animated. This puts them next to the gate, making it more likely that injured travelers will stop on, rather than being in the other corner of the town.

StrongDMM_QtFOvcBRkj
StrongDMM_mVOfOURFlJ
StrongDMM_HdVvk9foMa

### CODE REVIEW

**Comment by benj8560** [comment]
I'd like to be able to travel fully around the keep. Could some ground get added around here?
StrongDMM_kRBp3aKDL3

floating trees:
StrongDMM_dAwtYye5lA

Also the only barrel in there is (I believe) a non-prefilled one.  Would like prefilled water barrel filling barrels is another chore I don't need.

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Besides the upper concerns I'm just a bit confused where... the wall went? I know its barely used and all but it'd be odd if there's just a part of town no longer walled off. Looking good though, very nice placement as well!

**Comment by Lutowski** [comment]
> Besides the upper concerns I'm just a bit confused where... the wall went? I know its barely used and all but it'd be odd if there's just a part of town no longer walled off. Looking good though, very nice placement as well!

believe the idea is that the physicians' is part of the wall to make up this sort of gatehouse clinic

**Comment by Kavrick** [comment]
Everything here has been addressed, did a little touch-ups and showed pantsu what it's supposed to look like on discord.
StrongDMM_BITbihPojh

**Pull request merged**
