### PR TITLE
Tweak human AI, readd stamina to NPCs, misc. optimisations

### PR DESCRIPTION
**Pull request by noelle-lavenza**
## About The Pull Request
- AI-controlled mobs now regenerate stamina (and do some other misc. processing).
- Human NPCs will no longer take actions while busy (i.e. getting up).
- Tries to optimise build_appearance_list.
- Makes the sleeping status effect slightly less expensive by removing a redundant update_health call.
- Optimises inhand generation by cacheing an IconStates call.
- Removes the indefatigable trait from NPCs.
- Fixes me breaking conveyors because I didn't understand something.

## Why It's Good For The Game
The AI should be less overpowered, and the game should run a good bit faster. Also fixes conveyors moving you at lightspeed LMAO

### CODE REVIEW

**Comment by noelle-lavenza** [comment]
HEY PLEASE TESTMERGE THIS I DID SOME LOCAL TESTS BUT I AM NOT GOOD ENOUGH AT THE GAME TO KNOW IF ICONS ARE WRONG, AND THIS PR TOUCHES OVERLAYS AND INHANDS. PLEASE PLEASE PLEASE PLEASE PLEASE PLEASE TESTMERGE THIS.

**Comment by noelle-lavenza** [comment]
https://www.youtube.com/watch?v=me-HUZLiTcU

**Comment by noelle-lavenza** [comment]
Removed the broken/dangerous changes, tested locally by killing a goblin to death and washing off, and things seemed to be fine. Woo.

**Comment by Cleric2145** [comment]
Huh? There's conveyors in the map? Are they used for the feeding hole or something?

**Comment by EvenInDeathIStillServe** [comment]
> Huh? There's conveyors in the map? Are they used for the feeding hole or something?

They're used in a dungeon.

**Pull request merged**
