### PR TITLE
Bow QoL feature: Right click the quiver to auto load a Bow in the active hand

### PR DESCRIPTION
**Pull request by FreeStylaLT**
## About The Pull Request
dreamseeker_mL31ZBqWY6

## Why It's Good For The Game
Anyone that tells me pixel hunting a thin ass bow sprite with an arrow is peak gameplay is gonna get shown as a crying cheems vs me the gigadoge

### CODE REVIEW

**Comment by Alexi-6410** [comment]
...you can already do this by clicking on the quiver with the bow.

**Comment by Alexi-6410** [comment]
I mean, technically this is different (right click the quiver instead of left-click?) but- yeah, you can already do this with left click.

https://github.com/user-attachments/assets/6acfb649-3c3c-4936-bb0a-612b48aaa5b8

**Comment by kittysmooch** [comment]
in addition to already being able to click the quiver with the bow you can also click anywhere in the negative space of the bow sprite, so you don't have to pixel hunt at all. a nice QOL though would be the ability to unload a bow and send the arrow into your empty hand instead of the floor.

**Comment by Lutowski** [comment]
i will say that rmb to reload is better comfort-wise because having fire and reload keyed to lmb has contributed to a lot of friendly fires

**Comment by FreeStylaLT** [comment]
I am very embarrassed right now

**Comment by SirSwagmeyer** [comment]
You can actually just rebind it to right click. My bow reload is rebinded to alt + right click

**Pull request closed without merging**
