### PR TITLE
Replaces combat_fancy.ogg with a different song

### PR DESCRIPTION
**Pull request by sneksnek**
## About The Pull Request

Replaces the combat_fancy.ogg file with a new file containing the battle music from Arcanum, a classic early 2000s RPG.

## Why It's Good For The Game

The current fancy combat music sounds like a piano midi and features a full two second gap at the beginning. This music is fine in its own merit but as combat music, it's lacking. It's quiet, not very tense, but at least matches the sophisticated aesthetic of nobility.

I dug around in my youtube dnd music playlist and selected this new song to supplant it. It's a modest mixture of tension and  string quartet. It's not the thriller, high BPM music attributed to bandits, but you're a highbrow aristocrat, not a meatheaded adrenaline junkie abnegating breeches and decorum.

Youtube link for hearing: https://www.youtube.com/watch?v=rbNxjnRoq0k

If you don't like this, replace the music with something else. Please, the original music SUCKS.

### CODE REVIEW

**Comment by kittysmooch** [comment]
> The current fancy combat music sounds like a piano midi and features a full two second gap at the beginning. This music is fine in its own merit but as combat music, it's lacking. It's quiet, not very tense, but at least matches the sophisticated aesthetic of nobility.

it is a piano midi. it's combat music from a 90s rpg. there's nothing wrong with this.

> If you don't like this, replace the music with something else. Please, the original music SUCKS.

be less of a dick?

anyway, you nearly doubled the filesize with this replacement and that contributes directly to load in time, you should consider compressing the track.

**Comment by sneksnek** [comment]
> > The current fancy combat music sounds like a piano midi and features a full two second gap at the beginning. This music is fine in its own merit but as combat music, it's lacking. It's quiet, not very tense, but at least matches the sophisticated aesthetic of nobility.
> 
> it is a piano midi. it's combat music from a 90s rpg. there's nothing wrong with this.

What's the source? I tried searching extensively for any track named "Wilderness" by Eric Heberling and I couldn't find anything.

**Comment by kittysmooch** [comment]
it's from daggerfall

**Comment by sneksnek** [comment]
> it's from daggerfall

https://www.youtube.com/watch?v=0MRdtZFqwok

This isn't combat music. It's overworld music. There is palpable contrast between this barebones piano midi and any other combat track in the game. There is little tension.

Besides that, the track size was increased by about 1 megabyte. I could compress it if really necessary, but I don't know why it's crucial when it is a single megabyte difference and there are 12 other tracks in the folder with greater sizes. I can't compress it much without lowering settings below what other files have. I tried an online compressor with full bitrate that lowered its filesize from 1.99MB to 1.80MB. If you have another idea, let me know.

**Comment by bearrrrrrrr** [comment]
disrespect on the daggerfall name -10000 (this is a joke idc)

**Comment by Lutowski** [comment]
I like the piano because it reflects on the refined, composed nature of nobles, and the suggested song sounds more clandestine than I'd like, but I can sit here and armchair about music all day. 

I would find something that's still piano, but with an upped tempo instead.

**Comment by radarseas** [comment]
could settle with something like:
https://www.youtube.com/watch?v=DtKCNJmARF0

Beethoven Virus kind of fits that regal-rich theme while being dramatic enough for combat music and it goes on long enough to fill in for long-term drawn out fighting.

**Comment by sneksnek** [comment]
Alright. A couple ideas:
1. "Dance With Chaos" by Lionel Yu: https://www.youtube.com/watch?v=MwAS0MmwxXI
2. "Endcaller" (FFXIV Endwalker) on piano by SLSMusic : https://www.youtube.com/watch?v=pD7UtF_p9k4 (probably snip just ~0:17 - ~1:02)

I'll let this bide and welcome other suggestions. I asked on the discord for ideas too.

**Comment by sneksnek** [comment]
I can't make up my mind on a good song for this. I'll let someone else eventually storm up a better solution if there's interest,

**Pull request closed without merging**
