### PR TITLE
Deathsight: Necra & Zizo clerics can detect when someone dies

### PR DESCRIPTION
**Pull request by Ephemeralis**
## About The Pull Request

In the interests of giving divine magic more Cool Stuff, this introduces a deathsight trait for Necra & Zizo clerics (the lich also gets it) that tells them whenever a player (aka a mob with a client) dies for good. I don't mean like "sees the Dying screen" dead, I mean like, sees the YOU HAVE PERISHED screen levels of dead.

This includes a very loose and approximate location of where someone has eaten shit and died, with fuzziness for every category area and zone *except* the church. What this means is that if someone dies in town, you'll only know that they died in town, not exactly where. If they died in the wilderness somewhere, you'll only know they've died in the wilds. You may not even be able to ascertain fully where they've died at all.

You only get access to this trait if your class has access to devotion (aka holy magic) in any way. Casual Necrans and Zizo followers don't get it normally.

## Why It's Good For The Game

Adds a neat mechanical onus towards playing the death-sensitive roles for certain character concepts. Encourages relocating people before you murder them to throw off those pesky death-priests.

### CODE REVIEW

**Comment by Onutsio** [comment]
Very cool! Necrans needed smthing.

**Comment by MaSvedish** [comment]
You should make it if they have higher level of miracles they can detect what direction they died in, similar to the horn code. Even if its a generalized cardinal direction.

**Comment by bearrrrrrrr** [comment]
uhhh i dunno about this. 'somebody, somewhere, has just bit the fucking dust' is mechanically important enough by itself


>  Encourages relocating people before you murder them to throw off those pesky death-priests.

this is literally round removal and i can really easily see ppl moving bodies to impossible to find corners avoid being caught :/

**Comment by Ephemeralis** [comment]
> uhhh i dunno about this. 'somebody, somewhere, has just bit the fucking dust' is mechanically important enough by itself without the area notice. consider replacing that part with simply knowing whether or not the person is mechanically dead via looking at them? (ik they have the whole soul-vision thing goin on)
> 
> > Encourages relocating people before you murder them to throw off those pesky death-priests.
> 
> this is literally round removal and i can really easily see ppl moving bodies to impossible to find corners avoid being caught :/ _**really**_ not a fan of this one, i can already foresee someone doing this to a corpse and being boinked for round removal.

If anything, I think that the presence of this mechanic encourages people to keep people alive *more*. Death tips off the Necran worshippers and the Zizo no-gooders. You ideally want to keep them alive to avoid suspicion. It's probably worth trying with a testmerge to see how it shakes out before we make any changes.

**Comment by bearrrrrrrr** [comment]
> > uhhh i dunno about this. 'somebody, somewhere, has just bit the fucking dust' is mechanically important enough by itself without the area notice. consider replacing that part with simply knowing whether or not the person is mechanically dead via looking at them? (ik they have the whole soul-vision thing goin on)
> > > Encourages relocating people before you murder them to throw off those pesky death-priests.
> > 
> > 
> > this is literally round removal and i can really easily see ppl moving bodies to impossible to find corners avoid being caught :/ _**really**_ not a fan of this one, i can already foresee someone doing this to a corpse and being boinked for round removal.
> 
> If anything, I think that the presence of this mechanic encourages people to keep people alive _more_. Death tips off the Necran worshippers and the Zizo no-gooders. You ideally want to keep them alive to avoid suspicion. It's probably worth trying with a testmerge to see how it shakes out before we make any changes.

yyyeah alright i can see that

sure, i'm down for giving it a spin

**Comment by EvenInDeathIStillServe** [comment]
Could you make the message generation part happen outside the player_list for loop, and then applied when relevant?

**Comment by radarseas** [comment]
not sure i like this because you might get said clerics rushing people before they can rot and turn into zombies when dying to honest mistakes.

Maybe only if people get decapitated, or otherwise irrevivably mangled, add a delay so unless you're close by, they'll have already rotted and zombified.

**Comment by Ephemeralis** [comment]
> Could you make the message generation part happen outside the player_list for loop, and then applied when relevant?

Done!

> not sure i like this because you might get said clerics rushing people before they can rot and turn into zombies when dying to honest mistakes, reducing undead antagonism.
> 
> Maybe unless if people get decapitated, or otherwise too mangled to rise up as a zombie (gibbed); a delay so unless you're close by, they'll likely be close to rotting or zombifying.

The area range is *so* wide for this. For example, dying out by the spawn carriage is "wilderness". Dying in the depths of the grove is "wilderness". You can walk and search for 10-15 minutes in that entire radius and still not possibly find someone in it. Someone dying in town can be *anywhere* in town - the rooftops, a closet, a locked house, the dungeons, the vault... the intent behind keeping the locations indistinct (except the church) is to address exactly the issue you've mentioned.

**Pull request merged**
