### PR TITLE
Inn Remapping

### PR DESCRIPTION
**Pull request by Kavrick**
Gives the inn a glow up, including a beer garden and generally better space usage.

StrongDMM_4glOuddft3

### CODE REVIEW

**Comment by chemistrymain3** [comment]
Honestly, this is too much of a glow up.

The town just keeps getting prettier and prettier. I'm not advocating for grimshart, but it also shouldn't look like a five star resort.

**Comment by Exo-212** [comment]
The fenced garden with track of dirt for planting and flowers for - flowering? - is very nice in a pastoral "wouldn't it be nice?" kind of way, which I feel is a tone issue for an inn with the benefit of a large soilson compound directly to its south.

Building in space for Innkeeper/Cook characters to self isolate by growing their own food undercuts one of the ways people are mechanically encouraged to interact.

If you want to - say - bring a cart full of produce by the inn and sell your wares (perhaps under stockpile rate for bulk purchase) why would the staff at the inn buy any of that (and use the mammon they've been collecting serving food and drinks) if they're running their own farm out the back?

The fenced area to the bottom-right of the image feels like it's got unclear use with the relocation of the well to the back garden.

Additionally, with how hard it is to navigate with more than one person through a one-tile through-way, I'd suggest removing it entirely and moving the Inn to be flush with the Town wall.

In fact, the garden could be eliminated entirely by moving the inn west to the wall, which would free up that map space for the rest of the town, and make the central square with the fountain less cramped.

**Comment by Mikierpg** [comment]
This new inn has LESS space than the current one for farming.
The left most garden area is all dirt in the current map, and adding in the stone path means there is vastly less space to plant crops.
Even if it were removed, they'd just go 5-10 tiles to the north and plant crops in the same place the church does. Unless you want all the dirt removed from the town, there isnt going to be a map-solution to Inn chars doing farmwork.

**Comment by Mikierpg** [comment]
On the feedback front, it looks like you fully removed the Xylix Machine, not sure if thats intentional but I'd like to point it out just in case it isn't.
It might also be worth putting a scom into the north seating area, but probably not a huge issue.

**Comment by Exo-212** [comment]
> Unless you want all the dirt removed from the town, there isnt going to be a map-solution to Inn chars doing farmwork.

Sounds like a good-enough solution to me, but probably beyond scope.

**Pull request merged**
