### PR TITLE
Adds RMB Keybinds

### PR DESCRIPTION
**Pull request by Just-Sim**
## About The Pull Request
Screenshot 2024-10-30 202747

Adds RMB Intent Keybinds.

1. Select Feint Intent (Default: Shift+1)
2. Select Aimed Intent (Default: Shift+2)
3. Select Strong Intent (Default: Shift+3)
4. Select Swift Intent (Default: Shift+4)
5. Select Defend Intent (Default: Shift+5)
6. Select Weak Intent (Default: Shift+6)
7. Cycle RMB Intent (Default: N)

https://github.com/user-attachments/assets/2eff17a4-fb7f-4f28-9a12-4c21d5a177c9

## Why It's Good For The Game
Less clicking more gaming.

### CODE REVIEW

**Comment by Just-Sim** [comment]
Sidenote, because of how this codebase compiles, returning players may or may not need to set the keybind themselves, clicking "Set to Default" at the bottom of the keybinds menu will set it to the appropriate keybinds.

Occurred to me in testing, not sure if it'll happen during live merging.

New players will not have this issue.

**Comment by EvenInDeathIStillServe** [comment]
Can you add a cycle hotkey? :pleading_face: ?

**Comment by Just-Sim** [comment]
> Can you add a cycle hotkey? 🥺 ?

what button

**Comment by EvenInDeathIStillServe** [comment]
> > Can you add a cycle hotkey? 🥺 ?
> 
> which button

Uhhh. N?

**Comment by EaglePhntm** [comment]
I yoinked your two keybind PRs for dreamkeep, hope you don't mind.

**Pull request merged**
