### PR TITLE
training pack

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

uh

- antags can choose names for longer (we've had 3 ahelps about this in the last week)
- more importantly - training has been reverted so now you can't gain levels from LITERALLY EVERYTHING

## Why It's Good For The Game

YEAH.

### CODE REVIEW

**Comment by Onutsio** [comment]
Thank god. The training change basically ripped off one of the knobs we could use for adjusting roles. Since anyone could reach expert

**Comment by kittysmooch** [comment]
does this leave any way to get weapon skills past novice?

**Comment by Lutowski** [comment]
needing players to train you is unreliable, but willing to try this & potentially look into buffing antag-adjacent classes that could get locked out of this

**Comment by UncleBourbon** [comment]
This reeks, how is a novice supposed to train with an journeyman level if they cant even parry to earn the xp. The novice attacking into the expert doesn't seem to gain any xp so its just afk sitting there smacking the novice's chest and waiting for them to rng parry.
as of writing this i couldnt even get a novice to journeyman after both them smacking into me and me smacking into them, expert in sword fighting btw

**Comment by bearrrrrrrr** [comment]
> This reeks, how is a novice supposed to train with an journeyman level if they cant even parry to earn the xp. The novice attacking into the expert doesn't seem to gain any xp so its just afk sitting there smacking the novice's chest and waiting for them to rng parry. as of writing this i couldnt even get a novice to journeyman after both them smacking into me and me smacking into them, expert in sword fighting btw

they got up to apprentice from what i was told, which is what is intended

whether or not u want that to be changed is a separate issue

**Comment by bearrrrrrrr** [comment]
uh oh
**uh oh**

# uh oh

**Pull request merged**
