### PR TITLE
Something In The Air Tonight: Werewolf howl adjustments and Dendor T4 spell

### PR DESCRIPTION
**Pull request by Ephemeralis**
## About The Pull Request

Spitballing in general chat on Discord revealed the funny idea of giving Dendor access to the werewolf howl via their missing T4 spell. So, I've gone ahead and done the following:

- The werewolf howl SFX is now **half** the volume that it was. That shit was loud as hell because it spawns directly on the turf underneath you, and it was also 100 volume before.
- Anyone with the Beast language can now understand werewolf howls.
- The Polyglot special no longer awards the Beast language.
- Dendor devotionists/druids get access to a modified version of the werewolf howl spell titled as Call of the Moon as their T4 spell.
   - It is only usable at night.
   - The first time you use it, you'll gain understanding of the Beast language if you don't already have it.

This also has the neat side effect of reducing metaknowledge of werewolf presence by making it plausible to think that druids or other Dendor clerics might be responsible for the midnight howling.

It also essentially grants Dendor t4 users a 1-per-minute global comms (only at night) to use for whatever they want.

This is probably just a stopgap for now until we think of a real t4 for Dendor, but it was easy to make so I figured why not try it out?

## Why It's Good For The Game

Antagonist-follower collusion *rules*. Dendor already kind of has a bit of this going on with the werewolves already, but making Dendor's T4 basically a form of global communications with them opens the opportunities right up for deranged wildpeople to help or hurt those dealing with one of Dendor's greatest blessings.

### CODE REVIEW

**Comment by Joel-682** [comment]
This looks "fine", don't know how I feel about dendorites being able to listen into """antag comms""" and being able to fight them that way. 

Also mildly unrelated: Am I the only one that feels like the verevolf howl has a big ass cooldown? When I played it it felt eternal, tell me if it's a skill issue or if it should get checked at.

**Comment by Ephemeralis** [comment]
It should only be 1 minute or so but spells can get chunky as shit during heavy ti-di, and a *lot* of werewolf rounds are causing tidi lately. It's probably that.

**Comment by bearrrrrrrr** [comment]
> Anyone with the Beast language can now understand werewolf howls.

is it okay if this gets changed? it kind of directly smacks face-first into the gameplay loop we have of letting ww's breathe at the start.

**Comment by Ephemeralis** [comment]
> > Anyone with the Beast language can now understand werewolf howls.
> 
> is it okay if this gets changed? it kind of directly smacks face-first into the gameplay loop we have of letting ww's breathe at the start.

The only way I can see of getting the Beast language to begin with is either via this spell or the polyglot special. Is it that much of a concern? I could potentially remove it from polyglot.

**Comment by Ephemeralis** [comment]
I've added the following message on first cast:

**So it is murmured in the Earth and Air: the Call of the Moon is sacred, and to share knowledge gleaned from it with those not of Him is a SIN.**

**Ware thee well, child of Dendor.**

It should hopefully highlight that the comms are 'sacred' and not a vessel to be trivially shared with the non-faithful.

**Comment by Cleric2145** [comment]
> > Anyone with the Beast language can now understand werewolf howls.
> 
> is it okay if this gets changed? it kind of directly smacks face-first into the gameplay loop we have of letting ww's breathe at the start and i am big concerned ppl will use it to night 1 announce wolves
> 
> as for the T4 thing...most druids are already fairly WW-aligned anyhow, so no change there. maybe make WW's able to recognize dendorites, and have a special inspect like patron stuff for ww's for dendorites...? honestly ill look into that myself if u dont wanna

Tbh people already do this when they hear the WW howl. This will frankly make that an invalid assumption, since it might just be those nutty Druids "Awooo"ing at each other's bare asses (ie howling at the 'moon')

**Comment by bearrrrrrrr** [comment]
> I could potentially remove it from polyglot.

that'd be very appreciated, yeah. tysm ❤️ 

> Tbh people already do this when they hear the WW howl. This will frankly make that an invalid assumption

this is me asking that ppl who roll the polyglot special don't get to hear da werewuffs

**Comment by Ephemeralis** [comment]
All done: polyglot no longer gives the beast language, and I've updated the blurb to make sure people know this.

**Comment by Onutsio** [comment]
I lov antag/towner connections

**Comment by Lutowski** [comment]
peak peak peak peak peak peak peak peak peak peak

**Pull request merged**
