### PR TITLE
Revert "Revert "De-Chuddifies skin color selection""

### PR DESCRIPTION
**Pull request by Mannybrado**
Since we no longer have "I am from skin color 4 land" we can have this

Also changes the character customization menu to say skin tone instead of ancestry/clan/whatever

### CODE REVIEW

**Comment by EvenInDeathIStillServe** [comment]
No Bitch!!! It's LAME!!

There is nothing wrong with the ancestry names. If you have an issue with "Ebon" then that says more about you than it does about blackstone devs.

**Comment by Mannybrado** [comment]
It doesn't have anything to do with the names, its more that every single person that is tanned or black is from these locations. You can say "Just Ignore It" which is fine, but if everyone completely fucking ignores it anyways then it serves no purpose to be in the game at all, it just confuses players about our lore.

**Comment by Mannybrado** [comment]
Considering ancestry isn't even shown anymore, there's no point in even having it be set up this way to begin with. The only thing it does is show people that black people come from "EBON" and tanned people come from palestinereferenceland. This poopooshit shouldn't be in the game, sorry guy.

**Comment by n3tis** [comment]
nice pfp manny brado

no

**Comment by Mannybrado** [comment]
thanks its manny pardo but in ncr armor because i used to play fallout13 in 2020

i dont anymore

**Comment by ChungusGamer666** [comment]
> It doesn't have anything to do with the names, its more that every single person that is tanned or black is from these locations. You can say "Just Ignore It" which is fine, but if everyone completely fucking ignores it anyways then it serves no purpose to be in the game at all, it just confuses players about our lore.

reasonable

but saying that everyone with x color came from y region of the world was funny and soulful and i don't know why you'd remove it anyways

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Yeah nah... even if it doesn't show, I'll keep those names in just because some people like to have some guidelines for their characters, so giving them a general idea for origins is a good idea in my book.

Besides, you (still) forgot the Tieflings and Assimar lmfao. Anyhow, closing it now.

**Pull request closed without merging**
