### PR TITLE
Polearms (and greatswords) Now Backable With Delay

### PR DESCRIPTION
**Pull request by AtoriBirb**
## About The Pull Request

Ever be holding your favorite spear or halberd and someone asks you to hold their log? You think to yourself, how am I ever going to hold my mate's log? Well now with new and improved back slots, you can hold your buddy's log anytime, anywhere.

Allows all polearm weapons (other than the wooden staff since it already does this) to be put in the back slot after a 5 second delay.
Also allows the Zweihander and Greatsword the same because they're in polearm.dm for some reason, don't ask why.

## Why It's Good For The Game

When you're out of combat and you are just around town, it's really annoying to have to do any two-hand actions while holding your polearm. You'd have to drop it, do what you need to do, then pick it back up, a little wonky and I dunno about you but I'm just waiting for the day someone drive-by swooces my spear from under me.

This shouldn't have any combat advantages because it's such a long draw time you'd be leaving yourself wide open. Just QOL for the most part.

### CODE REVIEW

**Comment by Samarai** [comment]
I think the inconvenience of polearms/greatswords is very much an intentional bit of balancing, even if it primarily applies to being out of combat, and removing it makes these weapons more like every other weapon, not a fan.

**Comment by Onutsio** [comment]
Polearms arent especially great, theyre insanely FeelsBadsy because of losing an arm to carry one. Anything to encourage more weapon variety is great. I'll believe balance arguments against this when grand maces arent slottable.

**Comment by AtoriBirb** [comment]
> I think the inconvenience of polearms/greatswords is very much an intentional bit of balancing, even if it primarily applies to being out of combat, and removing it makes these weapons more like every other weapon, not a fan.

It was for balance, and this shouldn't upset that still. If the argument against is because of homogenization, It would leave me confused because they will be the only weapons with a delayed holstering and drawing. That still sets them apart.

And if you take a look at the handy roster I have made of all weapons in AP here https://docs.google.com/spreadsheets/d/1L3OJcgmhptumRyecWODg-aVqU7CWPKI_JLWcV8sYTzQ/edit?usp=sharing A simple longsword does just as much damage two handed as most all polearms two handed, more if one handed, and it can put put on the HIP or BACK without delay. This also makes taking a shield less likely as well, which I think is a good bit of tradeoff for being able to simply holster it.

**Comment by kittysmooch** [comment]
a lot of these will need some onmob transforms set

**Comment by AtoriBirb** [comment]
> Polearms arent especially great, theyre insanely FeelsBadsy because of losing an arm to carry one. Anything to encourage more weapon variety is great. I'll believe balance arguments against this when grand maces arent slottable.

If I did my homework correctly you should be able to slot a grand mace.. the master parent for mace is HIP/BACK unless I read it wrong.

**Comment by AtoriBirb** [comment]
> a lot of these will need some onmob transforms set

I think only the spear is missing that but I'll take a look

**Comment by Ollanius** [comment]
I think only certain greatswords should be sheathable on the back - the zweihander that Grenzelhoftian Mercenaries spawn with, specifically - and that polearms should remain unsheathable.

**Comment by AtoriBirb** [comment]
> I think only certain greatswords should be sheathable on the back - the zweihander that Grenzelhoftian Mercenaries spawn with, specifically - and that polearms should remain unsheathable.

Considering the Zwei also has reach attacks and similar damage profile to most polearms, even residing in the polearm dm, I cannot see why you would think this one is okay to sheath but not others that are so closely related. I need a little more info on this feedback here.

**Comment by faaaay** [comment]
In my experience, I hardly see people using polearms and greatswords, so maybe this will encourage a little more cariety. A five-second draw/stow time is plenty of inconvenience if you have to pull it out in a fight.

**Comment by lalaria1** [comment]
I'm concerned that polearms are just too strong and we're removing any drawbacks or inconveniences they had. Don't they even remove the penalty for moving in mud?

**Comment by Ollanius** [comment]
> > I think only certain greatswords should be sheathable on the back - the zweihander that Grenzelhoftian Mercenaries spawn with, specifically - and that polearms should remain unsheathable.
> 
> Considering the Zwei also has reach attacks and similar damage profile to most polearms, even residing in the polearm dm, I cannot see why you would think Zwei is okay to sheath but not others that are so closely related. I need a little more info on this feedback here.

Balance? Oh, no. The zweihander is the only greatweapon-of-the-bunch that'd actually look good when sheathed on the back. I have fond memories of stylemaxxing with that shit on Stonekeep. It's also the only greatsword _(save for the Estoc?)_ that can be acquired at round-start by certain roles, such as the Grenzelhoftian Mercenary and Heavy Knight. Letting them stow it on their back would be a very nice change.

The polearms, I'd imagine, would look incredibly ugly if stowed on the back. If they end up looking good, however, then I obviously wouldn't mind their inclusion.

**Comment by AtoriBirb** [comment]
> I'm concerned that polearms are just too strong and we're removing any drawbacks or inconveniences they had. Don't they even remove the penalty for moving in mud? I think they also have the highest defense value in the game.

I am BEGGING you to take a look at the data sheet that I have made earlier in this post. If you're going to give feedback I need people to do their part in research to actually back up what they're saying. There are plenty of one handed swords that can match the defense of polearms. The larger swords when 2 handed are only behind by one point of defense. Yes polearms allow you to walk better in mud but you need to have in in your hand anyway, which you 9/10 times will if you are walking about outside of town just because of how oppressive a 5 second draw time is if you get jumped.

**Comment by AtoriBirb** [comment]
> The polearms, I'd imagine, would look incredibly ugly if stowed on the back. If they end up looking good, however, then I obviously wouldn't mind their inclusion.

I made them in my test environment and they looked fine to me, a little shrunk but that happens to all the weapons. Luckily there was already a polearm-back sprite shift for the wooden staff so I just needed to copy that one's positionings for it to look okay when sheathed.

**Comment by lalaria1** [comment]
> > I'm concerned that polearms are just too strong and we're removing any drawbacks or inconveniences they had. Don't they even remove the penalty for moving in mud? I think they also have the highest defense value in the game.
> 
> I am BEGGING you to take a look at the data sheet that I have made earlier in this post. If you're going to give feedback I need people to do their part in research to actually back up what they're saying. There are plenty of one handed swords that can match the defense of polearms. The larger swords when 2 handed are only behind by one point of defense. Yes polearms allow you to walk better in mud but you need to have it in your hand anyway, which you 9/10 times will if you are walking about outside of town just because of how oppressive a 5 second draw time is if you get jumped.
> 
> Think of it as if you were to be walking around with your armor in hand, and every time you wanted to get into a fight you had to put that heavy armor on. Now take that time and DOUBLE IT, because putting armor on is a 2.5 second delay.

The mud walking benefit is -huge-. I did look and greatly appreciate your form, but the fact is polearms are the weapons with best defense stat, most durability (lucerne and eagle's beak have 3x the durability than a steel mace or a steel sword), and they give you that walking speed buff for mud.. I think they're far too powerful to also give them the ability to carry them on your back.

**Comment by AtoriBirb** [comment]
Your arguements that polearms are overpowered are kind of outside the scope of this PR, but I would still ask how many people do you actually see running around with spears/polearms on the regular? I think other than myself, I've seen like.. one royal guard with one. Regardless, I will try to clarify things that are within the bounds of this PR.

Here are some situations to help you visualize what this change will do to the every-day average Johan of Riverwood.

**Scenario 1: You are in town.**
Johan has a polearm weapon that he must keep in his hand at all times, for he is a guard, and a guard without his weapon is no guard at all. Johan wishes to retrieve some coins from his coin pouch to pay for a bit of food, for he is getting hungry. He pulls out his coin pouch, for his hips were both full of his lamptern and his key ring, and realizes... 'by the ten, my hands are full!' He then dumps his spear on the floor, cold and alone, just so he can interact with his coin pouch to pull coin to pay for his meal. At the last second though, Johan decides not to. He would rather go hungry then put his buddy spear on the floor where someone may swipe him, so he walks off, starving. Unfortunately for our friend Johan, as he gets hungrier, his grip on anything he is holding wanes, and he starts to drop his best friend, his spear, to the ground, for he is too hungry to hold them and cannot stow his spear in a safer way. 
**What my PR would change here**: In a more serious note, this would allow the spearman to stow his weapon while he is in town to do many interactions that would require two hands, without having to drop the spear to do so-- which is a bit uncharacteristic for rp but we can't just lean the spear against a wall. The 5 second delay would not affect him in a call-to-arms, since he would have time to prepare. This does not provide a mechanical buff for him to be able to have a polearm on his back, in fact, it is a nerf, because taking up the back slot means there is no room to take a shield or another weapon there.
 
 **Scenario 2: You are out in the wilderness of Azure Peak.**
 I'm not going to silly this one, I'll keep it short and simple. NO ONE, and I mean no one, will walk out into the bog with a polearm on their back if that is their main weapon of choice. **A 5 second delay** here means that in the event of being jumped by skeletons or goblins, you will need to flee. You do not have time to sit there and channel 5 seconds to get your weapon off you without taking a few hits first.
 **For the arguement of the walking stick** since that seems to be your center point, you need to have a polearm in one hand. In combat what that means is **unless you are fighting with a polearm in one hand** you will not be gaining benefits from the walking stick trait. So why not fight one handed with polearms, and maybe put on a shield? You would be insane, honestly. **Most polearms do about as much damage as a dagger when one handed**, and lose many of their better attacks. ALSO, as an added bonus, if you are carrying a shield, that ALSO would take up your back slot (buckler excluded) making the situation non-applicable to this PR.
 
 I really need you to ask yourself what this change does that would actually buff them. It's quality of life, but I'll continue here.
 
 **Scenario 3: You are up against another player.**
 In the event that you are caught off guard by a bandit or whatever, I would assume that most people would try to RP with you first. If this in the bog, you already have your spear drawn as we've explained above. If we're in town or somewhere safe, here is where it may become an issue. If someone decides to take a mechanical advantage, in this case drawing their weapon while someone is RP posting at them, I would almost say that is grounds for foul play. If a guard is caught with his spear stowed, it is almost as if they need to RP fumblings trying to draw the massive thing to respond-- and if it does go through and combat starts between two players, the guard is more than likely going to flee because they cannot reasonably draw their weapon with a 5 second cooldown before eating a stab, or a fireball, or what have you.
 
 **This PR would be more of a self-nerf if someone decides to use it, and that is what I want to convince you of.**
 The only thing to gain is the ability to use both hands without dropping your spear. Stowing it does not offer you any benefits in a combative scenario, and I implore you to find me one.
 
 If you believe that the spears are overpowered, then **that is a discussion for another PR,** because this will not make them any stronger or weaker, just gives a bit more viability for those who may have turned their backs on the weapon type simply because it is so cumbersome to carry. **I do agree** that some of the polearms have some wack-ass durability caps, but how often do you find durability to be an issue let's be real here. I would not hate if they got changed to be default rogue-weapon durability. On defensiveness, You can easily surpass a spear's defensiveness with a shield, which is the point of shields, but notoriously spears are defensive weapons, and quite honestly the best weapon in all history. It's like bows, people call you a coward for using them because you can win a fight without letting your enemy get close. https://www.youtube.com/watch?v=uLLv8E2pWdk I like this short-and-sweet video that shows why spears are basically the best stand-alone weapon, but also why they are pretty shit one handed, like in our current balance.
 
 Also if you want a walking stick buff just take a wooden staff to use in the bog, which is already back-stowable.

**Comment by bearrrrrrrr** [comment]
cool concept but big negatory; it is like this for a reason. polearms and greatswords are **SIGNIFICANTLY stronger** than other weapons, and it also makes literally 0 sense to be able to backstow them in-character. parade rest them in hand like their 1hand sprites, yes. full on sling them across back? absolutely not

big homogenization, -1

**Comment by AtoriBirb** [comment]
> cool concept but big negatory; it is like this for a reason. polearms and greatswords are **SIGNIFICANTLY stronger** than other weapons, and it also makes literally 0 sense to be able to backstow them in-character. parade rest them in hand like their 1hand sprites, yes. full on sling them across back? absolutely not
> 
> the equip/unequip delay also means literally nothing when on our server ppl will generally not ever attack folk without their weapons out
> 
> big homogenization, -1

The 'significant' strength they have is their one tile reach, but that's if you want to minimize and outright forget every other benefit other weapons have. The arguement for homogenization is very weak, because you are telling me that a polearm's identifying feature is the fact that it's cumbersome and that if it lost that (it wouldn't, because again, they would still be cumbersome to have to deal with a 5 second draw time.)

I'm not fluent in the intricacies of pvp on this server, because for as long as I've been on it I have never actually had to fight another player, and I've played warden, templar, and adventurer being out and about. That would be a questions for the rp etiquette team on conflicts.

You can tell me 'absolutely not' but you need to give me a better reason here then that it'd make no sense in character.
image

**Comment by bearrrrrrrr** [comment]
these are the huge, gigantic polearms that were bigger than folk, and u do not have a special strap or sling.

i'm literally telling you why, dude. either re-read everything i said, or don't. idc.

**Comment by AtoriBirb** [comment]
> these are the huge, gigantic polearms that were bigger than folk, and u do not have a special strap or sling.
> 
> i'm literally telling you why, dude. either re-read everything i said, or don't. idc. they're incredibly powerful and this is one of the ways they're balanced out; inventory management

I need you to tell me why you think they are powerful. I need an explanation. Also you don't have a strap for any weapon you'd put on your back and yet you still can in this game, maybe you could create a PR that has such straps.

Here are some pictures to help you imagine the size of relevant weapons:
image
image
Yes polearms are longer, that's the point, but you don't stow such one to one. You either hike it up so it's poking higher than your head, or you do so at a diagonal, either way, it is possible. Lances, not so much, but we don't even have a lance in game.

I have read over what you have said multiple times because it still leaves me confused as to your argument.

**Comment by bearrrrrrrr** [comment]
?? they're powerful b/c high defense, high damage, range. i stated this, not sure why you're confused??? and i'm not sure why this is controversial.

reach itself is already hilariously overpowered. being able to hit someone that can't hit you back is the definition of a winning engagement.

**Comment by SciDragon** [comment]
At the very least a spear should be able to be worn on the back. It's not that much longer than a wooden staff/quarterstaff and the longsword, both of which can already be stowed there. Honestly I kinda hate the balance obsession here on an HRP server. Test merge stuff like this and see how it works before shutting it down out of some sort of paranoia about PvP balance.

**Comment by AtoriBirb** [comment]
> i already have to go through all of the random fucking powercreep rtcoders have to put in, pls don't give me more work down the line of literally everybody picking up a greatsword (this PR now gives you literally no reason to use anything but a GS since u don't really pvp without ur weapons ready)

If people expect combat, they will have the weapon unholstered and at the ready.. yes, I agree. So how does this change that? If greatswords and polearms are so op, why are people not already doing this? I don't understand. How does relinquishing a slot on your character turn to something overpowering all of pvp? People would use them more for being less clunky, yes.. but if they're so broken overpowered, metagang will use them regardless. A sword/shield combo will still provide you more defense, and thus still probably win over a greatsword, but again that is more of a overall balance that lies outside of this PR.

I need objective reasons here for a change I am basically making for RP reasons on a HRP server. Every refute has been because of fear of pvp, and people make it sound like I'm adding 40 damage to the spears' base value. They're strong, I don't argue with that, but it feels like this has become a vent post for people who've been wronged by a polearm or greatsword before. Their downside will stay the same. They are clumsy, slow, have charges for their attacks, and are only good when used in both hands. A 5 second delay would make it still unreasonable to have it stowed in any situation you expect to be in combat. Hell, I could make it 20 seconds. It just does not feel good to have to drop a spear to literally do anything if you are just rping around the town.

**Comment by AtoriBirb** [comment]
> The real life argument is moot because in reality you can do more then one single thing with your hand. This is a very binary video game, so simply having a way to not basically lose a hand for the entirety of your round, or play around with dropping your weapon on the floor every five minutes, is a huge quality of life improvement.
> 
> Is it incredibly, overwhelmingly powerful?
> 
> no they're mandatory two handed weapons with a +5 attack to (optionally) two handing their contemporaries. There is no option of a shield, starting a fight with a ranged option is more or less out as you need two hands for it. Their defensive ability is even. Their main benefit is reach - noteable, but not as bombastic as a big deal over SS13 - and a whole five more damage at the cost of a severe lack of flexibility.
> 
> it's fine bear. A mace and shield is still the better pick. Or anything and a shield, really.

Reach is kinda hard to maintain just cause of the lag but I try not to use that as an argument here 😭. Thanks though, I appreciate the support.

**Comment by AtoriBirb** [comment]
> > it's fine bear. A mace and shield is still the better pick. Or anything and a shield, really.
> 
> not really
> 
> this also overtly punishes sword+shield users by now making them have the hardest time storing stuff out of any build in the entire game sans archers. very much not good
> 
> fine with this being merged but don't go shocked pikachu face when everyone is running around with greatswords

If they do I'll personally take another pass to put them more in line. Was never the intent to give you more headaches, I promise.

**Pull request closed without merging**
