### PR TITLE
Please Play Soilson: Farm Remapping

### PR DESCRIPTION
**Pull request by Lutowski**
## About The Pull Request
Peak Christ has descended and whispered his catholic epiphanies unto mineself: “please make the farm pretty so more soilers play” and by his will I spent over eight hours to do so.

* The farm is completely remapped, while keeping some recognizable buildings intact. The field has shrunk remarkably to make room for a chicken coop. Front doors replaced with dunjon ones for viewport larp, but has the same integrity set to regular doors. Upstairs added to bunkhouse.
* Bunkhouse moved to main hut upstairs. Balcony added. The old bunkhouse was absorbed by the communal feast area. Adds a small soup kitchen.
* Seperated livestock in barn since goats would randomly kill cows. Might move them to their own pen in a future PR.
* A more defined ‘town square’ is placed next to the inn and steward, with fair banners and a fountain.
* The inn has been moved two tiles to the east, with two commissaries in front of it obliterated and replaced with market booths, so some small changes were made in the sewer Z level to accommodate that without compromising too much of the original structure. Results in a more sizeable garden for the innkeep to do whatever in.
* Canopies are equipped with service hatches that’s deadbolted on the inside, and have tables that can be destroyed in case a walk-in stall is more desired. 
* Sign added next to stalls to inquire the merchant for stall keys, handy for new players.
* Guard keyrings added back to Azure Forest.
* Tavern kitchen door facing the well starts out locked.

Ontop of the remapping I've also:
* Added hay, sand, and pond tile. Sand is in its own DMI file.
* Edited hay and sand in paint.net to be more desaturated. 
* Fixes some tiles and decals not showing up in StrongDMM at all. Merged their DMI.
* Can craft hay with two chaff under Crafting.
* Combined Zydras' PR here: https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/385

<details>
  <summary>StrongDMM screenshots</summary>
  
image
image
</details>

<details>
  <summary>Ingame screenshots</summary>

image
image
image
image
image
image
</details>

## Why It's Good For The Game
The inn suffers a lack of visibility. It’s tucked in west part of town, and doesn't make itself known to the average passerby due to the chunky commissaries in front of it. Now, not only are the two commissaries renovated, but also placed next to the inn to form a funneling, U-shaped entry to invite and consolidate more roleplay potential in one place. We’ve also lacked a designated town square, so I’ve assigned one next to the inn, steward, blacksmith and the execution podium to centralize roleplay even further.

The previous farm had a lot of wasted space, so it's remapped to be lush and more roleplay friendly with a bigger communal/event hall that can be used for just about anything. Soilers never use more than half of the field, so it’s been shrunk to look more ‘full’ when worked on, and accommodate other expansions.

### CODE REVIEW

**Comment by Kavrick** [comment]
This is good mapping, the doubled-up kitchen is a bit weird, they only really need one.

**Comment by Lutowski** [comment]
> This is good mapping, the doubled-up kitchen is a bit weird, they only really need one.

truth be told I wasn't sure what else to put there. there can be up 5 soilers playing at a time and that's not accounting for the 2 something druids that come by, so having an auxilliary kitchen of a sorts can come in handy for an extremely populated farm

**Comment by MaSvedish** [comment]
Oh yeah. Its all coming together. [Number One Luto PR Supporter]

**Comment by bearrrrrrrr** [comment]
yo this kinda cooks ......

my only real comment is that yeah it may be worth double-dooring the inn or farm now :3

**Comment by Lutowski** [comment]
image

Farmhouse has been adjusted to be full of whimsy. Added SCOM outside of dunjoon door to contact farmers inside.
Inn doubledoored, small adjustments there too.

I've also:
* Adds hay, sand, and pond tile. Sand is in its own DMI file.
* Edited hay and sand in paint.net to be more desaturated. 
* Fixes some tiles and decals not showing up in StrongDMM at all. Merged their DMI.
* Can craft hay with two chaff under Crafting.

Planning to PR tileswapping with friendly mobs so bodyblocking isn't as much of a foreboding issue.

**Pull request merged**
