### PR TITLE
Goodbye Specials: Virtues for more character customization

### PR DESCRIPTION
**Pull request by Ephemeralis**
## About The Pull Request

Specials are dead. Long live specials. I mean it. Special is **gone**.

In their place are **Virtues**, weaker but significantly more broad traits that allow you to add special tweaks to your character's build **at the cost of any beneficial stats.** You are basically trading the positives (and negatives) of a statpack for the quirk that a virtue gives instead.

You gain the option to take a Virtue by picking the new **Virtuous** statpack. If you pick any Virtue, this statpack is applied automatically, replacing your old choice. Virtuous has +0 to all stats, meaning that you gain no bonuses or penalties.

**You CANNOT pick a stat-awarding statpack and a Virtue at the same time. You MUST pick Virtuous to gain access to Virtues.**

Before reading below, make sure you've read that paragraph once or twice. Really let it sink in that **you are trading raw mechanical stats to access these**. Many of them are weakened versions of the special traits you know and love already.

Here's a list of the ones currently available:

- Arcyne Potential - +1 arcane skill, start with prestidigitation (no extra spell point, so it's basically just prestidigitation)
- Acrobatic - leap slightly further (leaper) and break your falls (1 z level of fall damage immunity)
- Devotee - +1 holy magic skill, start with orison and absolutely gutted devotion (80 max, no t0 or any chance of progressing to t1+ basically JUST orison)
- Duelist Apprentice - +1 sword skill (max 4), start with stashed rapier 
- Toxophilite - +1 bows skill (max 4), start with stashed recurve bow and arrows
- Rich - start with a rich mammon pouch in your hands
- Rotcured - start with all the bonus traits (+weaknesses and rotting skin coloration) of someone who succumbed to the deadite rot but was revived
- Arsonist - start with 2 firebombs stashed
- Giant - start with a 25% larger sprite, +2 STR, +1 CON, -2 SPD. Deducts 2 triumphs upon spawn (does not check to see if you can afford them, you can go into triumph debt)
- Dust Runner - start with 2 satchels of random drugs and a dagger stashed
- Nobility - noble trait and +15 estate income (if already noble)
- Beautiful - beautiful trait (stress drop when people examine you)
- Deadened - no mood trait (no stress events)
- Light Steps - quiet footsteps trait, +2 sneaking skill (max 5)
- Linguist - select from 1 of elvish, dwarvish, orcish, hellspeak, draconic, celestial at roundstart/join, no effect if you know all languages already (archivist)
- Deathless - No hunger and no breathing traits.
- Crafter's Apprentice - +2 to all crafting skills except cooking
- Feral Appetite - eat rotten/raw food trait
- Night-eyed - gain night vision
- Guarded - deceiving meekness trait
- Impervious - critical resistance trait
- Learned - +3 reading skill (no cap, can take to legendary)

In addition, Flaws have been renamed to Vices, since the game refers to them as vices anyway, and Virtues and Vices sounds rad.

As an associated balancing choice, I've opted to remove the night vision from the Noc follower bonus. It has been replaced in spirit by Night-eyed, allowing characters who aren't Noc-affiliated to gain workable night vision. In its place, Noc followers now gain Night Owl, which gives them mood bonuses at night.

I have taken efforts to make Virtues very accessible to add for even novice coders - a simple virtue subtype placed in any modular file will appear in character creation, so please get creative and put your prospective ones up for review. There's plenty of examples to work from as well.

Please balancejak any especially problematic virtues in here responsibly, especially if they're not traits you can otherwise receive normally. There's already been a few removed after a quick pass in dev-general earlier today.

## Why It's Good For The Game

Some of you are going to violently shit your pants at this, but I think it is ultimately for the better. Virtues open up a lot of character customization options, especially for people/roles who are less concerned with raw mechanical power. 

Many virtues are just basically things to get your build online quicker and with less grinding. If you want to roleplay someone rich, pick rich and have a bunch of mammon to throw around at roundstart. Play a wandering tribal archer but can't find a job you like that gives you a hunting bow? Pick toxophilite. Playing a head-turning noblewoman? Pick beautiful. Playing a naked wild-kin dendorite? Pick Feral Appetite and eat things raw all the time.

More choices, more character concepts, more good stuff.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
nah, giving up a stat-pack for these is a super elegant solution, huge fan
burger is right however, definitely an add-up-to check for combat skills LOL, not a huge deal for non-combat

**Comment by Just-Sim** [comment]
this is based and gives way for neutral quirks that can be made for roleplay purposes

**Comment by Kroto-Ker** [comment]
Hey what if Giant could make you like, slightly stronger and slightly slower. Like replace your statpack with a 'giant' statpack. Since right now it's kinda just all negatives, lose out on stats for a larger clickbox.

**Comment by Ollanius** [comment]
> **edit:** some of these are a bit too strongk, like deadened/deathless, but that's extremely minor stuff that can be figured out after it's added and absolutely not even a concern on my mind atm, im a huge fan of this overall

Adding a TRIUMPH cost to stronger VIRTUES would be a nice way to balance it out.
This proposal could also be used to better reintegrate certain VIRTUES _(such as the previously-unnerfed 'Giant' trait - and maybe other round-altering choices like 'Outlaw' and 'Heretic')_ into the loop, without causing too many problems.

**Comment by DiscordWizard** [comment]
Cool idea, I do love more flavor and customisation. Though I don't really like that some of these are just a simple cosmetic change that then opts you out of stats. Anything that's simply modifying your looks shouldn't be gated behind losing on the customisation power of a statpack, both for flavor and balancing reasons, an example of this being the trait that makes your sprite bigger. It's just cosmetic, and it feels downright evil to force people who want to play taller characters to have less stats.

**Comment by bearrrrrrrr** [comment]
half giant having +2 str would be fine

but again, i want to emphasize that _**all of this can be handled after it's merged**_ and i rly don't think it's a huge idea

**Comment by Ephemeralis** [comment]
Virtues now support stat additions and triumph costs as well.

Giant has been updated to give +2 STR, +1 CON and -2 SPD and costs 2 triumphs. It doesn't check if you have the triumphs available, it just deducts them, so you'll always be able to play it.

**Comment by Ephemeralis** [comment]
I've added the following virtues:

- Night-eyed - gain night vision
- Guarded - deceiving meekness trait
- Impervious - critical resistance trait

Noc doesn't have night vision anymore either - it is replaced with Night Owl (-3 stress at night for 20 mins). I kind of had to do this since passable night vision was a bit too gamer for a pantheon bonus, and it opens the night vision prospect up to more than characters who just follow Noc.

**Comment by bearrrrrrrr** [comment]
> I've added the following virtues:

mm- acrobatic is definitely a bit much, iirc jumper was gonna be a mage spell but was dismissed as too powerful? unsure if it's worth a statpack thing though, we'll see how this all interacts

+2 str +1 end for -2 spd is definitely way too good (debatably even muscular, which is this but also with -2 int, is too good, this is unfortunately just an objectively better version of it, which is not a huuuge deal, since -2 int means nothing)

but like i said before i'm really not too concerned and will mostly be futzing w/ actual values after and **NEED IT I NEED IT I NEED THIS PR I NEED IT I LOVE THIS PR MERGMGN FMAHNOEGFJUGBHGJHG** 

begins frothing at the mouth

**Comment by Cleric2145** [comment]
I, too, support RP/cosmetic virtues compatible with Stat packs. Linguist, beautiful, future insignificant virtues, etc.

**Comment by Ephemeralis** [comment]
> mm- acrobatic is definitely a bit much, iirc jumper was gonna be a mage spell but was dismissed as too powerful? unsure if it's worth a statpack thing though, we'll see how this all interacts. just initial thought, not a request for anything

Is the combination of the two the thing that is making acrobatic overbearing? Should it just be one or the other?

**Comment by HeroWithYay** [comment]
Why should Giant deduct two triumphs considering its basically just a statpack?

**Comment by Ephemeralis** [comment]
> Why should Giant deduct two triumphs considering its basically just a statpack with the additional downside of a big hitbox?

Precisely because it's a statpack. Virtues are by design, not meant to be statpack replacements. People felt that Giant with just a cosmetic bonus was too much to pay for losing stats, so now they get the option of having a fixed statblock in exchange for a fairly minimal requirement (2 triumphs is 2 sleep cycles which you can get in the first 20 mins of the round or whatever).

**Comment by faaaay** [comment]
Could I suggest a virtue that grants ranks in Reading? A good number of roles lack literacy, and this would enable some character concepts in those roles.

**Comment by Ephemeralis** [comment]
I've added the Rotcured virtue, which essentially gives you all the traits (including skin coloration) of someone who succumbed to the deadite rot and was healed/revived by the Church.

**Comment by CandleJaxx** [comment]
this is super fun and i'm enjoying it immensely. the acrobatic skill does seem op as i've been able to consistently sneak into the keep by doing superjumps

**Comment by AtoriBirb** [comment]
There's clearly going to be some issues surrounding Arcyne Potential and I'm surprised no one has said so yet. I made a PR trying to add a medium armor-magic user and it drew a lot of backlash.

Just to give you an idea of what this can do:
image
image
I started this round an hour late and was able to give a cleric fireball and invisibility with it. MASTER level arcane magic.

A cleric, which gets the same casting power as the priest.
Meanwhile Devotee gives.. Orison? I think either the Arcyne Potential needs to be limited to be more in line with arcyne-monk (-6 skill points and a few pre-selected spells) or that Devotee needs to at least be brought up to the churchling or paladin/hymnist category. I think Devotee would even be great if it could bump up those a level too, like giving a paladin their next tiered spell or something. Either way, totally not equal here.

**Comment by Ephemeralis** [comment]
-6 seems like the gameplan there, yeah.

**Comment by AtoriBirb** [comment]
> -6 seems like the gameplan there, yeah.

I think it does need to be taken into account that a lot of people did enjoy it, even if it is a little broken. If being able to use the books could be turned off then I feel like giving them like.. one spell wouldn't be too killer. But similarly, I would still push for allowing for at least a tier in the miracle stuff.

I am not sure anyone would realistically want to sacrifice their stat spread for being able to fill a cup with water or shine a light. Maybe I'm wrong idk.

**Comment by Ephemeralis** [comment]
I've given Noc sight back to Noc followers for the time being.

**Comment by Ephemeralis** [comment]
Arcyne Potential now gives -6 spellpoints and prestidigitation ONLY if you're not normally an arcyne class. This should negate practically all of the spells you can get from gamering yourself to legendary arcane in a round. If you are an arcyne class without any extra defensive traits (any armor prof and dodge expert), you gain 1 extra spellpoint to play around with.

Devotee has more or less been completely reworked.
- If you aren't a Devotionist, Devotee now grants Lesser Miracle (the heal) in addition to Orison. You still have a cap of FUCKALL devotion, however. Enough for maybe four casts, tops.
- If you are a Devotionist, Devotee now increases your maximum progression tier by 1. If you're playing a role with max T4 progression already, you instead gain 1 passive devotion gain per tick now.

I've also made devotion able to give floating point numbers for passive gains, and have adjusted Cloistered Devout down appropriately.

**Comment by annikaRU** [comment]
I did some minor testing and it would appear several of the virtues are broken, example dueling apprentice, you gain no skill no matter if you have skill or do not, tested as a cleric, it is given sword fighting novice, virtue could not give more skill, pilgrim miner who does not have sword fighting, virtue could not give skill, and this applies with other skill based virtues as well

**Comment by Ephemeralis** [comment]
All addressed pending a new testmerge - thanks for the report though!

**Comment by annikaRU** [comment]
To clarify and correct myself a bit, is it intentional for dueling apprentice to not give skill if you have sword fighting skills

Life Clerics have sword fighting 1 dueling apprentice disallows it to be advanced further if so that is a bit odd could be changed, cannot influence it past sword fighting 3 

Although going through a second test on my pilgrim miner test character, it did the same repeat thing so the fix may of not properly applied or not applied at all

**Comment by Ephemeralis** [comment]
> To clarify and correct myself a bit, is it intentional for dueling apprentice to not give skill if you have sword fighting skills
> 
> Life Clerics have sword fighting 1 dueling apprentice disallows it to be advanced further if so that is a bit odd could be changed, cannot influence it past sword fighting 3
> 
> Although going through a second test on my pilgrim miner test character, it did the same repeat thing so the fix may of not properly applied or not applied at all

The fix hasn't been applied yet - it will be the next round, though.

The intent is that the skill virtues will not improve a weapon skill past 4. If your job starts with 3, it will improve that to 4. If your job starts with 4, it won't improve that to 5.

**Comment by YakumoChen** [comment]
Could the crafting virtue have sewing as well? I took it as maid so I wouldn't have to grind and was disappointed to find it was the one crafting skill it didn't have.

**Comment by bearrrrrrrr** [comment]
skills are for super sure bugged and not applying their +1's, multiple ahelps about this

tgs bot pls

**Comment by Ephemeralis** [comment]
Bunch of changes:

- Fixed zeroed skills not receiving virtue bonuses.
- Night-eyed virtue buffed substantially from 3 tiles fulldark to **12** tiles fulldark, 4 more than Nocvision
- Replaced tanning with sewing for the Crafter's Apprentice virtue
- Virtues can no longer buff a skill past its intended maximum
- Crafter's Apprentice now caps skills at Master instead of Legendary as previously

**Comment by Ephemeralis** [comment]
Added examine messages for beautiful chars, colored based on the bisexual flag (for masc/fem) and based on the non-binary flag for NB chars:

https://puu.sh/KisvX/4b0ac582ef.png (fem)

https://puu.sh/Kisw2/0a2d512366.png (masc)

https://puu.sh/Kisw7/4009e26c6c.png (nb/object)

**Comment by bearrrrrrrr** [comment]
Me when the test merge is updatred

**Comment by Lutowski** [comment]
puts a shotgun to the tm bot

**Pull request merged**
