### PR TITLE
Point blank charges always fail

### PR DESCRIPTION
**Pull request by FreeStylaLT**
## About The Pull Request
By request.

It's a pretty scrappy band-aid, but it works.
dreamseeker_lk7xOtZC38
image

## Why It's Good For The Game
It's undesirable to have a Werewolf be able to cheese point blank charges mid-combat, or for anyone else.

### CODE REVIEW

**Comment by kittysmooch** [comment]
volfs probably need escape tech for when theyre blocked in on all adjacent tiles but ig they can z jump

**Comment by ShudderEve** [comment]
Big +1

There should at least be a 1-tile charge to tip someone over with a charge, saying this as a WW player, it's really cheap to KO people down at any moment.

> volfs probably need escape tech for when theyre blocked in on all adjacent tiles but ig they can z jump

Charging into someone when you're surrounded already keeps you in place for 2-3 seconds, and is not viable. It's already not really an escape tech.

**Comment by radarseas** [comment]
oh thank god someone made this, I was getting tired of royal guards abusing this to instantly kill me as a bandit in combat and swift intent with maces for knockout spam through armor.

as for WWs, yeah this is needed, it gives people in lone-combat _a chance, at least._ Its gonna be rough against crowds still though, but then again, WW's have like infinite stamina as boring as running constantly from the murderball is, its the only option rn.

**Comment by Lutowski** [comment]
crazy kino

**Pull request merged**
