### PR TITLE
Manners Maketh The Man: Nobles have food quality & manner requirements

### PR DESCRIPTION
**Pull request by Ephemeralis**
## About The Pull Request

Since nobles gorging themselves on sticks of butter continues to happen at an alarming rate, I've decided to fix it in code.

Introducing; **manners**.

If you are playing a noble character, they will now have certain expectations about the quality of their food and the manner in which they eat it.
- Eating most plated or non-portable foods without a table will irritate nobles. Travel foods should be fairly obvious.
- Plating platable foods in most cases, increases their fare class and makes them more palatable for nobles.
- Eating "impoverished" food (such as sticks of butter or raw, unprocessed vegetables) will cause most nobles to become violently ill and suffer a rather large stress event, on top of puking on themselves.
- Nobles are able to eat impoverished food if they're *starving* but will incur a desperation debuff that lasts a whole hour and will tank their stress. Note: good way to punish unwieldy nobles.
- Eating anything from a bowl without a spoon will cause nobles to suffer a slight mood debuff.
- Yeomen & Courtiers are also a little picky and will be upset if forced to eat impoverished or poor foods, but won't throw up from them.

## Why It's Good For The Game

Princesses eating an entire frybird on the royal carpet is not kino, neither is the Duke shoving sticks of butter into his mouth 50 minutes into the round. This should hopefully encourage sane behavior, and the categorically uncaring can just ignore it and suffer the stress debuff if they're really committed to the bit.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
[ COMPOSURE - MEDIUM - FAILURE ]

Portrait_endurance

The butter slides past your lips and down your gullet. A wave of shit-sickness passes through you, nausea blanketing your body. The Lieutenant stares at you with disappointed, if not sympathetic eyes, an expression of unspoken 'I-told-you-so' written across his face. One you don't get to see- as you proceed to vomit the entire butter bar out onto the throne in front of His Dukieness.

**-1 MORALE**

**Comment by Cleric2145** [comment]
On one hand: noooo my nobles can't gobble the glizzy on the glarpet whyyyy

On the other hand: Haaah, that'll teach those stupid fucking nobles to eat like its not RP'o'clock

**Comment by bearrrrrrrr** [comment]
> If nobles want to gobble the glizzy, then let them. We don't need to mechanicalize food preference.

mechanically incentivizing rp is not a new or revolutionary or controversial concept

that, and encouraging ppl into cooking/service roles is good

**Comment by YakumoChen** [comment]
Huge maid buff

Please map more spoons in the keep if you're going with the soup thing however.

**Comment by Lutowski** [comment]
> Huge maid buff
> 
> Please map more spoons in the keep if you're going with the soup thing however.

Spoons are relatively easy to make now that servants had their crafting skills buffed.

**Comment by SciDragon** [comment]
Having played 3 minutes of a round with this PR merged I hope that it is seriously not this awful to play with, if you choose the Nobility trait or Knight-errant, you physically cannot eat food that would be expected to be found, say, while adventuring, despite the fact that you might actually be playing an adventurer.

**Comment by HeroWithYay** [comment]
Bugs aside. While this is great for enforcing manners in a courtroom, there's nobility in all corners of the world. And even a princess or courtier can be in a rough situation. Having them /throw up/ for eating a fish that they cooked seems excessive. Especially since not everyone who plays nobility is even playing an ultra picky baby.

**Comment by Ephemeralis** [comment]
> Having played 3 minutes of a round with this PR merged I hope that it is seriously not this awful to play with, if you choose the Nobility trait or Knight-errant, you physically cannot eat food that would be expected to be found, say, while adventuring, despite the fact that you might actually be playing an adventurer.

Jacksberries won't make you puke, neither will coppiettes or basically any tier 1 crafted cooking item. Roast some meat. Stop eating raw vegetables.

**Comment by AdamElTablawy** [comment]
Azure Keep players sobbing and screaming when expected to roleplay for one single second

**Pull request merged**
