### PR TITLE
Arcyne Knight, the Eldritch Knight addition

### PR DESCRIPTION
**Pull request by AtoriBirb**
## About The Pull Request

Adds a 'Eldritch Knight' or 'Red Mage'-esque class choice to Knight Errant, to allow for a hybrid spell-sword choice to match up with Paladin and Cleric.

Arcyne Knight, much like its similar hybrid the Arcanist, gets a lower level of arcyne talent than mages, while still retaining its class's main aesthetic, a knight of nobility. To compensate for their added magical ability, they take the following penalties:
 - Stats are nerfed from a total of 7 stat boosts to 5, with strength and constitution being lowered by 1.
 - Shield proficiency is removed
 - Weapon abilities lowered to apprentice
 - Heavy armor proficiency is removed and replaced with medium armor
 - Starting armor matched to new proficiency

## Why It's Good For The Game

I know it was said that we want more classes for in town, but if someone doesn't want to be in town, they won't be, and having more options won't really change that. Regardless, I felt there was a hole in the choices for adventurer, for both this and another PR. I know magic is hard to balance, so of course, open to discussion on how to balance it further. Sword and tome gaming!

Also I know this is not modular, I have no idea if this would have been better stuck as like a vagabond spec or something, let me know.

### CODE REVIEW

**Comment by ChillyLobster** [comment]
I love giving players options and whatnot!!! I love freedom to be a noble magician!!!

**Comment by Ephemeralis** [comment]
I love the theme of this. I really do. I am however, *mortally* afraid for the combination of high combat proficiency & arcane spells. I'm loathe to balancejack PRs at the best of times, but I think it's sort of critically important here.

This plus Haste and Repulse on demand is practically a guaranteed fight-ender on a very short cooldown. We **have** to limit the martial-arcyne axis on this front. Even something like lightning bolt is supremely problematic when you can no-save knockdown someone and immediately cripple their mobility while also being able to facetank heavy oncoming hits.

If we can spitball a list of the spells that martial-arcyne *shouldn't* have, I'm happy to put up a sibling PR to this to make per-class spell lists a reality.

**Comment by Ruediger4** [comment]
> honestly, I think its time some spells like repulse, fireball, haste and maybe darksight a trait limit to being only learnable by actual, mages so only proper mages/rogue mages/mage apprentices/court mage/vagabond mages can learn them.
> 
> it gives mages their niché without letting magical warriors step on their feet and do everything, better than them.

This is a genuinely good argument tbh. I don't think stuff like warlock-ish spellcasters are THAT bad _(i do think they can be a bit overtuned if they're given medium armor or higher, or even dodge expert)_ but it's true that this seems like people wanna play mage... but without the weaknesses that come with mage. Or the identity.

Everyone wants to have their cake and eat it too but that's just a bit Silly. It's already kinda silly when you see mages going around stacking (light) armor + a polearm so they end up looking like a weird barbarian that can also cast fireballs. This only cements the issue of "people want to play mages but without the downside of playing mages" even more.

This is food for another PR but yeah maybe locking certain spells to mages only and any other silly spellcaster gets a limited selection would be better. I am playing balancejak here.

If we're going for the "well what if someone wants to play a noble magician?", they... can do that. Arguably. Hell, could add something like an alternative class to mage where you have the traditional **"smokes swampweed and dialogues with frogs"** mage that is slightly poor but Really Good At IT and the alternative **"comes from a wealthy family that is influenced by the arcane"** class that could maybe get the noble trait + some SLIGHTLY different stats. Or just. RP as if you're a noble.

**Comment by SciDragon** [comment]
> > honestly, I think its time some spells like repulse, fireball, haste and maybe darksight a trait limit to being only learnable by actual, mages so only proper mages/rogue mages/mage apprentices/court mage/vagabond mages can learn them.
> > it gives mages their niché without letting magical warriors step on their feet and do everything, better than them.
> 
> This is a genuinely good argument tbh. I don't think stuff like warlock-ish spellcasters are THAT bad _(i do think they can be a bit overtuned if they're given medium armor or higher, or even dodge expert)_ but it's true that this seems like people wanna play mage... but without the weaknesses that come with mage. Or the identity.
> 
> Everyone wants to have their cake and eat it too but that's just a bit Silly. It's already kinda silly when you see mages going around stacking (light) armor + a polearm so they end up looking like a weird barbarian that can also cast fireballs. This only cements the issue of "people want to play mages but without the downside of playing mages" even more.
> 
> This is food for another PR but yeah maybe locking certain spells to mages only and any other silly spellcaster gets a limited selection would be better. I am playing balancejak here.
> 
> If we're going for the "well what if someone wants to play a noble magician?", they... can do that. Arguably. Hell, could add something like an alternative class to mage where you have the traditional **"smokes swampweed and dialogues with frogs"** mage that is slightly poor but Really Good At IT and the alternative **"comes from a wealthy family that is influenced by the arcane"** class that could maybe get the noble trait + some SLIGHTLY different stats. Or just. RP as if you're a noble.

It doesn't help that the "weakness" of playing a mage is so egregious. People wear light armor because armor is so critically important on this codebase whether you are fighting simple mobs or other players. One critical hit and you are dead within moments and mages have no other way to avoid that other than wearing armor.

**Comment by radarseas** [comment]
> It doesn't help that the "weakness" of playing a mage is so egregious. People wear light armor because armor is so critically important on this codebase whether you are fighting simple mobs or other players. One critical hit and you are dead within moments and mages have no other way to avoid that other than wearing armor.

Correct, hense why as light armor users, mages should keep their repulsion and more powerful spells than the likes of non-magos to compensate for this.

Anyone else should be sacrificing power for armor tradeoff preferably limited to the likes of fetch, spitfire, message and mostly utility or other light combat spells while mages are the ones that truely channel the arcyane.

**Comment by faaaay** [comment]
I like the idea in theory, but I'm not sure about using Knight-Errant as a baseline (but I'm partially just biased by the desire to play a spellsword who _isn't_ a Noble).

Also: Perhaps, to reduce balance concerns, their base weapon skills could be lower, with their weapon choice granting a skill bonus? Like how it's handled for Warrior

**Comment by AtoriBirb** [comment]
Hello hello I'm awake! Wanted to give a bit more insight into my mind on the changes within on this class.

While I understand having a martial fused magician is probably going to be hard to balance, I wanted to call attention to what is already possible in this field. Anyone can train up to apprentice in any martial or crafting skill, we're all familiar with this, which is why that is what I capped the Arcyne Knight at. A mage could pick up a sword, swing it a few times and be apprentice without much effort.

What this class has that mage cannot gain though, is its armor proficiency trait for medium armor. That is the bread and butter of what I have figured what a Knight-errant is all about, having higher proficiency in armors, and while this isn't heavy armor, it's still quite a bit better than anything the mage could ever hope to get.

The sacrifices, were significantly lower stats than most martial and magic oriented classes. A Court Magician, who also has apprentice in swords, can have an INT of up to +5 starting. Arcyne knight has +1 int resulting in a much lower casting speed. Their strength is only at a +1 as well, giving them the only leg up to being a martial that the mage/court magician or any other caster could not match.

I do agree that mixing hasten and repel on a martial class has the grounds to be quite bonkers frankly, but this class barely constitutes anything more martial than the average joe. 

--------------------------------------------------------------------------------------------------------------------------------------

Now to address where to take this from here. I really appreciate all the feedback!

I think that making the spell list trait bound would probably be a good idea, it would make it easier to be pick-and-choosy for which spells to be available to what classes if at all it is ever felt like one upsets the balance a little too much. I'm not sure if I have the ability to do that being the copy pasta monkey that I am, but I could take a look into it.

There's also polarizing the Arcyne Knight into dropping all martial skill and making them more like a heavy-armor mage, I imagine the mage's guild guards in the Imperial city in Oblivion. Their slower speed and slower casting time would be compensation for their armor proficiency, and it would be to protect them because they probably intend to get into more scuffles and close-range battles. What does that promote? Touch spells, which is fun to think about. Shocking hands anyone? Flame fingers shotgun?

I had a few ideas about spells that would go amazing for a martial-magic class as well. Green flame blade to apply to your weapon with your left hand, then strike to do extra burn and set other mobs around your target on fire. Booming blade, apply to your weapon to shock the target and give them the slowed spell's effect for a bit.. there's a lot of ideas, I suppose it just boils down to who wants to make them.

So, I'm open to take it any direction people feels that would go best. Maybe we could do a test merge and see how people take to it?

**Comment by bearrrrrrrr** [comment]
yeah uhhh a heavily armored caster sounds. NOT GREAT, ngl. you need to either give them a hell of a speed malus and very low str and consider lowering their skills even FURTHER (which is crazy given that they're at a 2) to make this even remotely fun to play against

not really sure how to rectify the issue

test merge may be worth seeing how it interacts but i am worried at this being the mother of all adventurer powercreep ngl

**Comment by AtoriBirb** [comment]
> yeah uhhh a heavily armored caster sounds. NOT GREAT, ngl. you need to either give them a hell of a speed malus and very low str and consider lowering their skills even FURTHER (which is crazy given that they're at a 2) to make this even remotely fun to play against
> 
> not really sure how to rectify the issue WHILE preserving the power fantasy for the knight
> 
> test merge may be worth seeing how it interacts but i am worried at this being the mother of all adventurer powercreep ngl

They're at medium armor currently. Lowering their martial skills further would not change anything considering anything can be trained up to apprentice, which is what they are currently at. The test merge suggestion is because I think it would help settle a debate if we could see some fights with it, since I cannot really test that myself. I still firmly believe a heavy armored knight with better strength, and way more skill, is still going to one-shot decapitate this slow mage that voluntarily puts itself in melee range.

**Comment by Mikierpg** [comment]
I feel like when you run into Mixing Martial and Arcayne, the only really suitable option for balance is to go the Naledi path. You give them a -6 spell point malus (so even if they train to legendary, they can never spend a point) and then you hand pick 1-2 spells for them to have that'd fit the asthetic.

Naledi has fetch and Ensnare, to complement their melee build. 

I dont think our current spell variety has much to offer for an arcyane knight that isn't just a copy of the Naledi Merc class however.

**Comment by GeneralPantsuIsBadAtCoding** [comment]
> I dont think our current spell variety has much to offer for an arcyane knight that isn't just a copy of the Naledi Merc class however.

Big agree, and ultimately the reason I choose to close this now. If you wish to be an "arcyne knight", you could potentially see about getting taught by a mage. Having martial skills, armor skills AND magic on round-start is _wild_, even if it sounds super fun.

Maybe if they came with a custom spell-set à la Carian Knights it could work... but as is it'd either be a copy of something existing, or something way too overpowered.

**Pull request closed without merging**
