### PR TITLE
Psydonian Crusaders in Bikini Armour

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
Adds bikini armours!!!!!!! They don't cover the stomach. Good luck.

Adds Ravox and Malum amulets. I love you Pantsu.

Templars now get a weapon choice between bastard sword, flail, and mace. Their weapon skills have been adjusted to Journeyman, increased to Expert for the weapon they choose.

Clerics, Templars and Paladins can choose Ravox and Malum as their patrons. Templars and Paladins can pick Old God also.

Old God faith description rewritten to represent server lore. Psydonians are not heretics, but nostalgists in denial.

Confessor is now locked to paladin deities.

Fixes tabard colouring for boobed characters.

Gave watchmen and squires keep keyrings.

### CODE REVIEW

**Comment by Mannybrado** [comment]
> Also they actually have holy spells so there's the bugbear of psydon is dead why you castin', as I don't thiiiink any of the holy skill havers can go psydon but that's not as important

Confessors get holy spells. They probably shouldn't, but this rule has already been broken.

**Comment by Kavrick** [comment]
I really do wish you didn't bundle buffs alongside other more necessary things. 
But either way, not quite sure why templars can pick non-pantheon gods when they work for the church.

**Comment by EvenInDeathIStillServe** [comment]
> I am against giving templars the weapon glow up; their surprisingly high weapon skill was tempered by the fact a.) they started with so-so armor but more importantly b.) it was in swords. Letting them have the choice of the frankly cracked weapons of blunts and whips would make them a menace.

> I am also personally against letting templars go Psydon; they are attached to the _church_, and while the Inquisitor nominally is he is a _heretical_ visitor people keep around as they tolerate them. Someone in with the church shouldn't be a heretic. Also they actually have holy spells so there's the bugbear of psydon is dead why you castin', as I don't thiiiink any of the holy skill havers can go psydon but that's not as important

Will have a look later today to see what weapons would be appropriate, along with converting pantsu about how Psydonians are treated in our lore.


> I really do wish you didn't bundle buffs alongside other more necessary things.

ADHD be like that. I'm sorry. I'll rry to separate things from now on.

**Comment by benj8560** [comment]
personally half love this. With others that it don't make much sense for anyone who follows psydon to have any kind of holy magic. Bro is DEAD. 

Skyrim mod armor is epic. Gimme. Need it. I will happily die in PVP thanks to boob armor.

**Comment by EvenInDeathIStillServe** [comment]
After talking to pantsu, the PR will be amended to remove remove all miracles from psydonian templars save for lesser miracle, they'll get a silver psicross as compensation. The flail and mace will also be downgraded to iron ones.

**Comment by bearrrrrrrr** [comment]
please merge this already i need my slutmogs

**Pull request merged**
