### PR TITLE
Arcyne Potential Rebalance (+Arcanist Fix)

### PR DESCRIPTION
**Pull request by AtoriBirb**
## About The Pull Request

So when virtues first came out, arcyne potential was the one that I thought would be the most game breaking. I set out to break it myself, and I did, I had a Cleric with tier 4 abilities and LEGENDARY magic, 6 points worth of spells. Other people gave it a try, enjoyed it, but universally it was agreed that it needed a nerf.

Today, what the trait is amounts to this:
A. If you have any level of arcyne and NO armor traits, you get +1 spell point.
B. If you have any level of arcyne AND armor traits, you get nothing.
C. If you have NO level of arcyne you get prestidigitation and -6 spell points, which effectively limits you from gaining more.

Option A applies to Mage, a Dune Strider, one of the mercenaries, court magician and a few other mage-likes.
Option B applies to Pontifex and Arcanist (Arcanist is bugged and this PR also fixes that)
Option C is for everyone else.

Basically, you get prestidigitation If you're not magical, akin to Orison for miracle users, at the cost of your stat block. Not great. Devotee gives a tier 0 on top of Orison, making it a much more viable, and flavorful choice. I've seen it be used by wardens, guards, etc to try and be a bit of a combat healer, so great.

### Proposed changes:
For non inate-arcyne, instead of a -6, moving it to -4. This means that at MASTER and LEGENDARY, you will get one skill point. You would have to spend a good bit of your rested skill points to get to this, but it is possible late in the round for those that wish for this.
For pontifex, this adds 2 spell points to give them a grand total starting of -4, like the non-inates. This also means that they can get at least something out of losing their stat block for this choice. One level 2 spell, or 2 level 1 spells.

## Why It's Good For The Game

Arcyne potential has so much potential (hah) and I feel as though it was a bit over-nerfed. Peopled enjoyed it, and I wanted to recapture a little of that back. Currently, if you are not arcyne, you have a 1% chance per rest to learn from a book that's not yours, or a 1% chance per gem you try to break over a book to get on the path to getting any arcyne.. it's not possible. This would at least give people the chance to late-game earn some flavor for their characters. It will not help them early game at all.

I do expect this to have a lot of balance debate, but we'll see.

### Arcanist Bug Fix
Tried to do this in another PR, can just do it here. Arcanist currently benefits from traits it is not intended to, this fixes that.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
gonna repost what i did in discord:
honestly have nostronjg opinions about this. imo it's important that magick remains difficult to access or rare, but that's a goal we're already semi failing at PEDFSKNF

if this allows ppl to access spells too readily it's very easy to dial back, but i doubt it will. no complaints here :] 👍

**Comment by radarseas** [comment]
there needs to be a limit for some spells like repulse to a trait that only mages, liches and zizoid clerics that have completed rituals get.

otherwise you're gonna get royal guards, brigands, iconoclasts, knight errants, assassin rogues or barbarians and other roles _that probably shouldn't have access to such magics for balance reasons related to having it._

**Comment by AtoriBirb** [comment]
> there needs to be a limit for some spells like repulse, blindness, invisibility, lightning and other very fast win spells to a trait that only mages, liches and zizoid clerics that have completed rituos **should get**.
> 
> otherwise you're gonna get _royal guards, brigands, iconoclasts, knight errants, druids_ (you thought kneestinger + whip was bad enough?), _assassin rogues, vampire lords or barbarians_ and other roles _that probably shouldn't have access to such magicks for balance reasons related to having it._

Very aware of this, but again I would promote that in this case, all of those classes would need to spend EVERY NIGHT successfully learning from a book, because it is only at legendary and master that they'd get a skill point. Could it happen? Yeah, but this individual will only be getting to do so very late game when it probably barely matters anymore. The book still limits people with sleep cycles, even more so if they don't dedicate themselves to it with high intelligence, drugs, etc.

If you give me a knight that has foregone its strength stat pack to get this, I will double grab tackle them after they shunt me away once with their pathetic spell.

Even further, if it does not make IC sense for a character to take this virtue, and they take it just because meta meme, then I'd even say that's green for a mod to step in since that's probably not the kind of person we even want coming around.

**Comment by YakumoChen** [comment]
I played with the trait last night and was disappointed after spending 3 hours getting a book with a gem, studying with swampweed, failing most of my study attempts (I suppose I need more gems, nothing in the game really hints at this and gems are hard to acquire) that even the one skill up I got didn't provide a skill point

Mechanically spells do seem pretty powerful and maybe should be in tiers but prestidigitation is also worse than orison AND you get a healing spell at round start with Devotee.

I'm not sure how Potential is supposed to be viable or worth getting outside of playing a mage at all.

**Comment by YakumoChen** [comment]
Semi-related but Devotee feels like a trap for paladins/templar since they don't advance in the spell tree and get nothing

**Comment by AtoriBirb** [comment]
> Semi-related but Devotee feels like a trap for paladins/templar since they don't advance in the spell tree and get nothing

It does, I play it on my templar/hymnist. The thing is you have to spend like 200% devotion, then pray to get it back to rise to tier 2. It's a little annoying but fairly easy to do just by using your miracles a bit.

**Comment by CandleJaxx** [comment]
in my experience the main issue isn't people playing to be the best, it's people who just want to have arcane abilities on top of a side bit. sure, people will overdo it and try to creep into op territory, but i feel like this should be moreso a case of lowering the ceiling rather than raising the floor, you know?

**Comment by AtoriBirb** [comment]
> in my experience the main issue isn't people playing to be the best, it's people who just want to have arcane abilities on top of a side bit. sure, people will overdo it and try to creep into op territory, but i feel like this should be moreso a case of lowering the ceiling rather than raising the floor, you know?

I get what you mean. It just doesn't seem like anyone wants to take the time to make that a reality, one of the reasons I wanted to put this forward since it's the easy slap job. Currently there is no floor or ceiling, this at least puts one there, and it's easy to remove again if it turns out to be too much. Even when this virtue was at full power I didn't see that many people running around doing insane stunts (it was just me because I live for this kind of balance testing)

**Pull request merged**
