### PR TITLE
Gives the court mage their own tower and the duke a penthouse suite

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This PR moves the court magician (and their two apprentices) into their own wacky wizard tower right next to the manor. The area the mage's quarters used to be has instead been renovated into a penthouse suite for the duke/duchess.

Screenshots below.
<details>
<summary>Mage Tower</summary>

Mage's Bedroom/Study:
image

Balcony/Kitchen:
image

Mage's Library/Entry Floor:
image

Basement/Apprentice's Quarters:
image

</details>

<details>
<summary>Duke's Suite </summary>

Entry Hallway & Private Kitchen/Dining Area:
image

Private Bath:
image

Bedroom + Balcony:
image
</details> 

Additionally, this PR includes some other miscellaneous mapping changes; such as expanding the garrison's training yard, adding a few bathrooms around the keep, adding a few more sewer entrances around the city, and a much smaller 'guest bedroom' where the monarch's room used to be for visiting nobility.

<details>
<summary> Expanded training yard, hopefully with enough room for some proper duels. </summary>

image
</details>

## Why It's Good For The Game

Baller ass wizard tower. Wizards belong in towers, dude. Also, the wizard getting significantly larger/more grandiose living quarters than the duke was kind of silly.

image

### CODE REVIEW

**Comment by Ephemeralis** [comment]
Super nitpick: some couches & central table in the main library/entry floor would be baller, since it looks a bit empty. Soulful otherwise, great work!

**Comment by Cleric2145** [comment]
Maybe make the tables in the Duke's suite fancy tables so they get the swaggy table cloths?

**Comment by YakumoChen** [comment]
Having a large pool above the ground floor isn't very realistic for the era, I feel.

**Comment by lpeapnni** [comment]
> We also apparently have four apprentices now(?), will need to map in 2 more bedrooms.

we dont, i literally just made this and posted it in the discord not knowing about this pr
image

**Comment by YakumoChen** [comment]
> Having a large pool above the ground floor isn't very realistic for the era, I feel.

should this be addressed? I don't like the idea of there being a rooftop pool in the keep, when every other bath is underground. I can't imagine the stone flooring being all that watertight.

**Comment by Lutowski** [comment]
freakeng epic

**Pull request merged**
