### PR TITLE
[TESTMERGE] [DO NOT MERGE] Debloats Azure Peak

### PR DESCRIPTION
**Pull request by Lutowski**
## About The Pull Request
Ports the following from Vanderlin/TG/Stonekeep (huge thanks to them):
* Removes several base tg features & mentions of it from the game. Diseases, xenobiology, cyborgs, chem reagents, implants, mining, lavaland, materials, antags.
* New light system.
* Particle weather.
* SSsounds and soundlooper improvements.
* Cargo boat, files for now until rest is ported and mapped in.
* New broom & glass shard sprite from Vanderlin.
* New troll sprite & sounds from Vanderlin.
* Net sprite from Stonekeep.
* New day, midday and nightfall music by Pizza @ Vanderlin.
* New lobby music.

## Why It's Good For The Game
HHHHHHHUUUUUUUUUOOOOOAAAAAAAAAAAAAAAAAAAAAARGH

bjorn-vinland-saga

### CODE REVIEW

**Comment by Cleric2145** [comment]
image
AHHHHHHH!!!!!

**Comment by Disheveled-arch** [comment]
A new world is on the horizon.

**Comment by bearrrrrrrr** [comment]
> AHHHHHHH!!!!!


**[AAAAAAAAAAAAAAAAAAAAAHHHHHH!!](https://www.youtube.com/watch?v=W3Ww9wigdso)**

**Comment by Tenryumi** [comment]
AAAAAAAAAAHHHHHHHHHH 🔥🔥🔥🔥🔥🔥🔥

**Comment by SmokingCrackForChrist** [comment]
i'm in the PR, based

**Comment by Lutowski** [comment]
Going to keep it testmerged for a couple of days to cast a wide net over potential bugs, but it's otherwise in full-merge territory now.

**Comment by DorfGuy1** [comment]
Thank you. I hate having to do code diving because of all the old TG stuff still around.

**Pull request merged**
