### PR TITLE
Left-Handed Magicks: Zizo miracles up to t3

### PR DESCRIPTION
**Pull request by Ephemeralis**
## About The Pull Request

The first batch of my Inhumen/Ascendent spell additions. Woe approaches.

Zizo clerics/devotionists receive access to the following:

- **T1: Profane.** Shoots a splinter of bone at a target for a lump sum of brute damage (20) and a low chance to embed a splinter of bone in a random limb. If you are holding a stack of bones in your free hand, it consumes one and upgrades the bone splinter to a lance (35) and improves the embed chance further.
- **T2: Lesser Animate Undead.** Summon a non-sentient skeleton companion for a large sum of devotion for your nefarious ends. Identical to the old necromancer spell.
- **T3: Rituos.** Rituos is the **signature** miracle for Zizo, a fell ritual that once per sleep cycle, allows you to draw upon the Lesser Work to skeletonize one of your limbs (except your head) and gain knowledge of any 1 arcane spell of your choice until you next rest. Upon skeletonizing a limb, you become **undead**, meaning that churn effects and divine miracles not of the Ascendents will hurt you. Skeletonized limbs cannot bleed.
   - Upon having all limbs but your head skeletonized, you complete the Lesser Work, and gain 3 levels of arcane magic skill, plus an extra 3 spell points permanently for the rest of the round, and Rituos no longer becomes usable.
   - If you have your skeletonized limbs removed or replaced, you still remain undead.

In addition, all Adventurer clerics can now be of any God choice, not just the Divine.

I originally had a T4 planned but after playing with Rituos a bit in testing, I'm not sure they really need it. A mixture of holy magic and arcane magic is quite strong. A Zizo cleric who has completed Rituos is a bit of a soft-antagonist, like a "light" lich, and gain a large boost of power in exchange for being weak to the usual anti-undead things.

Please use responsibly!

## Why It's Good For The Game

Zizo had nothing, now she has something.

### CODE REVIEW

**Comment by Onutsio** [comment]
Oh my god this whips. Zizo!

**Comment by Ephemeralis** [comment]
She's not moustache twirly evil, she's just entirely unafraid to co-opt the lingering power of the dead for her own aims and uses. Graggar and Baotha are probably the ontologically evil ones if I had to guess.

**Comment by Lutowski** [comment]
merge this right now

**Comment by faaaay** [comment]
I really like this PR! Would it be possible to also expand the patron selection for Paladins?
Also, becoming undead doesn't make mobs of the "undead" faction friendly to you, right?

**Comment by MaSvedish** [comment]
shes a necromancer, this is entirely on script. good PR

**Pull request merged**
