### PR TITLE
Forgotten Alcove

### PR DESCRIPTION
**Pull request by Varoxus**
## About The Pull Request
A disused, dilapidated space that was once used at some point in the town's past but has long since been forgotten in favor of the new and far more well maintained areas on the surface level of the town. These spaces could be made into semi-functional areas of any sort but will need a good deal of work, cleaning, and likely remodeling if anyone wished to do so. Otherwise, they serve as nice semi-dungeon sorts of areas that someone could go into and collect a bit of loot or slay some raus.

<details>
<summary>Screenshots</summary>
<br>
Entrance (same as the original concept but without the sign)
<br>

Entrance area

<br>
Main area
<br>

new

</details>

## Why It's Good For The Game
spaces for someone to fix up if they've got the time and dedication, otherwise just an expansion on the sewer-level dungeon areas that have a bit of flavor to them.

### CODE REVIEW

**Comment by Mikierpg** [comment]
Should include pictures when doing mapping changes

**Comment by Kavrick** [comment]
We already have stalls, don't we? Also these rooms are bigger than the smithy itself.

**Comment by Lutowski** [comment]
My thoughts on this PR:
* I already informed you over discord that I was going to make the current stalls bigger.
* This is way too big. You'll still have an excess room left over after building the necessary equipment required to run, say, kitchens or forges.
* The location isn't appropriate. People want to see stalls when they walk past it in town, and having it underground makes them forgettable. You want to jam key locations like these right into the players' eyes, which is why the inn has stalls mapped right next to it in the town square.
* A more subjective take that you can choose to ignore - I think it's unflattering. You mapped in giant squares, added some peddlers and nothing else. I can understand that's challenging to do on a codebase that's severely lacking in decorative items (an issue I and couple of spriter friends hope to solve in the future) but it genuinely feels like you CTRL+V'd in a hurry and called it a day.

**Comment by MaSvedish** [comment]
These stalls being bigger than most of the establish merchants doesn't make sense. This also looks like a mechanical fix to an RP issue. [It kinda off putting? Out of place?]

**Comment by Varoxus** [comment]
> My thoughts on this PR:
> 
> * I already informed you over discord that I was going to make the current stalls bigger.
> * This is way too big. You'll still have excess room left over after building the necessary equipment required to run, say, kitchens or forges.
> * The location isn't appropriate. People want to see stalls when they walk past it in town, and having it underground makes them forgettable. You want to jam key locations like these right into the players' eyes, which is why the inn has stalls mapped right next to it in the town square. It consolidates roleplay in one place.
> * A more subjective take that you can choose to ignore - I think it's unflattering. You mapped in giant squares, added some peddlers and nothing else. I can understand that's challenging to do on a codebase that's severely lacking in decorative items (an issue I and couple of spriter friends hope to solve in the future) but it genuinely feels like you CTRL+V'd in a hurry and called it a day.

1. Doesn't solve the issue that they're still locked behind the merchant which is rarely ever staffed, and for your 'making the stalls bigger' you said it would be 1-2 tiles, I really don't think that's good enough for a proper workshop, as I also told you.
2. It's that big so that you can add walls, stations, storage and anything you might want. That is the entire point. If it's too big I can cut them down in size but the point is you should be able to have room to make walls, maybe a back room or anything else you might want.
3. I made them so they wouldn't intrude on anyone else's areas or projects, I could have moved a ton of the other buildings around and made space for the workshops but I'm not going to touch your stalls or any of the other buildings because that'd surely anger people.
4. Yes your stalls are in the prime place for people to use them, but nobody does because they're far, far too small. And again, locked behind the merchant which is rarely ever there.
5. I'm not sure why you added that 'take' they're literally stated to be empty rooms that you yourself customize. What point were you trying to make here?

**Comment by Varoxus** [comment]
> We already have stalls, don't we? Also these rooms are bigger than the smithy itself.

These aren't meant to be stalls, they're meant to be workshops. And... no. The smithy is four-levels worth of rooms, each of these rooms is about as big half the smithy's main floor.

**Comment by Varoxus** [comment]
let me give an example of what an actually customized example might look like.
customized room
For a blacksmith, at least. It's really not a terribly huge amount of room. For other professions it might be a bit much though, sure.

**Comment by bearrrrrrrr** [comment]
can we get actual screenshots of this area? this looks way too big

**Comment by bearrrrrrrr** [comment]
this just...kinda seems like a dead-end alley that nobody's gonna go to. sorry :/ might wanna rethink it

**Comment by GeneralPantsuIsBadAtCoding** [comment]
> this just...kinda seems like a dead-end alley that nobody's gonna go to. sorry :/ might wanna rethink it

Have to agree with this. Seems like it'd be used for dubious deeds at best, and flat out ignored at worst.

I DO like it though, but it certainly is not quite as well executed as it could be. Integrating it into the sewers, maybe making some bits collapses, others infested, just adding to the town as a whole rather than only "a corner of empty workshops" certainly would make it a ton more appealing. Perhaps it could even hold the remnants of former workshops? Like barrels in one, some tables and other trash in another... that kinda stuff.

**Comment by Varoxus** [comment]
> > this just...kinda seems like a dead-end alley that nobody's gonna go to. sorry :/ might wanna rethink it
> 
> Have to agree with this. Seems like it'd be used for dubious deeds at best, and flat out ignored at worst.
> 
> I DO like it though, but it certainly is not quite as well executed as it could be. Integrating it into the sewers, maybe making some bits collapses, others infested, just adding to the town as a whole rather than only "a corner of empty workshops" certainly would make it a ton more appealing. Perhaps it could even hold the remnants of former workshops? Like barrels in one, some tables and other trash in another... that kinda stuff.

There are many portions of town that are already heavily ignored, but, fair enough. Thank you for the actual suggestion though, that's definitely workable and here's what I came up with to fit with that theme. Still WIP of course but, is this more what you might want to see?

**Comment by Kyogon** [comment]
I think having a second smithy is just asking for frustration. We have enough trouble getting people to sign up for blacksmith as is, having a 2nd shop running in the town would just cause conflict at best.

And at worst, it would be used by someone who is doing it out of spite for the blacksmiths, which at that point it should not be something that is made easy. If anything, this takes interactions away from existing roles where the interactions are already spite sparse. It doesn't feel like it has a lot of place in the town.

I can appreciate the thought that went into this, but I do not like this idea. Perhaps look into expanding upon existing shops, but do not take from them.

**Comment by GeneralPantsuIsBadAtCoding** [comment]
> Still WIP of course but, is this more what you might want to see?

It's closer for sure yeah! Can still put the keys with either steward, a machine or maybe the Mason/Artificer Guild if you want to, too.

> I think having a second smithy is just asking for frustration.

To be fair, the amount of times I've seen people set up forges elsewhere is already big. I doubt this would impact that much, neither positively nor negatively, especially with buffs to the ACTUAL smiths and whatnot. Just because one used to be a forge doesn't mean the person that might set up inside of it will also make a forge, either. They _do_ lack a greatforge too after all.

**Comment by Varoxus** [comment]
> I think having a second smithy is just asking for frustration. 

This isn't a second smithy, and yeah as pantsu said... it takes all of five minutes for a smith to setup somewhere else as it is. As was stated by many, these are out of the way locations that most likely won't even go to, and I'm removing the peddlers, shutters, etc. that would have made them more viable for a shop or something like that. So now they're mostly just renovation projects, at best.

I can remove the forge if that's what's got you not liking the space, but yes. As a person who plays a smith that doesn't work at the smithy, most will still very much flock to the actual merchant due to the fact that basic forges can't make steel, and general lack of materials to make someone anything more than one or two pieces of gear.

> It's closer for sure yeah! Can still put the keys with either steward, a machine or maybe the Mason/Artificer Guild if you want to, too.

No keys for this version of the place. They're old, forgotten and dilapidated so at best, the new occupants would need to either make new doors or go to an artificer to have new sets of locks/keys made.

**Comment by Varoxus** [comment]
Alright, made the northern room into an abandoned "doctor's office" (don't mind all the chains and blood.)
new

**Comment by Varoxus** [comment]
I feel like it definitely works better with the new changes but, I don't think I'd like to add it at the moment.

**Pull request closed without merging**
