### PR TITLE
gethsmane

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

gethsmane - expands the dungeon i added yesterday

## Why It's Good For The Game

And there appeared to him an angel from heaven, strengthening him. And being in an agony he prayed more earnestly; and his sweat became like great drops of blood falling down upon the ground.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
my internet is so bad that i literally can not upload a better image
im so sorry man
image

**Comment by Burrito-Justice** [comment]
image
My copy of this map is missing some content so excuse the missing stuff, but this is otherwise what it looks like

**Comment by bearrrrrrrr** [comment]
> My copy of this map is missing some content so excuse the missing stuff, but this is otherwise what it looks like

i lov u

**Comment by bearrrrrrrr** [comment]
wait dont merge yet

**Comment by bearrrrrrrr** [comment]
ok go on

**Pull request merged**
