### PR TITLE
Severely reduces hard stuns on silver items and miracles

### PR DESCRIPTION
**Pull request by coffeecoffeecoffee**
## About The Pull Request
HOPEFULLY gives the silver chalice's effect a fucking cooldown. You should not be able to hardstun werewolves infinitely with it anymore. It now sets them on fire a little bit and knocks them down, but you can only do so once every like 100 seconds.
Changes miracles and silver daggers so that they don't totally and instantly fuck our antagonists. Lesser and greater heal now light undead enemies aflame, but no longer stun them at all, it's just a stack of fire. Stabbing them with silver daggers should still stun them, but they'll be able to get right back up so they can still engage and aren't immediately just taken out of the game.
THIS NEEDS SOME TESTING BUT I CANNOT DO ALL THE TESTING LOCALLY WITH ONLY ONE "MIND" (PLAYER).

## Why It's Good For The Game
Instant death mechanics are pretty bad for roleplay and we've severely nerfed the worst parts of vamp lord.

### CODE REVIEW

**Comment by benj8560** [comment]
Infact you can test locally but its awkward. How you do so:
Start a server like normal and join it,
Fully close byond but leave your ckey-using dreamseeker client open
Then join the server again. As long as byond is closed you will join as a guest and can test stuff on your private server when needing 2 players.

**Comment by GeneralPantsuIsBadAtCoding** [comment]
This been tested yet?

**Comment by coffeecoffeecoffee** [comment]
nopers, I will shortly

**Comment by coffeecoffeecoffee** [comment]
It now works, tested. Unfortunately doing these things multiple times doesn't seem to make the fires worse, so despite what I'd like you can't turn a vampire into a torch by miracle-ing him with 5 different acolytes at once, but it works. Silver goblet now has a cooldown, all silver items burn and stun but only for a moment, miracles just burn.

We should talk about what to do about churn undead because as it is, it seems they make undead *fucking explode on the spot*.

**Comment by coffeecoffeecoffee** [comment]
If what I'm being told about ticks is that 10 ticks = 1 second approximately, this should make the "stun" from silver items approximately 1 whole, whopping, fat second, and the cooldown 12 seconds.

**Comment by bearrrrrrrr** [comment]
this is definitely a good thing
we will probably also need to change VL's hardstun slop combat at some point, but that's an 'in the future' thing, assuming that's even a problem here given the nature of the server

+100000

**Comment by EvenInDeathIStillServe** [comment]
> this is definitely a good thing we will probably also need to change VL's hardstun slop combat at some point, but that's an 'in the future' thing, assuming that's even a problem here given the nature of the server
> 
> +100000

https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/216

**Pull request merged**
