### PR TITLE
A balance experiment. TESTMERGE ONLY

### PR DESCRIPTION
**Pull request by HeroWithYay**
## About The Pull Request

Makes adjustments to armor, armor penetration and force values across the board. 
Generally lessening the gaps between leather, chain and plate, as well as making them less impervious

The new values make Slashing attacks generally more effective against leather ('blunt=72, slash=70, stab=75")
Stabbing attacks generally more effective against Chain ('blunt=78, slash=75, stab=72")
Blunt attacks generally more effective against Plate ('blunt=70, slash=80, stab=80")
Clothing-type armors have been given lower values between 60-70
AP values are centered around 55. 

There is an awful lot changed and some of the values might seem deranged. 
Dancing around armor values like this, one or two points of force can make a very large difference.
This needs a lot of testing.

To give an example of how this works in practice:
If one were to two-hand a Steel Sword with X Strength

Cuts would deal 8 damage through leather, 3 damage through chain and 0 damage through Plate.
Stabs would deal 3 damage through leather, 6 damage through chain and 0 damage through plate
Pommel strikes would deal 3.7 damage through leather, 0 damage through chain and 5.7 damage through plate

## Why It's Good For The Game

It might not be.
But the current armor values aren't so great, consider this an **attempt.**

Will need a lot of feedback and adjustments yet, there is sure to be oversights and a lot of the weapons might seem a bit samey, considering how tight the values are.

### CODE REVIEW

**Comment by HeroWithYay** [comment]
> yet another buff for dodge expert 😔

This definitely makes dodging stronger. May need to make some adjustments to that.......

**Comment by crix870** [comment]
I won't pretend to understand the complexities behind armour/weapon calculations but:

-  Hitting the spd multiplier of dodge_expert  and/or scaling armour integrity based on armour class might work.

https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/blob/1b8e0ba601ddb3233b99614e0a617912768d2bc8/code/modules/mob/living/roguetownprocs.dm#L381

- Another angle of attack might be the spd scaling on 'light' weapons to defend and attack better vs low speeders. Could perhaps change this to higher armor pen rather than parry bypass - faster so able to hit those critical weakpoints?

Seems like fun to balance! It's going to be difficult to appease everyone.

> This definitely makes dodging stronger. It's easier to kill someone in armor, so they don't have to land as many hits to win before getting grabbed/whatever. May need to compensate for this elsewhere

One downside to lowering TTK is that combat often becomes less satisfying, particularly on RP servers where prolonged engagements can add to the narrative. Of course, this might just be personal preference.

On the other hand, a faster TTK would result in antags being able to incapacitate opponents faster which would help them with thinning out the sheer number of people pursuing them which might be a good thing sometimes.

How do you anticipate your changes will affect group combat?

**Comment by HeroWithYay** [comment]
> I won't pretend to understand the complexities behind armour/weapon calculations but:
> 
> * Hitting the spd multiplier of dodge_expert  and/or scaling armour integrity based on armour class might work.
> 
> https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/blob/1b8e0ba601ddb3233b99614e0a617912768d2bc8/code/modules/mob/living/roguetownprocs.dm#L381
> 
> * Another angle of attack might be the spd scaling on 'light' weapons to defend and attack better vs low speeders. Could perhaps change this to higher armor pen rather than parry bypass - faster so able to hit those critical weakpoints?
> 
> Seems like fun to balance! It's going to be difficult to appease everyone.
> 
> > This definitely makes dodging stronger. It's easier to kill someone in armor, so they don't have to land as many hits to win before getting grabbed/whatever. May need to compensate for this elsewhere
> 
> One downside to lowering TTK is that combat often becomes less satisfying, particularly on RP servers where prolonged engagements can add to the narrative. Of course, this might just be personal preference.
> 
> On the other hand, a faster TTK would result in antags being able to incapacitate opponents faster which would help them with thinning out the sheer number of people pursuing them which might be a good thing sometimes.
> 
> How do you anticipate your changes will affect group combat?

It only adjusts TTK when armor is involved. As you can now potentially take someone down without actually breaking it. Though in most cases from local testing I find parts tend to break regardless before someone goes down.

The idea is to prevent scenarios where one party has to land like.... 20 hits while their opponent remains impervious before they can even start to do damage. Since there will almost always be a way to do damage through armor.

But realistically in most combat, not everyone is armored up to begin with. And generally weapon damage is lower across the board when it comes to unarmored opponents. So it's really hard to say.

**Comment by kittysmooch** [comment]
what on earth is the navbeacon change for

**Comment by bearrrrrrrr** [comment]
images

Not reading all of zat. Merge eet.

**Comment by HeroWithYay** [comment]
> what on earth is the navbeacon change for

Oh. 
Lmao.

At some point I used find/replace to change the leather armor values.
And the navbeacon happened to get caught in that.

**Comment by HeroWithYay** [comment]
Speed still gets a bonus to bypass parry with swift weapons, but it is now lessened. Hopefully this is enough to compensate.

This might be too much as the swift weapons also aren't too strong. Most of the daggers in the game dont have enough damage to hit through plate without using Pick or Sucker Punch. (De tace does but... it's one of them "Broken-on-purpose" weapons)

And neither the Sabre or the Rapier get access to Pommel Strike, meaning they can't realistically breach the 80 armor pen either.

**Comment by HeroWithYay** [comment]
> Speed still gets a bonus to bypass parry with swift weapons, but it is now lessened. Hopefully this is enough to compensate.
> 
> This might be too much as the swift weapons also aren't too strong. Most of the daggers in the game dont have enough damage to hit through plate without using Pick or Sucker Punch. (De tace does but... it's one of them "Broken-on-purpose" weapons)
> 
> And neither the Sabre or the Rapier get access to Pommel Strike, meaning they can't realistically breach the 80 armor pen either. (Yes I made Pommel strike actually the best option against plate)

To re-iterate. Swift weapons are /still/ just as bad at penetrating plate as they used to be.
But they have gained the ability to do pretty strong damage through chainmail. Which they couldn't do before.
This is in line with the identity of a swift weapon attacking gaps in armor, which is good!
But also maybe the nerf isn't entirely deserved. We will see if we ever get to testing in-game.

**Comment by kittysmooch** [comment]
> > what on earth is the navbeacon change for
> 
> Oh. Lmao.
> 
> At some point I used find/replace to change the leather armor values. And the navbeacon happened to get caught in that. Lemme just....

nw i was prepared to believe it affected something childed to it lmfao

i notice a lot of values are really specific with way fewer round numbers, did you actually spreadsheet all of this out? im intrigued but i dont have a good sense for how it plays out without booting up a test instance and whacking npcs

**Comment by HeroWithYay** [comment]
> > > what on earth is the navbeacon change for
> > 
> > 
> > Oh. Lmao.
> > At some point I used find/replace to change the leather armor values. And the navbeacon happened to get caught in that. Lemme just....
> 
> nw i was prepared to believe it affected something childed to it lmfao
> 
> i notice a lot of values are really specific with way fewer round numbers, did you actually spreadsheet all of this out? im intrigued but i dont have a good sense for how it plays out without booting up a test instance and whacking npcs

I started with the basic "Steel" version of each weapon, adjusted it til it did what I wanted it to do. Then adjusted other weapons relative to that. Usually with only 1 or 2 force of difference. I did have a spreadsheet just to help draft it in my head but nothing impressive.
I can't really do round numbers because even a force increase of 5 can basically double the damage of a weapon through armor.

I would have liked to make the armor values from the 10 to 30 range instead, so that not every weapon has a massive listed AP value. But I figured that could have unintended effects from other sources of damage like fall damage.

**Comment by LittleEvil9** [comment]
Daggers shouldn't have the same cut pen as thrust attacks imo, while you're at it might as well remove the god awful bardiche wind up on its cut attack and increase its damage multiplier to 1.0.

**Comment by HeroWithYay** [comment]
> Daggers shouldn't have the same cut pen as thrust attacks imo, while you're at it might as well remove the god awful bardiche wind up on its cut attack and increase its damage multiplier to 1.0.

Already made the bardiche equivalent to the billhook, except with cuts instead of thrust.

And I basically gave daggers less of a force multiplier instead to basically do the same thing except also make it worse than stabbing against are breaking armor and against unarmored targrts

The point is to make dagger cuts weaker in exchange for the different damage type. But if its too much weaker, the benefit for swapping damage type is outweighed.

It could stand to be lowered to 0.8. But it already has a very small amount of use cases

**Comment by ApplePlastic** [comment]
goblin/viking mob buff lowkey

**Comment by HeroWithYay** [comment]
> goblin/viking mob buff lowkey

The stone weapons are still mostly pretty bad, but yeah weapons in general are a lot scarier, no matter what they are

Vikings absolutely stronger.

**Comment by sneksnek** [comment]
This PR is nuts at a first glance, but it makes a lot of sense when I looked deeper into the numbers. My main reservations with it are that daggers now deal considerably less damage to unarmored targets (simply due to lower force) and have less benefits to their accuracy from swiftness to achieve such. Also the piercing capabilities of other weapons have improved while dagger pick intent has been nerfed and still has a slightly longer swing delay (12 vs 10 of smash or chop).

**Comment by sneksnek** [comment]
Ignore what I previously said. I think most of these changes make sense, but I dislike how some weapons have less force and now deal less damage for targeting unarmored regions. In a way, this could make some fights take longer than they originally did if one were to intelligently target unarmored areas in a person's armor. If someone's coated in metal though, this will improve that condition. I believed an armor degradation system that decreased armor values as the armor's durability decreased was a proper solution.

**Comment by HeroWithYay** [comment]
Closing this in favour of a different, slightly higher effort solution.
That doesn't have scuffed and relatively unintuitive 55 AP on everything
AP should not work this way to begin with, it's inherently flawed and needs an actual change to its function instead of this

**Pull request closed without merging**
