### PR TITLE
Adds static threat spawners to procedurally spawn enemies in-round

### PR DESCRIPTION
**Pull request by Tenryumi**
## About The Pull Request

See title.
This adds a new type of landmark - a static threat spawner.

So, here's the general idea behind these:
These are static threat spawners. They routinely will, at random, generate enemies in the same way that ambushes spawn them - that is, spawning them around random trees/mushrooms/etc within view of themselves. However, unlike ambushes, THESE
mobs will actually stick around and not despawn!

After a specified time into the round, the threat spawners become "active," and will start a cooldown that is randomized between the min and max time. When the cooldown hits 0, it spawns lingering enemies around any valid targets in much the same way that ambushes spawn enemies. Then it goes on a randomized cooldown again, and the
cycle repeats for the rest of the round.

The threat spawners are highly configurable, and the amount of foes they spawn is random as well. However, they are configured to be most likely to only spawn between 1 and 2 enemies, with a very small chance of them spawning anywhere between 4 to 6 enemies. This way, we usually only see a couple dudes spawn, and in some cases, well, let's just say the wardens will have something to take care of!

On a side-note, if this is accepted, PLEASE testmerge this first. I have no idea how many enemies will actually be spawned by the, say, 1:30:00 mark in a round. I am trying to make it very unlikely that the wilds will be swarmed with dudes, but it IS possible.

CURRENTLY, these spawners have been placed in key locations in:
- The Coasts
- The Bogs (I really wanted to be careful to prevent wanderers getting spawned by RNG so I placed them with that in mind)

### UPDATE:
This also now reduces the price of goblin heads' randomized range from 7 to 40 mammo nto 7 to 10 mammon, because goblin head inflation has now arrived and holy shit it needs to be addressed!!!

### UPDATE 2:
Since the coasts are now more consistently dangerous, wardens have a job to do there, too! In light of this, a smaller watchtower has been built in the coasts right along the cliffside.

## Why It's Good For The Game

My justification for this is the same as what I said in #958 . The bogs and forests aren't dangerous enough and the threats do not persist, giving the wardens pretty much no job whatsoever. This also makes exploring them feel like an already-looted map in an extraction shooter.
So let's try and keep them dangerous, eh?

### CODE REVIEW

**Comment by kittysmooch** [comment]
i was JUST thinking abt this to support another pr bless

**Comment by Tenryumi** [comment]
> Didn't know about this being test merged, tried to camp out in the Grove with some friends and it rather quickly turned into a wave defense game that ended up with us overwhelmed and decapitated. Overall really makes the woods more dangerous and scary. It would be wonderful if there was some sort of structure we could build to prevent these from triggering so people can still camp/reclaim buildings without it turning into wave defense. Or even give the Wardens a goal to build some in key points to help keep the roads safe.

There is! If you build a light source within the range of the spawners, they will not spawn enemies at all. The only exception to this are the craftable wooden braziers.
This is of course difficult to do because you can't actually see the spawners ingame, though... I'll see what I can do about that!

**Comment by codyman765** [comment]
> > Didn't know about this being test merged, tried to camp out in the Grove with some friends and it rather quickly turned into a wave defense game that ended up with us overwhelmed and decapitated. Overall really makes the woods more dangerous and scary. It would be wonderful if there was some sort of structure we could build to prevent these from triggering so people can still camp/reclaim buildings without it turning into wave defense. Or even give the Wardens a goal to build some in key points to help keep the roads safe.
> 
> There is! If you build a light source within the range of the spawners, they will not spawn enemies at all. The only exception to this are the craftable wooden braziers. This is of course difficult to do because you can't actually see the spawners ingame, though, so the average player will have no idea WHERE to do this... I'll see what I can do about that!
> 
> UPDATE: So, now you can build ANY light source around the general area of a spawner and it won't create more mobs - now this includes braziers too! So if you want to build somewhere, make sure it's well lit!

Oh amazing! That's really handy to know! It did lead to a hell of a thing to be apart of when the survivor brought back help. The Templar that came was /floored/ by the sight. (I couldn't even get all the dead skeletons in the shot) 



Overall very thematic and fun change. Definitely going to be building more lights so I can still do cozy camping. Or just set up a camp for some wave battles.

**Comment by Vynellin** [comment]
hey you may want to 
a make the mobs despawn after they are killed
and
b make them have a cap as it seems this has been causing a shit ton of lag in the server at this point

**Comment by codyman765** [comment]
Unsure if it's the new watchtower from this or not, due to it looking a bit different. But the stairs near them/the entrance of the coast don't line up anymore.

**Comment by Tenryumi** [comment]
> hey you may want to a make the mobs despawn after they are killed and b make them have a cap as it seems this has been causing a shit ton of lag in the server at this point

They already have a cap on how many enemies each spawner can make! As for despawning, that is probably for the best. I'll see about making then despawn after a while.



> Unsure if it's the new watchtower from this or not, due to it looking a bit different. But the stairs near them/the entrance of the coast don't line up anymore.

What the heck!!! lemme see about fixing that...

**Comment by Lutowski** [comment]
love this, well done

**Pull request merged**
