### PR TITLE
Steel, blacksmithing/merchant adjustments, hide/fur price changes

### PR DESCRIPTION
**Pull request by crix870**
## About The Pull Request

Changes:
-   Recipe for iron->steel (3 iron, 1 coal) now results in 3 steel ingots instead of 4.
-   Added hide as a component of the half-plate and full-plate armours.
-   Changes the value of steel (60 to 40) and iron statues (40 to 20).
-   Changes the item values of hide (20 -> 8) and fur (40 -> 18). The stockpile values have also changed. 
        The stockpile at default now buys hide at 5 and sells it at 8.    (previously it purchased hides at 10 and sold at 15 by default)
        The stockpile at default now buys fur at 10 and sells it at 15.  (previously it purchased fur at 15 and sold at 23 by default)
-  Adds iron chain leggings and steel plate leggings to the merchant machine. Changed the prices for armours upward. Also, rearranged some of the items to make more sense. (eg: for clothing, top-down)
-  Increases the price of coppiette (15 to 20) [total nutriment 50] and raisin cakes (30 to 45) [total nutriment 90]  in merchant machine

Minor changes:
-  Typos
-  Fixed bug with plate boots in merchant machine

     

## Why It's Good For The Game

- Steel is prevalent in the game world. The recipe for steel in a greatforge shouldn't result in more steel out than iron being put in. This is relatively minor in the grand scheme as scrap is still 1:1 conversion and is just as, if not more-so, widespread.  
- Full-plate and half-plate represent the pinnacle of smithing and of heavy armour, it should be more than 4 ingots of steel being slapped together. The addition of leather add some minor complexity (in terms of craft time), item value as well as adding more uses to leather.

The two above changes aim to slow fully equipping heavily armored, non-keep characters by a small amount. 

- Iron and steel statues have too much value for the effort. If mammon is the goal for bandits/merchants then I feel scrapping metal goods to make statues doesn't promote great gameplay. Current values are still at a profit, especially with quality worked in.
 This probably won't dissuade mammon-desirers but I'd like to see what other players think - whether to trend it up/down or whether they are apathetic to it.
- Hide/fur are just too expensive. The values are open to change - current low values may screw over trapping bait profitability.
- Expensive merchant shop imports to cover for what was missing. (chain and plate leg armours)

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
i agree with everything here but the coppiette/raisin bread increase. ppl already avoid paying for food far too often via commie piles. i'd definitely like to see that changed back

armor price increased at the merchant machine is also a little strange. can you explain that one to me? merchants already extremely rarely buy the armor license

**Comment by crix870** [comment]
> i agree with everything here but the coppiette/raisin bread increase. ppl already avoid paying for food far too often via commie piles. i'd definitely like to see that changed back

It was to attempt to shift the main source of food back to player vendors/tavern but I'd neglected the stockpile's raw and cheap food. I think you're probably right in that it's not worth the effort to change it, or rather, keep the merchant as the easiest vendor for non-perishable food.
 
> armor price increased at the merchant machine is also a little strange. can you explain that one to me? merchants already extremely rarely buy the armor license

The price increase was to mostly give it some wiggle room if the other armour types (light, med, heavy) were added to the machine. (20, 40, 60)
In terms of raw material value from the stockpile (with the steel change), 1 steel bar is worth approx 8 mammon (1 iron[6] + 1/3 of a coal[2]) --- I was going to make a comparison to leather boots and plate boots here but there aren't any appropriate armoured light boots.

In thinking about it, I'll revert the price changes for purchasing things from the merchant until I get a better grasp of the game's economy.

**Comment by crix870** [comment]
Updated changes for this PR:
- Recipe for riddle of fire iron->steel (3 iron, 1 coal) now results in 3 steel ingots instead of 4.
- Added hide as a component of the half-plate and full-plate armours.
- Reduces the value of steel (60 to 40) and iron statues (40 to 20).
- Changes the item values of hide (20 -> 8) and fur (40 -> 18). 
- The stockpile prices are now appropriate for the new item values.
 The stockpile at default now buys hide at 5 and sells it at 8. (previously it purchased hides at 10 and sold at 15 by default)
 The stockpile at default now buys fur at 10 and sells it at 15. (previously it purchased fur at 15 and sold at 23 by default)
- Adds iron chain leggings and steel plate leggings to the merchant machine.

**Comment by bearrrrrrrr** [comment]
right, that's basically all i rly had to ask

ill kick this back towards other ppl that know more about economy than me ig

**Comment by Elli-Skala** [comment]
I may be missing something, but doesn't this make steel statues the same price as steel bars and iron statues worth *less* then a unrefined bar?
Is this just a target against mass produced bandit offerings?

**Comment by crix870** [comment]
> I may be missing something, but doesn't this make steel statues the same price as steel bars and iron statues worth _less_ then a unrefined bar? Is this just a target against mass produced bandit offerings?

The prices of iron/steel bars/ores is an oversight. They should also be lowered.

The change is to address the ease from which you can generate value from metal statues -- whether it is to the merchant, bandit or the keep. My intention was mostly for merchant and keep since those don't have inherent risk for asking the smith to do things. 

Post change, a flawless/masterwork steel statue should still reach around 50 mammons, one of the highest-value single-ingredient crafts. Iron statues get shafted. 

Pre change with steel statues at 60 base value, each decently crafted statue is worth 70 mammons which is the highest value item made by common resources (outside of gold/silver+gems). The closest crafted equivalent seems to be direbear cloaks (80 value, no quality) which takes 4 hide and 2 fur.

I admit, I should have gone through item values more thoroughly but this PR is already poorly atomized and statues were the main outlier. At this point I'm willing to trim off any item value and smithing changes to simply address the typos and merchant machine additions.

ref:
The quality modifiers for products crafted by smiths are located here:
https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/blob/cebf7a1516a3366f4630fb7c02b831c1c253823e/code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/_anvil_recipe.dm#L139

1.2x, 1.3x for flawless, mastercraft respectively.

**Comment by Lutowski** [comment]
okay with this PR since it slows down mammon acquisiton a little but that scale shouldn't apply to withdraw prices, so raising those back since they're a relatively valuable crafting material

**Pull request merged**
