### PR TITLE
adds tips to day transitions

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

as the title says. can be tips, lore, whatever.

## Why It's Good For The Game

i wish i could do it cleaner for my own ego (maybe with a .json or .txt) but honestly this works fine

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
> hermaphrodite? sign me up

### Horny Jail. 

images

**Comment by Ruediger4** [comment]
I am Zizo and I APPROVE this PR.

**Comment by Mannybrado** [comment]
i could add a tip to your transition if you know what i mean

**Comment by bearrrrrrrr** [comment]
> no memes

yes memes

> i could add a tip to your transition if you know what i mean

yeah

**Comment by Mannybrado** [comment]
> > i could add a tip to your transition if you know what i mean
> 
> yeah


https://github.com/user-attachments/assets/6c6c9482-7846-473f-82a7-2fc7c0dd4176

**Pull request merged**
