### PR TITLE
Important Balance Fix

### PR DESCRIPTION
**Pull request by Plum-but-gayer**
## About The Pull Request

uh. um. uh. listen. just merge this okay. the people of general chat want it.

## Why It's Good For The Game

sweats

### CODE REVIEW

**Comment by Ollanius** [comment]
I am going to kill you.

**Comment by Lyroy** [comment]
This is a good change. It adds further to the setting's lore that werevolfs are ho otttt as hfcukkk......

**Comment by Kavrick** [comment]
Would rather not have changes that push us towards being an erp server.

**Comment by Onutsio** [comment]
Im Onutsio of the Azure Peak, and I approve of this PR

**Comment by Cleric2145** [comment]
Woof. ERP server is not the same as server with ERP allowed

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Thought I closed that a week ago. Hm.

**Pull request closed without merging**
