### PR TITLE
Remove the 40k Accent

### PR DESCRIPTION
**Pull request by Kavrick**
Removes the 40k ork accent from the game, really does not fit a HRP server. Had a good few complaints about it from other players and I don't think much more needs to be explained.

### CODE REVIEW

**Comment by GeneralPantsuIsBadAtCoding** [comment]
How about instead of fully removing it, we cut out the parts that don't fit? Someone else did so earlier already to make it a bit nicer. I personally am a fan of that accent and rather not see it just disappear, especially since I actually use it pff.

**Comment by Kavrick** [comment]
> How about instead of fully removing it, we cut out the parts that don't fit? Someone else did so earlier already to make it a bit nicer. I personally am a fan of that accent and rather not see it just disappear, especially since I actually use it pff.

I kinda get what you mean, I've gone through the accent and it's kinda hard to just 'prune' it because the ENTIRE thing is just 40k orcs, I'd basically be deleting like 80% of it.

Like anyone who's particularly familiar with 40k will see it stick out like a sore thumb even without the direct slang. I could maybe give it a once-over but I don't really know if it's possible to make it usable without being blatant.

**Comment by coffeecoffeecoffee** [comment]
I think we should just make it slightly into something that is less "the 40k accent", as brutish barbarian-speak is a strong fantasy trope. I think removing it is just being anti-fun for the sake of being anti-fun.

**Comment by Ollanius** [comment]
> I think we should just make it slightly into something that is less "the 40k accent", as brutish barbarian-speak is a strong fantasy trope. I think removing it is just being anti-fun for the sake of being anti-fun.

If I see _another_ cobbled-together goblin screaming at the top of their lungs like a drunken British hooligan without any punctuation-or-tact, I am going to fucking kill them on the spot.

This is not a threat. It is a promise.

**Comment by DorfGuy1** [comment]
Oh, and we're still leaving the elf accent with the horrible brain fucking cyrillic characters in.

**Pull request closed without merging**
