### PR TITLE
Bandits no longer have to be matthios worshippers

### PR DESCRIPTION
**Pull request by chemistrymain3**
They just don't have to. I one line deleted it.

## Why It's Good For The Game

There's no reason they should be obligated to be. There's more reasons than 'I worship matthios' that someone might be a bandit. They're, regardless, more than likely a member of the freefolk and players should be able to think of reasons why they might be there.

I've seen people want to play otherwise criminal characters as bandits and be unable to do so because of the forced worship, when they'd genuinely prefer to be. There are graggarites who want to be- I saw someone play a zizite wizard as bandit but have to just kinda half-ass the whole matthios part. I saw a couple genuine psydonite bandits.

### CODE REVIEW

**Comment by Onutsio** [comment]
Bandits are thematically set around being Matthians. They are essentially Matthian cultists, in a way. No. Their entire gameplay loop revolves around donating to Matthios.

All their equipment checks for Matthios worship, this would break the antag as well.

**Comment by bearrrrrrrr** [comment]
ehnnnn

bandits are pretty matthew-coded. they quite literally sacrifice to Matthew as their primary mechanic

> I've seen people want to play otherwise criminal characters as bandits and be unable to do so because of the forced worship, when they'd genuinely prefer to be. There are graggarites who want to be- I saw someone play a zizite wizard as bandit but have to just kinda half-ass the whole matthios part. I saw a couple genuine psydonite bandits.

This kind of defeats the whole purpose, doesn't it? if people are already playing non-matthew bandits. 

this is also partially- this kind of runs into something else. we _**have no self-antag rules,**_ but people seem to only be willing to do antag-like actions when antag. maybe this is a hint to add some kind of generic opt-in antag role? like 'ohoh i am a thief!! i steal things wif my dextwous thief fingews!!' and it's not a real antag but it gives u antag textg or smth

idk

**Comment by chemistrymain3** [comment]
Talked it over with Onut in DMs.

The bandits/freefolk are matthiosian as an organization, which makes perfect sense to me. This is, basically, just to allow for dual worship.

It does not break any of their items or behavior.

**Comment by chemistrymain3** [comment]
> This kind of defeats the whole purpose, doesn't it? if people are already playing non-matthew bandits.

No, it doesn't.

**Comment by Lutowski** [comment]
i'm personally in favour of this change
more people will be able to partake the bandit archetype without being shoehorned to 1 god

in a poly worshipping setting, characters should be able to pay respect to multiple deities for the every-day areas they govern over. praying to dendor that your shitty little houseplants will pull through, abyssor for that lucky catch -- this enables variety without stepping on the original concept's toes

**Comment by radarseas** [comment]
can you ensure that Iconoclasts are **_ALWAYS_** Matthiosians, since they're quite-literally from the eccentrical sect of matthios according to their descriptor.

these should be the only bandits that are always Matthios worshippers directly, since they enforce his will and guide them to theft. (that and the transaction is their entire gimmic, they really don't need dendor's kneestinger immunity or that)

**Comment by chemistrymain3** [comment]
> I'm in favor with this, with a single caveat for the sake of Bandit lore.
> 
> could you make it so its ensured that Iconoclasts are **_ALWAYS_** Matthiosians, since they're quite-literally from the eccentrical sect dedicated to Matthios according to their descriptor.
> 
> these should be the only bandits that are always Matthios worshippers directly, since they enforce his will and guide them to theft from the rich, giving to the worthless (themselves).
> 
> (that and outside of RP, the transaction is their entire gimmic that they're built around fighting with, they really don't need dendor's kneestinger immunity or that with super strength + wrestling + unarmed + fullplate + transaction healing + passive regen devotion.)

Let me double check to see they're set to it.

**Comment by bearrrrrrrr** [comment]
-2

**Comment by mopcat** [comment]
bad change. you can literally just... roleplay worshipping multiple gods? i don't see why this is necessary and all this will lead to is incoherent characters playing bandits as astrata worshippers or w/e. this is a roleplaying game. you can roleplay around mechanical restrictions rather than breaking the mechanical restrictions over your knee because you cannot handle being limited.

**Comment by Lutowski** [comment]
think it's fine with iconoclasty being exclusively matthiosian, this change shouldn't rly impact existing characters other than opening up opportunities for new ones

**Comment by chemistrymain3** [comment]
> bad change. you can literally just... roleplay worshipping multiple gods? i don't see why this is necessary and all this will lead to is incoherent characters playing bandits as astrata worshippers or w/e. this is a roleplaying game. you can roleplay around mechanical restrictions rather than breaking the mechanical restrictions over your knee because you cannot handle being limited.
> 
> edit: not to mention that it really doesn't make much sense for say, an astratan or a psydonian to be sacrificing explicitly to matthios. it'd require some serious skill to roleplay that well that i do not trust most people to have, unfortunately.

Don't care.

**Comment by YakumoChen** [comment]
Do casual matthiosian worshipers still recognise non-Matthisoian freemen?

I play a character often as a Smith whose whole sthick is selling cheap to Matthis and bandits and this kinda treads on it if I'm not gonna be able to examine most bandits anymore

**Comment by radarseas** [comment]
> Do casual matthiosian worshipers still recognise non-Matthisoian freemen?
> 
> I play a character often as a Smith whose whole sthick is selling cheap to Matthis and bandits and this kinda treads on it if I'm not gonna be able to examine most bandits anymore

`trait_commie`, aka blessing of matthios is given by the antag status itself, you will be able to see them on examine (they also need it for their scomstones anyway)

**Pull request merged**
