### PR TITLE
Town and Manor mapping update + Tailor job

### PR DESCRIPTION
**Pull request by Kyogon**
## About The Pull Request

Luto and I have been working quite hard on these map changes, but they are finally here!

Adds a new tailor shop to replace the one that was lost with the introduction of artificer.
Also adds a yeomen role to run that shop, a dedicated tailor. As of now, it only has one role spawner, but if we expand the living quarters of the shop in the future, we can accommodate a second.
image
image

It takes the location of the old merchant shop. The merchant shop has been relocated south of the steward's, in a new merchant's square fit with multiple stalls.
image
image

image
The 2nd peddler connected to the merchant's building contains the keys for the three stalls, ready for purchasing from round beginning.

The Artificer's Guild basement has also been given a door to the greatforge chamber. Both doors are uniquely locked by each side's own key ID, so you don't have to worry about the other job wandering into your workspace.
image

Finally, we arrive at the manor. As requested, the place has received numerous SCOMs in rooms that had none. However, the one nearest to the vault is at the south of the basement chamber, to avoid instant reporting of vault robberies. The sheriff/councilor section has also had it's locks turned on, so there is not an open path to the main courtroom at round start.

The servant's section of the manor has been tuned slightly, and they have received a garden with a well right outside the kitchen. The gates and doors are attached to the manor key ID, to stop any random towner in the keep from stepping on your crops.
image

The Heirs' rooms have received an overhaul, now sharing a lobby room and balcony, but generally being more fitting than the previous broom closets for the upcoming rulers. The Monarch's apartment has also been updated and expanded slightly, and it now also contains a balcony.
image

The previous Heir Apartment on the west end of the manor has been given as a hand-me-down to the Head Butler as their quarters.

### Changelog
Removed hoe and composter from servant garden.
Added one more table to servant kitchen.

## Why It's Good For The Game

The map changes are general QoL changes, as the current iteration of the keep is.. to put it lightly, rather shabby. This is step one to making it a proper holding, with more planned changes on the way.
Since removing the previous tailor shop, we held a vote on discord, and it had a whopping 88% of the votes wishing for the shop back. 
image
We also had requests to add a proper yeomen tailor role, and with population on the rise, we decided this was a good time to bring it into the fold  (the code existed but was vastly outdated compared to current jobs, and the seamster towner class was the closest anyone could get to that job.)
The merchant being moved was to divide the town into the crafter's section, and the merchant's section, and with it now being a proper merchant square, the moving process was (hopefully) painless.

### Credits
Without Luto, this update would not have been possible. Give them some props for the work on the town changes, including the peddler that will have the keys stocked instantly for the stalls.
I handled the keep part of the update, as well as the Tailor job.

### CODE REVIEW

**Comment by CosmicLAER** [comment]
I LOVE THIS SO MUCH AHHHHH

Two questions;

- The new merchant's seems to be where the public townhouse is, is that removed in lieu of the update?
- Is the well at the front of the Manor still in place (the one that's next to the lobby doors) as you added one to the kitchen's new garden area or was that particular one moved to the area addition?

**Comment by Kavrick** [comment]
Lots of this stuff looks good, but the manor should not have it's own farm because it encourages not interacting with soilsons when there's a vomitorium right there. Game design usually should promote interaction and not self sufficiency. 

Also putting the millstone right there is terrible for cooking, it's in the way. I'm the person who originally mapped the kitchen and the layout was very intentional.

**Comment by Kyogon** [comment]
Whether or not adding a garden for servants is seen as a good thing, the fact of the matter is that servant's *already* did grow some of their own things in the keep. Aside from removing any growable patches of dirt, there was nothing we could do that would stop them from having a garden. At least this way, we have the ability to somewhat control the size of it more and keep it from being in plain view of anyone entering the keep.

I will however remove the hoe and composter to make it less of a give.

I spoke to people who actually did use the kitchen, and the consensus on the tablespace was that it was not nearly as needed as a bit more open space in the room was. I had only removed one table, and Ill add back a table to compensate, but otherwise the expanded area was made by shifting walls around.

**Comment by Kyogon** [comment]
> I LOVE THIS SO MUCH AHHHHH
> 
> Two questions;
> 
> * The new merchant's seems to be where the public townhouse is, is that removed in lieu of the update?
> * Is the well at the front of the Manor still in place (the one that's next to the lobby doors) as you added one to the kitchen's new garden area or was that particular one moved to the area addition?

The idea is that one of the two gardens (probably the one with the well) near the keep's gates would be replaced with a stables, so to prepare in advance I gave the servants a proper garden with a well.

**Pull request merged**
