### PR TITLE
Ports Spellbuying

### PR DESCRIPTION
**Pull request by WatermelonsEverywhere**
Ports https://github.com/Tree445/Hearthstone/pull/336
Magic-wielding roles now get Spellpoints when they join based on their Arcane skill (1 level, 1 point) and any job or age related spellpoint bonuses which they can use to customize their spell loadout, also adds various new spells and a loot item that can be placed in dungeons to grant spellpoints.

A few different spells now give XP based on their fatigue cost, so one could level up their Arcane skill mid-game but it is quite slow, spamming trying to spam spells non-stop while using mana potions and sleeping usually took around 20 minutes in local tests for a Mage Adventurer.

FORCEWALL:
Puts up a 3x1 magical wall that the caster can pass freely through, centered on their position when cast. Not very durable, (a MAA with a cudgel broke a wall in three hits) and lasts 20 seconds.

ENSNARE:
A 3x3 square of warning tendrils spawns on the targeted location, and after a brief delay it immobilizes anyone caught inside for a short time.

MESSAGE:
Send out a message to anyone whom you know the name of, the target cannot answer back without casting their own Message spell.

REPULSE:
Throws everything including people in a 3x3 area around the caster, turning them prone and making them drop held items, watch for your allies.

BLADE BURST:
A 1x1 square spawns on the targeted tile, and after a short delay it deals 40 damage to whomever is still standing on that tile. 

NONDETECTION:
Blow a handful of ash onto a target to render them immune to scrying abilities for an hour.

KNOCK:
Force open all adjacent doors, openable windows, and most containers.

HASTE:
Enhance a target with +3 Speed for 1 minute.

FEATHERFALL:
Imbue yourself and all adjacent creatures with 1 minute of fall damage resistance.

DARKVISION:
Touch a target to grant them enhanced vision in darkness for 10 minutes, 2 minute cooldown.

### DETAILS
- Heartfelt Magos

Spawns with Greater Fireball

Total Spellpoints: 		8
Total Spellpoints (Old):	10

- Mage Adventurer

Total Spellpoints: 		4
Total Spellpoints (Old):	6

- Court Magician

Spawns with Greater Fireball

Total Spellpoints: 		8
Total Spellpoints (Old):	10

- Mage Apprentice

They spawn with Lighting Bolt by default, to reflect some "teaching".

Total Spellpoints: 		3

- Archivist

Total Spellpoints: 		2-3

SPELL CATALOG:
| SPELL| COST|
|--------|--------|
| Fireball| 2|
| Bolt of Lightning| 2|
| Fetch| 1|
| Spitfire| 2|
| Forcewall| 2| 
| Ensnare| 1| 
| Message| 2| 
| Repulse| 2| 
| Blade Burst| 1| 
| Nondetection| 1| 
| Knock| 1| 
| Haste| 2| 
| Featherfall| 1| 
| Darkvision| 2|

### CODE REVIEW

**Comment by WatermelonsEverywhere** [comment]
Technically it's ready, I'd just like to know if there's any notable changes that should be made to the spells or costs staff would like to see

**Comment by WatermelonsEverywhere** [comment]
nevermind on the being ready there's a few spells I want to switch around and change their behavior so this will be a draft still

**Comment by Mannybrado** [comment]
Repulse, Force Wall, and Bolt of Lightning should probably cost 2 as they're pretty powerful compared to the other ones.
Message should also probably cost 2, as being able to send messages to basically anyone from anywhere on the map is insanely powerful. If it was only people in your view I could see it being 1, but... y'know.
Long Jump should be 3. The ZJUMP trait is equivalent to setting your climbing skill to legendary and also letting you climb air. With this, you could get into basically anywhere or escape from basically any situation instantly, making it pretty much the best utility spell.

**Comment by WatermelonsEverywhere** [comment]
Yeah a lot of these new spells are undergoing some work to make them closer
to DND spells instead and there won't be a Z-JUMP spell anymore

**Comment by WatermelonsEverywhere** [comment]
more spells added, some tweaked slightly in cost or behavior

**Comment by bearrrrrrrr** [comment]
ooooooooooooooooooooooooo

**Comment by NikolayByondPlayer** [comment]
Really good PR, please merge

**Pull request merged**
