### PR TITLE
Vampire Changes

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**
Removes no fatigue from vampires.

Transfix now needs you to Say something. Each use of the transfix spell makes the target drowsier. Upon 3 consecutive uses, they will fall asleep.

Bat and mist form now consume 2500 vitae per use.

### CODE REVIEW

**Comment by Mannybrado** [comment]
2500 for bat form is kind of insane. Should make it like 750.

You get 900 vitae from one person if you drink them dry in one go.

**Comment by EvenInDeathIStillServe** [comment]
> 2500 for bat form is kind of insane. Should make it like 750.
> 
> You get 900 vitae from one person if you drink them dry in one go.

I've tested draining NPC bums and got 3000 vitae from them.

**Comment by Mannybrado** [comment]
Oh... wtf

**Comment by coffeecoffeecoffee** [comment]
> 2500 for bat form is kind of insane. Should make it like 750.
> 
> You get 900 vitae from one person if you drink them dry in one go.

Yeah you get about 3000 vitae if you suck a person totally dry. IIRC it requires about 10,000 vitae to upgrade your vampire level, so using your bat form will set you back about 1/4th of your progress, a meaningful but not insane snackrifice.

**Comment by EvenInDeathIStillServe** [comment]
Decreased the chargetime on the mass transfix from 30 to 10, because otherwise people will end up just shrugging off the drowsiness by the time it's off cooldown.

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Loving the Transfix changes. This is a good step towards VL being not just diet-maniac lmao

**Pull request merged**
