### PR TITLE
Teensy Mageventurer Buff

### PR DESCRIPTION
**Pull request by funnymansaxo**
## About The Pull Request

Removes the END malus from mages, and increases their knives skill.

## Why It's Good For The Game

Mage spells, as they are now, are terrible at ending fights. This leads to mage players having very little option (unless the enemy somehow goofs extinguishing themselves) for defeating a foe, and exhausting themselves then dying. More stamina, better weapon skills.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
ehhhh mages are already pretty strong rn, not sure if buffin em is the move

> Mage spells, as they are now, are terrible at ending fights.

this is balanced by the fact that mages are fantastic in group fights and are also really good at staying safe in group fights. 1v1 they have trouble ending fights, as they should, because getting owned by someone you can't get into melee range of and who doesn't stop casting spells Does Not Feel Good

**Comment by Ollanius** [comment]
Removing the END malus would be nice, since _(as far as I recall)_ stamina is integral for casting spells. Combine that with the fact that stamina drains from multiple other sources, and it'd be easy why it might be a bit unfun to play.

I would suggest removing the skills they get in Swords and/or Bows, in exchange, in order to better promote the mindset that mages should stick to their spells, their staves, and - in the worst-case-scenario - a good ol' fashioned shiv.

Having a Journeyman-level skill in Knives seems fair enough, especially when you consider how mages are already weak _(compared to your average Town-or-Drifter role)_ and are often unable to wear any armor.

**Comment by Ephemeralis** [comment]
They already have polearms 2 - why do they need knives 3?

**Comment by radarseas** [comment]
I'd swap their knives (**80% armor peirce steel dagger looking at you**) for polearm journeyman stat if anything, these guys are too weak to actually hold spears and that anyway. especally if they get hungry, compared to classes designed for fighting with such. if you have to, maybe extra endurance and a bit less strength.

They could honestly use a leather vest instead of a shirt under those robes, same as monks, they die too easily to wolves and that especally without literally any starting armor, not even a tiny bit of chest armor.

**Comment by bearrrrrrrr** [comment]
> I'd swap their knives (**80% armor piercing pick intent steel dagger into repulse at the neck looking at you**) for polearm journeyman stat if anything, these guys are usually too weak to actually hold spears and that anyway. especally if they get hungry, compared to classes designed for fighting with such.
> 
> They could honestly use a leather vest instead of a shirt under those robes, same as monks, they die too easily to wolves and that especally without literally any starting armor (minus the trousers), not even a tiny bit of chest armor.

LOL no we do not need mages running around w/ the same polearm skills as combat classes. and yes, they _can_ use certain spears

this is getting into pretty wild powercreep territory, not rly a fan of this. i can justify these buffs on rogue mage but this is not good

**Comment by bearrrrrrrr** [comment]
> mages _are_ combat classes. they're also adventurers, which follow the typical ruling of 3 + gimmick/+1 skill. Mages having casting as a gimmick.
> 
> Mages, of all kinds, _kind_ of suck. "burger you bimbo, fireball" sure, if the court mage with a pumped up arcane casts even normal fireball it'll fuck shit up, and CM with greater can horizonal an entire lich contingent with one button, but they're kind of an outlier and have a fat cooldown besides. Bring armor into the mix and lesser fireball bounces.

i meant melee combat class

again, mages are crazy in group fights, idk, i dont think buff is terribly needed

**Comment by funnymansaxo** [comment]
seen the comments- don't have the know-how to edit my own PR and am kinda doing IRL stuff right now. going to close this and come back to it later

**Pull request closed without merging**
