### PR TITLE
Give Acolytes regen, remove blood heal from lesser miracle

### PR DESCRIPTION
**Pull request by Kavrick**
Talked about this in the discord to make sure I got opinions and stuff. Right now, cleric is just straight up a better acolyte, and after discussion I thought it'd be better to buff acolytes rather than nerf priests. This PR should make it so acolytes both regen devotion naturally like the priest and no longer have to pray-grind to get their miracles. Mostly QoL, partially a buff with how it lets acolytes do other things while getting their devotion rather than pray-spamming.

Also, removes blood-heal from lesser miracle, that was always pretty overkill. After talking to people, feels like people didn't even know that lesser miracle restored blood in the first place. Still heals oxyloss and everything else.

On a side note, I also removed polearms from priest and gave them some utility skills to help them around the church when there are no acolytes.

Tested locally.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
> On a side note, I also removed polearms from priest and gave them some utility skills to help them around the church when there are no acolytes.

The reason the Priest has polearms is a ceremonial thing- a spear is Astrata's holy weapon.

**Comment by Kavrick** [comment]
Added back polearms @bearrrrrrrr

**Comment by ChungusGamer666** [comment]
passive devotion gain was really supposed to be a priest exclusive because spells are op bullshit anyways but sitting around and praying is ass, devotion is a shit mechanic, and clerics shouldnt be objectively better

so i am ambivalent about this

**Comment by Kavrick** [comment]
> passive devotion gain was really supposed to be a priest exclusive because spells are op bullshit anyways but sitting around and praying is ass, devotion is a shit mechanic, and clerics shouldnt be objectively better
> 
> so i am ambivalent about this

I kinda agree, I just wanted to give people a reason to play acolyte over everyone just playing cleric without just deleting cleric. Praying isn't a particularly fun mechanic, sitting down and doing nothing isn't particularly interesting. I wish there was a better fix but this is just a bandaid for now until someone reworks devotion.

**Pull request merged**
