### PR TITLE
Buffs to Ritual Silver Daggers, making them no longer snap broken when used.

### PR DESCRIPTION
**Pull request by Joel-682**
## About The Pull Request
Expanding further upon the great work done in #473 this PR makes it so that Silver Daggers don't snap while making ritual circles with them, but rather just consume the manna powder, I've updated the flavor text when carving a rune to reflect this.

## Why It's Good For The Game

This makes it so that silver daggers are worth the hassle.

### CODE REVIEW

**Comment by Mikierpg** [comment]
Magic was never intended for non-magic characters. Spell books added in (at first 1%) the ability to get arcane skill without being a magic job. Then it got buffed all the way to 15%. This is just strength creep for people that aren't supposed to have spells in the first place.
A low success rate for someone solo-bumbling through it is quite fine.
If your character *really* wants to learn magic, then they always have the option of getting a mentor/tutor who can make a book for them, and give them access to read it.

**Comment by Ephemeralis** [comment]
The general intent was to make them *possible* but not reliably probable. Even 1 level of arcane magic adds a lot to characters (a knight with repulse can probably reliably win every single 1v1 they start) and I hold grave fears that making it consistent will just cause an arms race to rush arcyne tomes for combat-inclined classes.

**Comment by Joel-682** [comment]
> Magic was never intended for non-magic characters. Spell books added in (at first 1%) the ability to get arcane skill without being a magic job. Then it got buffed all the way to 15%. This is just strength creep for people that aren't supposed to have spells in the first place. A low success rate for someone solo-bumbling through it is quite fine. 

No, it was not "buffed to a %15", that's if you only found +10 magic stones with the perfect secondary trait, that usually just doesn't happen. In my experience, I've spent four hours total testing the changes on #506 and haven't had any success at all. Furthermore, I'd like to remind you this is the CHANCE TO MAKE THE TOME. This is NOT a 75% to GET AN ARCYNE POINT. Your chances to get an arcyne point are still AT MOST swampweed bonus + silver dagger rune + rock magic bonus (not multiplied by 5, unlike the chances to make the book)

> If your character _really_ wants to learn magic, then they always have the option of getting a mentor/tutor who can make a book for them, and give them access to read it.

Agree! Sadly, it was made so books you yourself made have a bonus and whenever you yourself made them. And for some reason, when I try to get a teacher of the arcyne, getting hit with a BRAND NEW tome gets me this message if I'm a non-arcyne character. 
image

**Comment by Joel-682** [comment]
> IMO if you /really/ wanted to give non-magic classes an easier way to learn magic it should be through the court mage - way more interesting to encourage players to interact and roleplay with the town's dedicated wizard than to simply make their own tome and grind out skills on their own without any interaction with other players needed.

Yeah, same, I'm just not experienced enough to actually make a change like that, so I'm trying to do what I can with what I know. 

I'm glad removing/lowering the multiplier chance (Though, again, this is for MAKING the tome, NOT actually getting an arcyne point, getting an arcyne point as a non-arcyne character is STILL as debuffed in #506, I can't stress this enough).

**Comment by Joel-682** [comment]
> The general intent was to make them _possible_ but not reliably probable. Even 1 level of arcane magic adds a lot to characters (a knight with repulse can probably reliably win every single 1v1 they start) and I hold grave fears that making it consistent will just cause an arms race to rush arcyne tomes for combat-inclined classes.

I would hope not, the only reliable way to get magical stones is by getting normal stones, so unless fighting classes start rushing mining, I don't think this will be "rushed."

If it is, the modifier can be lowered/reverted, it's just a number change.

**Comment by Joel-682** [comment]
Alright, I've removed the buff to arcyne tome crafting due to popular request, but I still think that the silver dagger changes are good.

**Comment by Ephemeralis** [comment]
The silver dagger changes are fine, yeah. Not really sure why that one was eating the dagger when it was probably supposed to eat the powder instead.

**Comment by Joel-682** [comment]
It also had me bewildered, I tried to reach maacha about _(their expired car warranty)_ the reason why and they didn't answer so I'm just going out on a limb and doing this as a change, because silver daggers for rituals are VERY COOL but they currently are really bad to use.

**Comment by radarseas** [comment]
this is good a change honestly, the chances to learn from another's book is already 1% unless you make it yourself (which is far, too insanely low).

we really don't need to spend 10+ silver ingots to maybe, possibly, somehow manage to get enough.... luck... just cast fetch.. at most after 2-3 hours..

**Comment by Joel-682** [comment]
Oh Radarseas, this PR was heavily altered, beforehand it also included a buff to making an arcyne tome with magic stones as a non-arcyne user, making it so you'd have at most a 75% of MAKING the tome, and at least a 5% chance. It's been scrapped due to popular demand.

**Comment by Joel-682** [comment]
@EvenInDeathIStillServe Could I get a review on this PR pretty please with a cherry on top?

**Pull request merged**
