### PR TITLE
Buffs Swords and Axes a little bit.

### PR DESCRIPTION
**Pull request by HeroWithYay**
## About The Pull Request

Increases the armor penetration of axes when cutting from 10 --> 20
Increases the ~~armor penetration of axes when chopping from 20 --> 50~~ (This attack has long swing delay.)
Increases the armor penetration of the battleaxe when cutting from 15 --> 25

Increases the one-handed force of the steel sword and it's children from 18 --> 22. The two-handed force remains unchanged.
Increases the damage factor of cutting with swords from 1.0 --> 1.1
Increases the ~~armor penetration of swords when chopping from 10 --> 50~~ (This attack also has a long swing delay and 0.8 damage mod)

EDITS:
Axe chop to 35
Battleaxe chop to 40
Sword chop to 30 but removes its damage malus. Making it deal normal damage instead of 0.8 damage.

## Why It's Good For The Game

Swords and axes are some of the least whelming weapons in the game right now.
I believe none of these buffs particularly change the status quo of what the best strategies in the game are right now.
I will explain the reasoning behind each.

CHOPPING for both swords and axes has had it's armor penetration increased from a pitifully small number, to a more reasonable number for an attack with swing delay. This was not increased all the way to 80 to match PICK and SMASH, as those numbers, especially in the case of PICK might already be overtuned. This change is especially needed in the case of swords, as the CHOP on a sword had both a damage nerf /and/ lower armor penetration than the sword's usual STAB ability, making the attack almost completely redundant.

The gap between the one-handed and two-handed force of the basic swords has been lessened, to make pairing it with a shield in the offhand a more viable strategy, as well as make it not literally hit weaker than a one-handed dagger with EVEN LESS armor penetration and speed. It now has 2 points more than a dagger... and still has less armor penetration and speed.

CUTTING with the sword has been given a 1.1 damage factor. This might be foolish, but it gives the player a reason to actually swap to CUT once in a while, considering CUT has no armor penetration to speak of.

Meanwhile the armor penetration of CUTTING with axes has been increased to 20 for normal axes and 25 for the battleaxe. Axes are specialized in CUTTING and it doesn't make sense for them to have less armor penetration than the stab of a sword. I would actually like to increase these numbers to more in the 30/35 range. But I don't want to get too crazy with it.

Please feel free to tell me if I'm a big dumb idiot. The main argument I can see against these changes is to keep these weapons weak intentionally since they're quite common. But I feel that since players actually ENJOY using swords and axes, having them be more valid weapons to use is more important.

### CODE REVIEW

**Comment by HeroWithYay** [comment]
If this is fine, I'll also use this as a baseline to make some changes to maces and flails.

**Comment by Kavrick** [comment]
> If this is fine, I'll might also use this as a baseline to make some changes to maces and flails. At the very least flails.

I already nerfed maces and flails, keep that in mind.

The main issue with swords is that they'd be a lot better if that they'd be _the_ defensive weapon. But it's super easy to get 90% parry chance even on non-defensive weapons. Personally flails could be fixed if you made it so their smash intent only showed up when you two-hand the weapon. Flails can be paired with a kite shield in an incredibly strong combo.

**Comment by HeroWithYay** [comment]
> > If this is fine, I'll might also use this as a baseline to make some changes to maces and flails. At the very least flails.
> 
> I already nerfed maces and flails, keep that in mind.


I actually wanted to make flails specifically a little bit better Overall. Looking at maces I've decided they're basically fine so I'm not gonna touch them
Flails have 5 armor penetration on their basic attack. This puts them solidly at the "Worst weapon in the entire game" ballpark.
While they do have that juicy 80% armor on their Wind up attack that now ALSO has swing delay. It's an unwieldy, unfun and unusable gimmick. I plan to remove the swing delay so that it's just a charge-move and nerf the armor penetratation to acceptable levels. Likely 30%..

**Comment by HeroWithYay** [comment]
>  Personally flails could be fixed if you made it so their smash intent only showed up when you two-hand the weapon.

I very much disagree with this. Two-handed flails are a completely different type of weapon that looks more like a polearm. You cannot even two-hand a normal flail and for good reason

**Comment by Kavrick** [comment]
> I very much disagree with this. Two-handed flails are a completely different type of weapon that looks more like a polearm. You cannot even two-hand a flail in-game right now and for good reason
> 
> Our flails are one-handed flails.

Uhhh... I hope you realize that flails aren't real.

**Comment by bearrrrrrrr** [comment]
mmm, i dunno about the 50 pen for chopping; that is _**pretty high.**_ i'd make it something more modest, at least below 40; that's where stuff starts to become specialized armor-defeating options

otherwise eh? seems fine. axes in particular kinda suck rn so this can't make it any worse LOL

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Agreed with the 50 pen. I'd say more like 35 or 40. Otherwise looks fine.

**Comment by HeroWithYay** [comment]
Alright, gonna lower those numbers a bit and assume that the 80 armor pen on some identical moves are NOT something we plan to keep.

**Comment by HeroWithYay** [comment]
I had chosen 50 with the existence of weapons that had 80 in mind.

**Comment by HeroWithYay** [comment]
> Uhhh... I hope you realize that flails aren't real.

Whether they were used in real life battle or not (which is debatable). The concept of a flail exists in games, movies and all sorts of other media.

And if you think about /that/ flail, which is the one we have. ...the concept of two-handing it seems a little silly considering you'd basically be swinging it like a helicopter dick or above your head like you're readying up for a swing in baseball.

It would certainly be more difficult.

**Comment by HeroWithYay** [comment]
> The ones with 80 is specifically maces as a hat, and it's in their two handed mode besides. You could lower that down to 50, but don't base others off them. . .

Daggers also have 80.
But I am MORE than happy to change those things as well
I'll put up a PR for the weapons getting nerfed, we can talk about those and then maybe everything will be swell, yeah?

**Comment by HeroWithYay** [comment]
>I'll put up a seperate PR for the weapons getting nerfed, we can talk about those and then maybe everything will be swell, yeah?

Kavrick says they plan to rework armor and change those weapons at the same time, very soon. So I will refrain from this.

**Comment by HeroWithYay** [comment]
Axe chop to 35
Battleaxe chop to 40

Sword chop to 30 and removes its damage malus. Making it deal normal damage instead of 0.8 damage.

**Pull request merged**
