### PR TITLE
reverts RG buffs

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request
Since the RG buff was merged, we have had:

- roughly 5 individual instances royal guards running off into the forest in a death ball over multiple rounds
- 2 royal guards jumping the gun on escalation to secure kills/takedowns
- ~3 instances of borderline/confirmed metagaming to get an antag
- a bunch of small valid-hunting things

**I DON'T THINK IT'S BEEN MORE THAN 48 HOURS**

royal guard having the highest stats and skills and social status and armor creates extremely poor behavior due to the wild power discrepancy. reverts the buff. 

also appropriately bonks the warr class' stats

## Why It's Good For The Game

game design being good is good. I have done my due diligence in letting it play out. The results have been pretty apparent.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
> the idea that 1 extra point of endurance and constitution is enough to bring about a complete shift in player behavior and cause all royal guards to suddenly lose their minds and start breaking rules left and right is both hilarious and delusional

>me when i literally don't know wtf i'm talking about

**Comment by Jul-Jul** [comment]
I know thus may come across weirdly. Though this sounds more like a OOC RP/Player quality issue that should be combated by staff action... not something that should require a PR. As just a debuff wouldn't stop people causing issues, they'll just find another way to be an issue.

**Comment by Lutowski** [comment]
Should enforce QC bans especially if these incidents are (likely) from freshly whitelisted players. Holding off on any verdict until I'm sure it is or isn't isolated events.

**Comment by Ollanius** [comment]
> fine with this sitting a bit to see if it was just a 2 day fluke but i doubt it tbh. we'll see

Well, I think the issue is that these statistics - while relevant to combat - aren't the main contributor to these incidents.

A member of the Royal Guard spawns with the best weapons you can feasibly acquire _(like the Battle Axe and Estoc)_, a full set of steel plate armor, free access to a well-stocked fortress with a personal armory and pantry, _and_ the legal authority to essentially kill anyone they don't like. This makes it a honeypot for people who want to 'win the game' at any cost, so-to-speak.

I'm confident in saying that these incidents would've occurred all-the-same, regardless of whether the buff _(which gave them an extra point each in CONSTITUTION and ENDURANCE)_ was passed or not. Outside of removing the very benefits that differentiate them from the Men-At-Arms, solving this issue cannot simply be done through mechanical input alone.

Rather, it is something that can only be solved through cultivation. Administrators should be more stringent on jobbanning those who flagrantly abuse the position _(without flagging those who had the circumstantial greenlight to do so)_. Players should also be made aware that if they want to roam the forests and hunt baddies, they can do so without consequence as a Warden or a member of the Men-At-Arms.

**Comment by bearrrrrrrr** [comment]
so to clarify on my response to 'simply quality-control better'; i'd like any solutions that don't start with 'ban more people'. this is basically my issue LMAO

**Comment by Lutowski** [comment]
> so to clarify on my response to 'simply quality-control better'; i'd like any solutions that don't start with 'ban more people'. this is basically my issue LMAO

I just don't believe that moving numbers around is going to make bad RG players disappear overnight. Stats isn't the entire motivation on why roles are played, and in the wake of new players, you'll always have bad apples locked into security coded roles who are afforded privileges and prestige. These issues are nearly synonymous to default ss13 with over-escalation and validhunting. You'll have to reprimand those individuals as they come.

I'd instead be more open to raise PQ requirement so new players don't immediately jump into a high responsibility role.

**Comment by bearrrrrrrr** [comment]
hmm
yeah, PQ requirement may be the plan, actually

**Pull request closed without merging**
