### PR TITLE
Updated Lux Sprite

### PR DESCRIPTION
**Pull request by olirant**
## About The Pull Request

image
Updated slightly animated Lux sprite to better represent that it's made of soul-stuff.

## Why It's Good For The Game

More fitting tonally than the old out of place sprite.

### CODE REVIEW

**Comment by GeneralPantsuIsBadAtCoding** [comment]
This got a conflict with the produce.dmi, really wish I actually could resolve those on github but oh well.

**Comment by olirant** [comment]
> Owner

Really? I just checked with upstream and it doesnt seem like theres any updates to produce.dmi other than my lux to cause a conflict. If theres new produce files I can just update the lux on the new file easy-peasy later.

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Well the problem is more that while that conflicts there I can't merge, pfft.

**Comment by olirant** [comment]
Should be fixed, someone updated potatoes the same day i was updating lux, because lux is legally a vegetable. Should be fine now.

**Comment by GeneralPantsuIsBadAtCoding** [comment]
I love drinking Lux-beer.......

**Pull request merged**
