### PR TITLE
Completely removes all spells.

### PR DESCRIPTION
**Pull request by n3tis**
## About The Pull Request

Deletes EVERY Roguetown spell in existence.

## Why It's Good For The Game

Ah, the sweet, blissful silence of a world without spells and magic—where mages no longer prance about with their flashy incantations, and the battlefield is finally a place of fairness, equality, and good old-fashioned weaponry. Removing every single spell is not just a change; it's a revolution. It’s the dawn of a new era where true Ravoxian balance is restored, and everyone has an equal opportunity to bash each other's skulls in without the interference of those pesky, overpowered fireball spells.

Let’s be honest: spells are just a crutch for those who can’t handle the intricacies of actual robust combat. Why spend time learning how to land a hit with a sword or arc a bow when you can just click some scroll on yoru screen and vaporize your opponent from where they're standing? It’s laziness, pure and simple. By deleting all spells, we’re leveling the playing field. No more “strategic” spellcasting from behind cover and true combatants—now it’s just you, your weapon, and your ability to dodge or parry.

Remember that time when you were on the brink of victory, only for your opponent to pull out a giant fireball that reversed the entire fight? Or how about those pesky healing spells that drag out battles for hours? By removing these abominations, we’re not only making combat fairer, but we’re also speeding it up. A battle should be quick, brutal, and to the point—not an endless display of glowing effects and nonsense shouting.

With spells gone, we can finally focus on the true art of combat: melee. There’s something so pure, so satisfying about landing a critical hit with a well-placed mace bash to the head. It’s a dance—a beautiful, bloody ballet—that has been overshadowed by fireballs and lightning bolts for too long. By eliminating spells, we’re giving melee combat the spotlight it deserves. Players will rediscover the joy of a perfectly rolled parry or the thrill of an unexpected counterattack.

For too long, true Ravoxian warriors have been the laughingstock of Azure Peak and other places, outclassed by mages who can summon balls of fire and bolts of lighting out of their arse. But no more! With spells out of the picture, the warrior class will rise to its rightful place at the top of the food chain. Imagine a world where the most powerful character is not the one with the highest INT stat, but the one with the most grit and determination. Warriors will finally get the respect they deserve—because they’ll be the only ones left standing in seas of blood and bone.

Without spells, battles will no longer be about who can memorize the cheapest way to take down an opponent, but who can think on their feet. Strategy will reign supreme. You’ll have to consider positioning, terrain, and timing. Combat will be more about outsmarting your opponent than simply blasting them. Victory will taste that much sweeter when you know you earned it through skill, not "God-given" sorcery.

In Conclusion: A Better, Fairer World
Removing all spells is not just good for the game; it’s necessary. It’s a bold step toward a better, fairer world where combat is pure, untainted by the corruption of magic. In this brave new world, balance will be restored, and everyone will have an equal chance to meet their end by the sword, the bow, or the axe. It’s time to embrace the future—one without spells, but full of glorious, unadulterated combat.

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
Retvrn to normalcy

Break the cycle

**Comment by n3tis** [comment]
> Retvrn to normalcy
> 
> Break the cycle

Erase Your Light. Take Your Flight. To A Place Where You Will Be Remembered. To A Place Where You Will Be Loved.

**Comment by Stutternov** [comment]
image

**Comment by bearrrrrrrr** [comment]
they made medieval europe real this is so cool i can't wait to get ra bies

**Comment by n3tis** [comment]
> they made medieval europe real this is so cool i can't wait to get ra bies

Actually would be interesting if we got virology. I have never heard or seen anyone get any diseases in this game.

**Comment by bearrrrrrrr** [comment]
BOOO

**Pull request closed without merging**
