### PR TITLE
Guys, the Crab, Go get it - Bandit features [PT1]

### PR DESCRIPTION
**Pull request by Onutsio**
## About The Pull Request

This Capstones the first part of a large-scale project I've been slowly grinding into to make bandits not suck, and into an actually interesting antag.

This PR adds in a new item, the Covetous Crown. This is a item which is adminspawn, to test first,, and can be used to mount onto meisters to begin tapping the treasury. Stats:

Time to complete
NORMAL MODE - 1:30, roughly
Maximum drain per meister - 500 mammons(The two hidden meisters, the interior soilson and bathhouse, are 250. Future meisters can be edited this way too in map editor)
Drain per interval: 50

When drilled for its maximum of 500, a meister breaks. It can no longer be siphoned and the Crown pops off. It also leaves a nasty surprise for non-matthian NOBLE-traited people who try to use it. But otherwise works normally for everyone else.

This PR also changes the bandit camp. Adding some loot bags(sacks, and a backpack). It also replaces their torches with lampterns. putting them, at least on par for lighting, with the garrison. It additionally adds a well and a crate of food to their bunkhouse.

This PR also grants(or ups) the athletics of all bandits to 3. Some classes had none. This brings them on par with most other combat roles.

This PR also resprites the Blooded coin and reflavors it to be a bit less meta-able. Sprites of the Covetous Crown, meister states, and new Bandit SCOMstone by Zydras!

[Video Demonstration](https://www.youtube.com/watch?v=oU8MyFcuNY4)

Sprites
daring
spritesbyzyda

## Why It's Good For The Game
Bandits now have a way to directly interact with the town that is far less likely to lead to their direct deaths than directly sieging the vault or church. Or robbing 4-mammon carrying adventurers for their pants. This also further drives the Matthian bandits into conflict with the *Nobles*, their BLUEBLOODED target of ire, rather than their only source of safe income being robbing broke ass peons in the woods. Having checked, there should still be no meisters that are 'free robberies'. They will take effort, planning, intrigue.

Bandit map changes are needed as bandits have no way to feed themselves, and I am starting to feel bad robbing the warden's tower for food every round. Loot sacks to work in accord with the new Coveter, and lampterns to put their visibility on par.

If this works out, look forward to Phase 2! Making the idol not boring

### CODE REVIEW

**Comment by Raze500** [comment]
It's a good change honestly, beacuse atleast now with this the bandits can have the option to do an objective and planning to siege the town, i can image a good interaction about this, nice work.

**Comment by bearrrrrrrr** [comment]
hmm

burger's got a point insofar as that it being so freely accessible and repeatable is probably not fantastic but i'm not too sure how to fix that

i'd like it if it was admin-only spawn rn tbh while we look at how it affects gameplay

**Comment by Onutsio** [comment]
Will change map, keep admin spawn when home

**Comment by Onutsio** [comment]
Scratch that. Did some digging. These are all the town meisters I could find. I'm pretty sure there are MORE in the keep, but It's also the Keep. So I don't care to look for 'very easily robbery targets' meisters there. I have set the mammon siphon cap to 250 for the one INSIDE the farm and the one in the bathhouse. As they are the only two that are not exposed.
townmeister11
townmeister10
townmeister9
townmeister8
townmeister7
townmeister6
townmeister5
townmeister4
townmeister3
townmeister2
townmeister1

**Comment by Onutsio** [comment]
Admin logging, no more arm breaks, and steward logging added. Also, some notes for balancejaks later down the line to easily see what's doing what.

**Comment by Onutsio** [comment]
Silent running removed and HEDGE KNIGHT ARMS ARE NOW SAFE. I AM DONE FR(I HOPE)

**Comment by radarseas** [comment]
funnier idea, make broken meisers make non-nobles tax exempt to spite the nobility _**one bit more.**_

**Comment by Onutsio** [comment]
> funnier idea, make broken meisers tax exempt for everyone that can use them to spite the non-matthiosian nobility _**one bit more.**_

This is an incredible idea and I will come back to it later

**Comment by Jul-Jul** [comment]
I like the idea but like already mentioned, if there's lower pop or people... ya know RPing on a HRP server, just to be dragged away by bandits using their GMod DarkRP ATM cracker, I can see why people wouldn't be overly happy about it. Perhaps give it a cooldown between use or only a limited time use.

**Comment by bearrrrrrrr** [comment]
> > It also leaves a nasty surprise for non-matthian NOBLE-traited people who try to use it.
> > it's azure fucking PEAK.
> 
> Big fan of this. Current bandit gameplay loop is either rob some scrub for 4 mammon in the woods, which you could literally make in twenty seconds with the stockpile, or pick a fight with some town plate-juggernaut who probably doesn't even keep their cash on them. Aside from skimming valuables from a few unattended town areas there's not a lot to do, and robbing the vault isn't really fun RP it's just smacking a wall/some bars for 10 minutes hoping no one hears you, and if you get caught you get turned to mincemeat because the whole garrison is sitting in the court with their eyes glazing over.

MASK
MASK
MASK
MASK
MASK
MASK

**Comment by Onutsio** [comment]
Admin spawn only now. Also noticed that brigands don't have shield skill(they spawn with one), now they do.

**Comment by Onutsio** [comment]
> This is a cool idea but I sorta worry it may encourage bandits to just run around the town siphoning money from obscure Meister locations with no one around rather than actually interacting with and antagonizing other players. This is much less risky than robbing folks and has much higher rewards despite not even requiring you to actually interact with any other players in any capacity. In that sense, it's not exactly much more engaging than just silently breaking into the armory/vault and stealing everything - except it seems a lot easier to pull off.

There really aren't any obscure meisters. The one's that are most obscure, the soilson and bathhouse, are half value.

**Pull request merged**
