### PR TITLE
!! ARRETZ !! - Adds stone-decor alarms.

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

Hey, you. Tired of those PESKY THIEVES breaking into your steward and treasury? So are we! Introducing ~~ZIZO'S~~ PSYDON'S THIEF-SCREECHER SYSTEM!!

By stepping over the tile the alarm is on, the alarm will play a noise audible (through z-levels, hopefully) to all nearby, and scream its little lungs out! What a trooper!

## Why It's Good For The Game

Flavorful.

Stops places from being so easy to break into.

Currently in steward, treasury, armory. (Nobody breaks into the last one, but it's cool, anyway)

**THESE ARE NOT MEANT TO BE SPAMMED -** they purposely have no easy ways to bypass them such as sneaking or lockpicking due to the fact they are meant to only be used in **extremely round-important areas.** Anti-magic stops them since they need **some** way to be bypassed, but I doubt this will ever come up. May make a version that lets you sneak/lockpick/etc, later.

Hedge knights can bypass these. This is intentional. If you sneak a hedge-knight into the treasury tunnel, you deserve this.

gif of the alarm - be patient, it is indeed a gif. 
wahh

### CODE REVIEW

**Comment by Mikierpg** [comment]
Kino. I would rather see HK not getting a bypass, and bandits instead having a general purchasable item that's like, a dedicated gag for the yapper? It would be visible and an obvious sign that someone has gone through, while also being more accessible to The Bads.

But also yeah, if a HK gets into the treasury without being noticed that's a little funny.

**Comment by bearrrrrrrr** [comment]
> Kino. I would rather see HK not getting a bypass, and bandits instead having a general purchasable item that's like, a dedicated gag for the yapper? It would be visible and an obvious sign that someone has gone through, while also being more accessible to The Bads.

Honestly, I fuck w/ this idea heavily- might even re-use the covetor for it??

**Comment by radarseas** [comment]
I like the idea of noble-blooded trait letting you bypass it, makes it not an entirely useless roll as a bandit, or rogue or whatever past tax evasion in the latter.

(the former just outs you to the royals for the court mage to spy on since nerve master sees job).

**Comment by bearrrrrrrr** [comment]
> I'd personally toggle-lock it to a key though, if you get the key for the area as a thief, you totally deserve to get in quietly instead of being screwed over by this.
> 
> being masked should **100% stop it logging you, regardless of account.** else this'll fuck over non antags doing a self-antag gimmic, vampires and werewolves if they for whatever reason want into these areas (especally the armory). Not because its gone off but because it'll give their true name away for scrying.

I may do this for less-important areas, but understand that stuff like the steward and treasury is literally a round-ending break-in for the keep if people get away with all of it. It is intentionally **extremely rigid.** It's still possible to go at it stealthily if you're determined, but very hard to.

**Comment by Ephemeralis** [comment]
Possibly consider adding noble-blooded stopping it, and also temporarily disabling it for like 30 seconds so people can indignantly capture nobility and hold them at knifepoint as they rifle through whatever.

**Comment by bearrrrrrrr** [comment]
> temporarily disabling it for like 30 seconds

👁️

**Comment by MaSvedish** [comment]
BEHOLD. THE SNITCH THROAT GOAT.

**Comment by Cleric2145** [comment]
Small thing, on examine, the alarm has no name and simply shows up as "This is ."

**Pull request merged**
