### PR TITLE
Fix | Removes Random Wall

### PR DESCRIPTION
**Pull request by MortoSasye**
## About The Pull Request

Removes a random wall near the church.

image
image

## Why It's Good For The Game

We don't like random walls.

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
it's peak

**Comment by Mannybrado** [comment]
soulless

**Comment by NikolayByondPlayer** [comment]
get this, you wall!

**Comment by Lutowski** [comment]
closing since https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/951 fixed it

**Pull request closed without merging**
