### PR TITLE
Quicksilver Poultice: A deconversion method for werewolves and lesser vampires.

### PR DESCRIPTION
**Pull request by PPooch**
## About The Pull Request

There had been a request for a way to de-convert antagonists, werewolves particularly, without admin intervention. I had an idea of a silver poultice, "quicksilver", that was an expensive and intensive RP-gathering solution to make the effort worth it. Here's the design steps and my reasons.

1) Foraging the materials.
The fyritius flower. I had wanted to make a special herb to encourage the go out and forage, but looking at the fyritius, it seemed like it did not have much going for it. You have to pluck a fyritius flower, and then (like using the confessional contract) hit it against a bleeding werewolf or vampire. This gets the aberrant blood on the flower bud, which then begins to rot quickly - 15 minutes before it turns to ash. (You can still put it in a chest like a normal food.) This is akin to the zombie cure Ambuzol from SS13 requiring zombie blood: this assures that the cure for the condition shall not be pre-empted without definitive contact with the antagonist.

The blessed water and the silver ingot also ideally pull from the church and the smithy, getting them involved.

2) Alchemy requirement: Involves the merchant or the physician/apothecary.

3) The actual application requires either the Inquisitor themselves or a character with Expert miracles - an acolyte, or the priest, or other clerics. It needs to be at a cross, like Anastasis. The Inquisitor can eke two doses out of this. Mostly to anoint both of his orthodoxists with the mapped in item they have in the inquisition chambers.

Completing the anointing gives a special trait. When anointed, both the werewolf bite infection and the vampire lord bite->suck blood will fail - denying both of those conversion methods. The inquisitor starts off with this trait.

If a werewolf or lesser vampire undergoes the procedure, they will burst into flame. If it completes, they will have the traces of their antagonist abilities removed as if they had not been infected in the first place. (Hopefully). They will also get the trait added to them, preventing further infections.

## Why It's Good For The Game

Everything here is open to balance and any necessary adjustments to get it merged of course. I thought that this would be a good starting point. It is expensive, requires a few different hands to make and use, and has a special cut-out for the Inquisition. Those were the three ideas I wanted to go for with the idea.

Would be cool if someone could whip up a better sprite for the poultice, since it is just my dev sprite for now.

https://github.com/user-attachments/assets/83de621e-7fec-4813-a140-1d1723e3649c

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
ouh, neat.

immediate concern is that some lesser vamps may just use this as an easy out to surrender despite the fact they're supposed to be loyal IC'ly, butt this is mostly just me talking to myself

v awesome, tysm :3

**Comment by PPooch** [comment]
I will give the elder / roundstart werewolf immunity, sounds good

**Comment by radarseas** [comment]
I'd give people an option to resist immunity/forced deconversion, for those that want to bare with the consequences to staying accursed, especally for those that signed up purposefully as lesser vamps.

**Comment by PPooch** [comment]
Could put in an option to resist. My thinking was, since the process is painful, the people who go through with it are either 1) ICly/OOCly cooperating, or 2) they're at the complete mercy of whoever is applying it. In the case of 2, what is the next step if someone resists? I think the natural thing would be round removal / execution. So it could "skip the guilt" of someone having to escalate round removal and have rejection cause a lethal amount of damage, as an option. But putting in the delay wait-until for the victim to select YES/NO wouldn't be too difficult.

**Pull request merged**
