### PR TITLE
liquidswordz - adds new sprites for rapiers and a new greatsword subtype, the estoc

### PR DESCRIPTION
**Pull request by kittysmooch**
## About The Pull Request

Liquidswords1995

image

the first thing this PR does is overhaul rapiers a bit. i thought their old sprites looked more like chopping weapons, so i gave them fancy NEW sprites that look like this:

image
image
image

they get new descriptions, too.

<details>
<summary>for the rapier:</summary>
"A duelist's weapon derived from western battlefield instruments, it features a tapered blade with a specialized stabbing tip."
</details>

<details>
<summary>for the decorated rapier:</summary>
"A fine duelist's instrument with a tapered thrusting blade. Its hilt is gilt in gold and inlaid, and its blade bears twin inscriptions on either side. One reads, 'CAST IN THE NAME OF GODS' while the obverse reads, 'YE NOT GUILTY'."
</details>

<details>
<summary>for the lord's rapier:</summary>
"A royal heirloom whose spiraling basket hilt is inlaid with fine cut gems. It bears the burnish of time, where once sharply defined features have been worn down by so many hands. An old rumor ties this implement to the siege that smashed the Mad Duke's keep to rubble, and burnt the Duke himself to cinders."
</details>

aside from the description and the sprites, nothing changes about these.

now, for the estoc:
image

the estoc is a thrusting-oriented sidegrade to the greatsword and zweihanders, which trades up front damage (worse against nakkie people) for armor penetration (better against armored people). for this it gets some bespoke intents based on similar intents from other weapons, mixing some of the strengths of the greatsword and zweihander and some of the strengths of anti armor weapons like maces and daggers. Overall, the numbers to kill or disable are not all that different from the greatsword, but the fighting style is a little different. currently estocs are available to heavy knights and have a crafting recipe that's otherwise identical to the greatsword.

## Why It's Good For The Game

the rapier has kind of a crusty set of sprites for what should be a very stylish weapon, plus old items in roguecode tend to have pretty boring and anemic descriptions, which has always been one of my biggest flavor-related complaints with the base. the estoc is good for the game because i mained it in elden ring :) plus rock-paper-scissors balance can happen within classes of weapons as well as across classes of weapons, which makes counterplay trickier and more complex.

### CODE REVIEW

**Comment by faaaay** [comment]
Would it be possible to see what the sprites look like in-game, please? It's hard to tell if the gold is consistent with the colours used in other sprites.

**Comment by Kavrick** [comment]
These weapons don't follow our art style, as much as I like them. If you need me to redo them feel free to ask. Also please use aseprite to increase the size of the preview so you can actually see them.

**Comment by kittysmooch** [comment]
> Would it be possible to see what the sprites look like in-game, please? It's hard to tell if the gold is consistent with the colours used in other sprites.

yeah i'll worry about that next time i boot up the test enviro

> These weapons don't follow our art style, as much as I like them. If you need me to redo them feel free to ask. Also please use aseprite to increase the size of the preview so you can actually see them.

colors and style are straight out of the 64x dmi

**Comment by kittysmooch** [comment]
> tumblr_6b1235af6cc4a721c0c6c0454c222d00_89bb88bf_500 [ tumblr_6b1235af6cc4a721c0c6c0454c222d00_89bb88bf_500 ](https://private-user-images.githubusercontent.com/50682821/370845769-ae36120d-dcac-48a3-bd2a-51ba6687c5c3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODg1MzEsIm5iZiI6MTcyNzI4ODIzMSwicGF0aCI6Ii81MDY4MjgyMS8zNzA4NDU3NjktYWUzNjEyMGQtZGNhYy00OGEzLWJkMmEtNTFiYTY2ODdjNWMzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE4MTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZDM0YTk4Zjc5M2YyMjVmN2FmNmQzNzBiM2M2MDIyYWRkOWRmODFkNTJhNDM4NGNiZTM4NjIxMDE2N2FhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mnoAaCYL9hXDRL0SjBP744hL-m3P-qxied_UXvQd9so) [ ](https://private-user-images.githubusercontent.com/50682821/370845769-ae36120d-dcac-48a3-bd2a-51ba6687c5c3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODg1MzEsIm5iZiI6MTcyNzI4ODIzMSwicGF0aCI6Ii81MDY4MjgyMS8zNzA4NDU3NjktYWUzNjEyMGQtZGNhYy00OGEzLWJkMmEtNTFiYTY2ODdjNWMzLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE4MTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZDM0YTk4Zjc5M2YyMjVmN2FmNmQzNzBiM2M2MDIyYWRkOWRmODFkNTJhNDM4NGNiZTM4NjIxMDE2N2FhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mnoAaCYL9hXDRL0SjBP744hL-m3P-qxied_UXvQd9so)
> 
> it's peam. gilded weapons don't get enough love. Also having some sidegrades to the greatswords is nice to keep them from being king. Does the estoc get reach?

right now it has two bespoke intents; one has more armor pen, less damage, and no reach, and one has less armor pen, more damage, and 2 reach. the other two are bash-style intents for less-lethal stuff. might whittle them down to one.

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Mmmmh. The normal rapier is looking fine. It's the other tw osprites that I kinda got an issue with. The gold honestly looks like **cheese**, and the estoc looks way too thin with just bein one pixel thick and the guard.

**Comment by kittysmooch** [comment]
the color of the gilt rapier is so that it still looks golden after being passed through the game's grungefilter:

image

it's also almost exactly the same color as actual gold/gilt/brass handles on swords

cantbelieveigottadothis

as for the estoc: it's not one pixel, it just blends into the github background color.

image

this corresponds to the shape of the actual swords, which have thin blades and aggressive tapers because they're meant to find the holes in the maille sections of plate armor.

unnamed

**Comment by GeneralPantsuIsBadAtCoding** [comment]
> as for the estoc: it's not one pixel, it just blends into the github background color.

Ooooh yeah I can see it now, that way it looks way better lmfao.

> it's also almost exactly the same color as actual gold/gilt/brass handles on swords

Well the problem is that its not quite the same gold as the other decorated bits. 

image
image2

Just as some examples. Might just be a matter of shading but yeah, it is a big difference.

**Comment by kittysmooch** [comment]
forgot to take the "this aint ready" outta the about this is ready to go whenever

**Comment by kittysmooch** [comment]
image

i actually wasn't going to initially but this kind of entitlement to volunteer time is actually insane. no thank you.

**Comment by kittysmooch** [comment]
reopening this bad boy because i saw a rapier sprite and dry heaved and also im not mad anymore

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Heya, nice to see you back!

Though I still would like to request the golds shade to allign with other golden items, please. Besides that I'd say its ready to merge.

**Comment by kittysmooch** [comment]
the gold tones are sampled straight off the monarch's crown so that the drip matches

**Comment by GeneralPantsuIsBadAtCoding** [comment]
> the gold tones are sampled straight off the monarch's crown so that the drip matches

Well, it doesn't exactly allign with other weapons with golden trim, though. Or the rings. The crown is pretty much the only one using that shade- which might also have to be changed imho.

**Comment by kittysmooch** [comment]
alright. i can swap tones and update the pr in about 30 minutes

**Comment by kittysmooch** [comment]
image
bazinga

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Okay I hate to be the one to constantly go "HMMM AND MAYBE-", but I think it might benefit from a different colour grip, too. Perhaps leather wrapped or something? It certainly looks nicer with that shade of gold though to me, that's for sure!

And another side-question, the belt-worn sprite, does that use the experimental system or _actual_ sprites?

**Comment by kittysmooch** [comment]
the belt sprite uses the transform system, though i went through by hand on every value to make sure it looked good, which is something i'll probably do to a lot of other weapons that do weird things like drag their hilts on the ground when i get the time to.

i'm already nose deep in a big pr for another base and a different grip style requires a little more attention than color swapping so if we wanna go that route it'll have to either wait a few days or i can come back with a small secondary pr to update it.

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Yeah no worries I'll merge it like this for now, its still a beautiful sprite!

**Pull request merged**
