### PR TITLE
Ports Ratwood's feint buffs

### PR DESCRIPTION
**Pull request by sa1tman**
## About The Pull Request
Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/756 without SPD scaling.

Adds scaling with INT (10% chance per point of difference). 

Increases duration of immobilized debuff if feint is done from the dedicated feint intent. It is still possible to feint while using any other intent, but to much less effect.

Many commits cause I'm stoopid and never used github before.

## Why It's Good For The Game
Makes INT a little more viable for combat outside of magic. There is now a bit of a downside to dumping INT.

### CODE REVIEW

**Comment by Joel-682** [comment]
Doesn't Aimed already counter dodge? I think it'd be fine if it was kept the way it is, plus dodge can get you into nasty situations (Dodging into a trap, into a ranged attack, into an open space, etc).
You also need dodge expert for dodge to even be viable, so.

**Comment by sa1tman** [comment]
> This is great but we can go even further. Make feint disable dodge for a time. Dodge is already way stronger than parrying, and making feint even more viable against just one method of defense will only make people lean into it even more.

defend mode parries disable dodging for a short while, if they do apply 'riposted' debuff like they should

**Comment by sa1tman** [comment]
> Doesn't Aimed already counter dodge? I think it'd be fine if it was kept the way it is, plus dodge can get you into nasty situations (Dodging into a trap, into a ranged attack, into an open space, etc). You also need dodge expert for dodge to even be viable, so.

aimed just increases your odds of hitting body part you are aiming

**Comment by LittleEvil9** [comment]
> This is great but we can go even further. Make feint disable dodge for a time. Dodge is already way stronger than parrying, and making feint even more viable against just one method of defense will only make people lean into it even more.

Dodging is already WAY STRONGER than dodging? funniest bit i've heard ngl (skill issue). The reason feints does not disable dodging is because most dodge users are cooked due to wearing light armor, you only need to hit a good grab or clean hits.

Also, when you ever get feinted with parry, you can swap to dodge.

**Comment by sa1tman** [comment]
> > This is great but we can go even further. Make feint disable dodge for a time. Dodge is already way stronger than parrying, and making feint even more viable against just one method of defense will only make people lean into it even more.
> 
> Dodging is already WAY STRONGER than dodging? funniest bit i've heard ngl (skill issue). The reason feints does not disable dodging is because most dodge users are cooked due to wearing light armor, you only need to hit a good grab or clean hits.
> 
> Also, when you ever get feinted with parry, you can swap to dodge.

u cant
feinted disables both blocking and dodging

**Comment by Ephemeralis** [comment]
We can't do the SPD thing. SPD's already a god stat - it doesn't need more going for it.

**Comment by sa1tman** [comment]
> We can't do the SPD thing. SPD's already a god stat - it doesn't need more going for it.

k spd scale removed

**Comment by Lutowski** [comment]
epic

**Pull request merged**
