### PR TITLE
gives da captain two classes + weapon selection

### PR DESCRIPTION
**Pull request by kittysmooch**
## About The Pull Request

tors wanted the captain role to have the RG weapon selection. i said ya and then discovered a ui bug involving injecting a weapon selection menu into a class that doesn't have advclasses. thus, the captain now has advclasses too. they're basically the same but one lost a wrestling point to get a riding point and lost a riding point get a wrestling point. in other words this is a stealth buff to infantry captains that WILL destroy balance forever. oh yeah i kinda tidied the code a little too.

## Why It's Good For The Game

sabres are cringe idk

### CODE REVIEW

**Comment by bearrrrrrrr** [comment]
i was about to say 'mace 5 is too much' but then realized they have HAD weapon skill 5. wtf how did i miss this

more choices good, anyway

**Comment by bearrrrrrrr** [comment]
what if the guard captain was called the freak captain and h

**Comment by kittysmooch** [comment]
> i was about to say 'mace 5 is too much' but then realized they have HAD weapon skill 5. wtf how did i miss this? probably fine, anyway
> 
> more choices good, anyway

i could do like actual classes since this was more of a "well i cant just have one class and its og captain that looks ridiculous" thing. if theres a desire for it.

**Comment by kittysmooch** [comment]
improved class differentiation, mostly by moving skill points around and giving them different hats.

**Comment by Lutowski** [comment]
erm, epic i think

**Pull request merged**
