### PR TITLE
adds abyssor trait

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

u can swim better now

technically this means you are now able to regen stamina if you have swimming 5 but this already happened with swimming 6 and nobody even has swimming 5

## Why It's Good For The Game

yeah

### CODE REVIEW

**Comment by n3tis** [comment]
protip: you can easily circumvent stamloss with a handcart

**Comment by n3tis** [comment]
> > protip: you can easily circumvent stamloss with a handcart
> 
> you can also just not move for a bit to regain stamina so meh

kiiiiinda works but the handcart/barrel trick works best cause you remain in one place

**Comment by bearrrrrrrr** [comment]
ohhh with flowing water, yea

**Comment by n3tis** [comment]
> ohhh with flowing water, yea

on this current map I think there's water tiles that don't flow so a player can rest on there
but yeah generally in a place where you expect it to not you can use a handcart

**Comment by GeneralPantsuIsBadAtCoding** [comment]
Probably a better idea than mine (being able to crawl through waddah without drowning LOL), merged

**Comment by bearrrrrrrr** [comment]
fuck

**Pull request merged**
