### PR TITLE
QoL | Paladins Drip Upgrade

### PR DESCRIPTION
**Pull request by MortoSasye**
## About The Pull Request

People hate playing Paladin because as it stands right now they are lacking armor, even though they have the heavy armor trait too like Templars... spawning with a single hauberk. The Cleric gets better armor than they do. What's up with that?

This PR does the following hence:
- Changed the hauberk for a chain coif + half-plate (the armor clerics get)
- Switches the cloak for the templar variety whenever possible, which is much more fancy, for 𝓯𝓪𝓼𝓱𝓲𝓸𝓷 purposes.
- Gives them their God helmet. If you don't have a helmet variety for your God, well... bad luck bozo.
- Gives them the axes skill because I forgot. Tee-hee.

<details>

dreamseeker_3uTc9Xj9EG
dreamseeker_lF0sIcb9gg

</details>

## Why It's Good For The Game

Avoid the syndrome of people going Templar then evaporating from the church because truly all they wanted to play was non-ass Paladin.

### CODE REVIEW

**Comment by Aurorablade** [comment]
Tbh I like how the chain looks and feel like the plate could be for the battle master subclass

**Comment by MortoSasye** [comment]
> Tbh I like how the chain looks and feel like the plate could be for the battle master subclass
> 
> Edit after thinkint: also the entire issue can ne solved, if it is purely drip related, by interacting with people town and fellow adventurer crafter (trust me I go out of my way for a looks). Same applies for Templar. If it's someone rolling town Templar just to 'go off'..that feels like a player issue. But this is purely my opinion and o am sorry if it sounds like pure shut down

No. The idea behind this PR is putting them on equal footing with classes such as cleric, considering they're meant to be the "warrior/protector" variant of the faith classes.

**Comment by Alexi-6410** [comment]
> > Tbh I like how the chain looks and feel like the plate could be for the battle master subclass
> > Edit after thinkint: also the entire issue can ne solved, if it is purely drip related, by interacting with people town and fellow adventurer crafter (trust me I go out of my way for a looks). Same applies for Templar. If it's someone rolling town Templar just to 'go off'..that feels like a player issue. But this is purely my opinion and o am sorry if it sounds like pure shut down
> 
> No. The idea behind this PR is putting them on equal footing with classes such as cleric, considering they're meant to be the "warrior/protector" variant of the faith classes.

This is nerfing them though, potentially through an oversight. The hauberk is probably a superior piece of armor to half-plate for paladin because half-plate only covers the torso, whereas a hauberk covers the torso, legs, and arms. It does have inferior durability, yeah, but it gives you way more practical protection because the only thing that targets torso is simplemobs / people who forgot to select a new zone to target. In this new armor set, paladins have no arm armor and less leg armor. The current meta is "target the legs" so removing a layer of leg armor is bad (hauberks are one of the few leg armors other than chest armor) and having no arm armor means all it takes someone is examining you and going "oh, your arm is unarmored" and cutting your arm off. You also can layer a hauberk with looted armor (persay, looted leather armor or something of the sorts from a raider/skeleton).

...so, your first choice of action upon spawning in as a paladin is gonna be to go buy a hauberk (or haubergeon) so you can cover your arms. Or sewing a gambeson, I suppose, if you're lacking a smith.

Maybe the old hauberk + powercreep them a cuirass (an otherwise almost exclusively unused piece of armor)? 

...then again, even with the old hauberk + chainlegs for armor, they still had better armor than cleric who /only/ spawns with half-plate, and otherwise has leather-trousers and the sorts. Cleric's armor is only better if your opponent is completely targetting chest, and doesn't realize they can just cut your leg off. Which, fair when fighting simplemobs I suppose.

**Comment by Alexi-6410** [comment]
also Eora paladins are for some reason getting a free sallet helmet whereas other paladins who lack an unique helmet are not, maybe give out the sallet helmet to everyone (or rob Eora paladins blind) so people have a generic helmet option? Though I think the sallet drip sucks.

**Comment by Lutowski** [comment]
keep hauberk & patron-based drip, remove chain coif

**Comment by radarseas** [comment]
you forgot to mention in your PR that psydonites don't have their silver psycross and instead a normal one, which means they're not protected from lesser vampire transfixation anymore.

_also psydon patron paladins should totally get their boots replaced with enduring boots, they're basically normal leathers anyway, but more zeolotically drippy._

**Comment by MortoSasye** [comment]
> keep hauberk & patron-based drip, remove chain coif

Done!

**Pull request merged**
