### PR TITLE
fixes some balance issues

### PR DESCRIPTION
**Pull request by Plum-but-gayer**
## About The Pull Request

Fixes a few balance issues regarding stats and attributes, as well as roundstart gear. 

## Why It's Good For The Game

Satire is a [genre](https://en.wikipedia.org/wiki/Genre) of the [visual](https://en.wikipedia.org/wiki/Visual_arts), [literary](https://en.wikipedia.org/wiki/Literature), and [performing arts](https://en.wikipedia.org/wiki/Performing_art), usually in the form of [fiction](https://en.wikipedia.org/wiki/Fiction) and less frequently [non-fiction](https://en.wikipedia.org/wiki/Nonfiction), in which vices, follies, abuses, and shortcomings are held up to ridicule, often with the intent of exposing or shaming the perceived flaws of individuals, corporations, government, or society itself into improvement.[[1]](https://en.wikipedia.org/wiki/Satire#cite_note-FOOTNOTEElliott2004-1) Although satire is usually meant to be humorous, its greater purpose is often constructive [social criticism](https://en.wikipedia.org/wiki/Social_criticism), using [wit](https://en.wikipedia.org/wiki/Wit) to draw attention to both particular and wider issues in society.

A prominent feature of satire is strong [irony](https://en.wikipedia.org/wiki/Irony) or [sarcasm](https://en.wikipedia.org/wiki/Sarcasm)—"in satire, irony is [militant](https://en.wiktionary.org/wiki/militant)", according to [literary critic](https://en.wikipedia.org/wiki/Literary_criticism) [Northrop Frye](https://en.wikipedia.org/wiki/Northrop_Frye)—[[2]](https://en.wikipedia.org/wiki/Satire#cite_note-2) but [parody](https://en.wikipedia.org/wiki/Parody), [burlesque](https://en.wikipedia.org/wiki/Burlesque_(literary)), [exaggeration](https://en.wikipedia.org/wiki/Exaggeration),[[3]](https://en.wikipedia.org/wiki/Satire#cite_note-Claridge2010p257-3) [juxtaposition](https://en.wikipedia.org/wiki/Juxtaposition), comparison, analogy, and [double entendre](https://en.wikipedia.org/wiki/Double_entendre) are all frequently used in satirical speech and writing. This "militant" irony or sarcasm often professes to approve of (or at least accept as natural) the very things the satirist wishes to question.

Satire is found in many artistic forms of expression, including internet memes, literature, plays, commentary, [music](https://en.wikipedia.org/wiki/Satirical_music), [film and television](https://en.wikipedia.org/wiki/Satire_(film_and_television)) shows, and media such as lyrics.

## Social and psychological functions

Satire and [irony](https://en.wikipedia.org/wiki/Irony) in some cases have been regarded as the most effective source to understand a society, the oldest form of social study.[[12]](https://en.wikipedia.org/wiki/Satire#cite_note-Rosenberg1960p155-12) They provide the keenest insights into a group's [collective psyche](https://en.wikipedia.org/wiki/Collective_unconscious), reveal its deepest values and tastes, and the society's structures of power.[[13]](https://en.wikipedia.org/wiki/Satire#cite_note-Deloria69p146-13)[[14]](https://en.wikipedia.org/wiki/Satire#cite_note-Nash1970p203-14) Some authors have regarded satire as superior to non-comic and non-artistic disciplines like history or [anthropology](https://en.wikipedia.org/wiki/Anthropology).[[12]](https://en.wikipedia.org/wiki/Satire#cite_note-Rosenberg1960p155-12)[[15]](https://en.wikipedia.org/wiki/Satire#cite_note-Babcock1984-15)[[16]](https://en.wikipedia.org/wiki/Satire#cite_note-Coppola-16)[[17]](https://en.wikipedia.org/wiki/Satire#cite_note-17) In a prominent example from [ancient Greece](https://en.wikipedia.org/wiki/Ancient_Greece), philosopher [Plato](https://en.wikipedia.org/wiki/Plato), when asked by a friend for a book to understand Athenian society, referred him to the plays of [Aristophanes](https://en.wikipedia.org/wiki/Aristophanes).[[18]](https://en.wikipedia.org/wiki/Satire#cite_note-Willi2003p1-18)[[19]](https://en.wikipedia.org/wiki/Satire#cite_note-Ehrenberg1962p39-19)

Historically, satire has satisfied the popular [need](https://en.wikipedia.org/wiki/Need) to [debunk](https://en.wikipedia.org/wiki/Debunk) and [ridicule](https://en.wikipedia.org/wiki/Ridiculous) the leading figures in politics, economy, religion and other prominent realms of [power](https://en.wikipedia.org/wiki/Power_(social_and_political)).[[20]](https://en.wikipedia.org/wiki/Satire#cite_note-Bevere2006p265-20) Satire confronts [public discourse](https://en.wikipedia.org/wiki/Public_discourse) and the [collective imaginary](https://en.wikipedia.org/wiki/Collective_imaginary), playing as a public opinion counterweight to power (be it political, economic, religious, symbolic, or otherwise), by challenging leaders and authorities. For instance, it forces administrations to clarify, amend or establish their policies. Satire's job is to expose problems and contradictions, and it is not obligated to solve them.[[21]](https://en.wikipedia.org/wiki/Satire#cite_note-WieseForbes2010p.xv-21) [Karl Kraus](https://en.wikipedia.org/wiki/Karl_Kraus_(writer)) set in the history of satire a prominent example of a satirist role as confronting public discourse.[[22]](https://en.wikipedia.org/wiki/Satire#cite_note-Knight2004p254-22)

For its nature and social role, satire has enjoyed in many societies a special freedom license to mock prominent individuals and institutions.[[23]](https://en.wikipedia.org/wiki/Satire#cite_note-Test1991p9licencequote-23) The satiric impulse, and its ritualized expressions, carry out the function of resolving social tension.[[24]](https://en.wikipedia.org/wiki/Satire#cite_note-Test1991p8-24) Institutions like the [ritual clowns](https://en.wikipedia.org/wiki/Ritual_clown), by giving expression to the [antisocial tendencies](https://en.wikipedia.org/wiki/Antisocial_tendencies), represent a [safety valve](https://en.wikipedia.org/wiki/Safety_valve) which re-establishes equilibrium and health in the [collective imaginary](https://en.wikipedia.org/wiki/Collective_imaginary), which are jeopardized by the [repressive aspects of society](https://en.wikipedia.org/wiki/Social_repression).[[25]](https://en.wikipedia.org/wiki/Satire#cite_note-Cazeneuve1957p244-25)[[26]](https://en.wikipedia.org/wiki/Satire#cite_note-Durand1984p106-26)

The state of [political satire](https://en.wikipedia.org/wiki/Political_satire) in a given society reflects the tolerance or intolerance that characterizes it,[[20]](https://en.wikipedia.org/wiki/Satire#cite_note-Bevere2006p265-20) and the state of [civil liberties](https://en.wikipedia.org/wiki/Civil_liberties) and [human rights](https://en.wikipedia.org/wiki/Human_rights). Under [totalitarian regimes](https://discord.com/invite/FXrMvsYAbH) any criticism of a political system, and especially satire, is suppressed. A typical example is the [Soviet Union](https://en.wikipedia.org/wiki/Soviet_Union) where the [dissidents](https://en.wikipedia.org/wiki/Dissidents), such as [Aleksandr Solzhenitsyn](https://en.wikipedia.org/wiki/Aleksandr_Solzhenitsyn) and [Andrei Sakharov](https://en.wikipedia.org/wiki/Andrei_Sakharov) were under strong pressure from the government. While satire of everyday life in the [USSR](https://en.wikipedia.org/wiki/Soviet_Union) was allowed, the most prominent satirist being [Arkady Raikin](https://en.wikipedia.org/wiki/Arkady_Raikin), political satire existed in the form of [anecdotes](https://en.wikipedia.org/wiki/Anecdote)[[27]](https://en.wikipedia.org/wiki/Satire#cite_note-27) that made fun of Soviet political leaders, especially [Brezhnev](https://en.wikipedia.org/wiki/Brezhnev), famous for his narrow-mindedness and love for awards and decorations.

### CODE REVIEW

**Comment by kittysmooch** [comment]
the changes this pr makes are ridiculous! however i have a very reasonable pr up to nerf squires overall in exchange for letting them pick loadouts on spawn. https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/461

**Comment by bearrrrrrrr** [comment]
compiler faiHOLY SHIT IS THAT JEVIL FROM FUCKING UNDERTALE??
images

**Comment by Noightmare** [comment]
This is 100% a joke PR, which I have no idea why you're doing this considering your PR history but, denied.

**Comment by EvenInDeathIStillServe** [comment]
> This is 100% a joke PR, which I have no idea why you're doing this considering your PR history but, denied.

god forbid women do anything

**Pull request closed without merging**
