### PR TITLE
Evil Farmer Traps Innocent Verevolf In Mud: Adjusts skill changes and traits to soiler and miner

### PR DESCRIPTION
**Pull request by Lutowski**
## About The Pull Request

- Soilers spawn with Longstrider, No Stink and Seed Know trait, no slowdown from rough terrain and not affected by odour.
- Soilers have a new description from Stone Keep.
- Druids spawn with Longstrider trait.
- Miners spawn with Noc Sight trait.
- Thresh intent is set to 1st on two handed thresher.
- Skill adjustments:

**Miner**
1 Masonry -> 3 Masonry
-1 INT debuff removed.

**Soiler**
3 Knives -> 1 Knives
2 Polearms -> 4 Polearms
1 Wrestling -> 3 Wrestling
1 Unarmed -> 3 Unarmed
2 Archery -> 0

## Why It's Good For The Game
Miners should know quite a lot about the rocks they mine and how to use them. Strengthens their niche in the wake of masoner's removal. Being in dark tunnels adjusts their eyes' to be a bit better than others.

Soilers are Mud Wizards. They shouldn't have issues traversing the land they farm on. Soilers are also not archers or rogues. Skill change strengthens focus on being practical, rough & tough farmers wielding pitchforks. They're usually the first to be fragged on antag heavy rounds, so this will give them a fighting chance to defend their hood.

image

### CODE REVIEW

**Comment by kittysmooch** [comment]
we should add geomancy

**Comment by MaSvedish** [comment]
Another Shining Light From Azure Bleak Lets Go.

**Comment by Lutowski** [comment]
> I changed the description away to play them up as some harvest moon/rune factory giga farm god!!
> 
> Losing knifes is fine, four polearms is too high (it's soldier/garrison-tier) but three would be _fine_. I was iffy at three unarmed until I looked up and realized almost every role in the game has three unarmed which is, uh
> 
> a separate 🤔 issue but that's fine for now
> 
> Masonry three on the miner will let them do all masonry except for craftstone, which I feel is overstepping the Artificer's former mason hat. In the same breath though, who's building walls so that's... probably fine, but I have reservations.

your description had grammar issues that I didn't have the energy to fix. if you want it back, fix it and push in seperate PR

four polearms isn't high, you can still flatline soilers because they start with just pitchforks and nothing else. no neck armour, no plate. only thing soilers have going on for them is a pitchfork and maybe strength in numbers as peasants do (if more than 1-2 sign up) if you're good at combat and have gear, a soiler with four in polearms already loses

**Comment by GeneralPantsuIsBadAtCoding** [comment]
I'm genuinely unsure how I feel about giving ANY role permanent longstrider. Said that with the Wardens before, will repeat it now. I can understand the utility behind it and whatnot, but it seems pretty damn crazy, **especially** for Druids which already get to do all kinds of wild fuckery.

**Comment by benj8560** [comment]
> I'm genuinely unsure how I feel about giving ANY role permanent longstrider. Said that with the Wardens before, will repeat it now. I can understand the utility behind it and whatnot, but it seems pretty damn crazy, **especially** for Druids which already get to do all kinds of wild fuckery.

just a small note here. You can very easily get permanent longstrider via mounts. Saigas don't get slowdown from dirt or even water. It's also not particularly difficult to obtain one.

**Pull request merged**
