### PR TITLE
knife belt

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request
knife belt and throwing knives

## Why It's Good For The Game

image

no longer poo poo garbage sprites, made by the extremely talented dongwaiver, thank you very much bud :]

### CODE REVIEW

**Comment by kittysmooch** [comment]
had a similar thought because i wanted the ninja throwing stars gone, never got around to it

**Comment by Mannybrado** [comment]
:3

**Comment by EerieDream** [comment]
Knife build is looking good

**Comment by Lutowski** [comment]
so peak

**Pull request merged**
