### PR TITLE
VOICE OF COMMAND

### PR DESCRIPTION
**Pull request by Onutsio**
## About The Pull Request

THIS PR DOES THE FOLLOWING

REMOVES HEAVY ARMOR TRAINING FROM MAA. Now RG have the sole cool-factor of being the only garrison with heavy armor access.

MAA now spawn in the garrison, rather than alongside the court.

Restats Boltsman into being a quick, ranged/daggers MAA class. Dodge expert, light armor, better climb/athletics than a footsman.

SERGEANT -A new, non-noble garrison leader. Responsible for directing the MAA in their new *official* role as town guards. Basically statted identically to a regular MAA, with some minor bonuses(better athletics, a better starting helmet). Their primary boon comes in the form of:

### _**VOICE OF COMMAND.**_

GCs and Sergeants can now issue Orders to their underlings. These cost a decent chunk of stamina, and provide pretty good targeted buffs. You cannot buff yourself or people who aren't your underlings(RG for GC, MAA for Sergeant).

"MOVE! MOVE! MOVE!"
Applies HASTE to a target for a minute

"TAKE AIM!"
+5 PER on a target

"HOLD!"
+2 CON, +2 END on target

"ON YOUR FEET!"
Removes stuns/knockdowns, bumps target up to standing and gives them pain res for a short time

"Focus target!" 

Outlines a target in red, applies -2 fortune to them and applies critical weakness

## Why It's Good For The Game

Some Spicy Garrison content:tm:

### CODE REVIEW

**Comment by radarseas** [comment]
any chance of giving team antag leaders, (bandit iconclast, vampire lord, lich) access to a varient of these to command their own? perhaps... weakened versions (they're already pretty powerful).

**Comment by Onutsio** [comment]
> any chance of giving team antag leaders, (bandit iconclast, vampire lord, lich) access to a varient of these to command their own? perhaps... weakened versions (they're already pretty powerful).

Probably not! This is *specifically* built as a Disciplined garrison thing! Antagonists have their own things going for them ;3e.

**Comment by kittysmooch** [comment]
sad to see marshall go after macha and cre just gave it new content and exclusive sprites.

**Comment by Onutsio** [comment]
Oh I forgot it got unique outfits. Can probably move them to Councillors closet or something?

**Comment by Onutsio** [comment]
Actually I agree. I'm going to just remove Marshall removal from this PR. I do rlly like the sprites and stuff + I dont rlly like to undo other contributors schtuff.

**Comment by Onutsio** [comment]
> im sorry boo the keep does not need three separate combat leaders it usually doesn't even have three people in the garrison

Marshall isn't, at least, supposed to be a combat leader. Though I did want to strip it, I'm not bcuz it has new stuff.

**Comment by bearrrrrrrr** [comment]
> im sorry boo the keep does not need three separate combat leaders it usually doesn't even have three people in the garrison

this isn't rly true anymore; it's on off but when keep gets ppl it pops off. that anddd nobody rly plays martial anymore, frankly. i'd be down for the straight up removal of it but it seems EXTREMELY shitty to remove something that just got a paid overhaul, esp with such gorgeous sprites

**Comment by Alexi-6410** [comment]
I see marshalls fairly consistantly, though primarily during highpop hours. I don't think having inherent roleplay positions is a bad thing though, but I agree that the garrison having 3 leaders might lead to being confusing. We already occasionally run into too-many-leaders situations with just two as sometimes the duke/hand likes to get personally involved.

Crit weakness is kinda brutal, IIRC it makes you instantly die from a significant amount of crits. Just outlining a target in red is powerful, especially because in combat it can be extraordinarily difficult for the garrison to determine who they're actually supposed to be stabbing. Bandits/antags/other bad people don't have an enforced dress code to look bad, and with the habit of knights wearing black armor and no heraldry, even people who were once supposed to look distinctly evil (death knights, vampyres, etc) can blend into a crowd. It's exceptionally difficult for the garrison to determine whose on whose side, so just outlining a target in red so the garrison knows "this is bad man, stab them!!" is good.  

+5 perception might be too much, keep in mind that boltman already gets +2, plus upto 3 from racial/statpack, plus +2 from being in town. That's giving a boltman 19 perception (no statpack/racial bonus) to 23 (+1 perception race, foresighted statpack) perception.

Other than that this looks REALLY cool. I like the orders system, it seems nifty and like it has a lot of potential.

**Comment by Onutsio** [comment]
> I see marshalls fairly consistantly, though primarily during highpop hours. I don't think having inherent roleplay positions is a bad thing though, but I agree that the garrison having 3 leaders might lead to being confusing. We already occasionally run into too-many-leaders situations with just two as sometimes the duke/hand likes to get personally involved.
> 
> Crit weakness is kinda brutal, IIRC it makes you instantly die from a significant amount of crits. Just outlining a target in red is powerful, especially because in combat it can be extraordinarily difficult for the garrison to determine who they're actually supposed to be stabbing. Bandits/antags/other bad people don't have an enforced dress code to look bad, and with the habit of knights wearing black armor and no heraldry, even people who were once supposed to look distinctly evil (death knights, vampyres, etc) can blend into a crowd. It's exceptionally difficult for the garrison to determine whose on whose side, so just outlining a target in red so the garrison knows "this is bad man, stab them!!" is good.
> 
> +5 perception might be too much, keep in mind that boltman already gets +2, plus upto 3 from racial/statpack, plus +2 from being in town. That's giving a boltman 19 perception (no statpack/racial bonus) to 23 (+1 perception race, foresighted statpack) perception.
> 
> Other than that this looks REALLY cool. I like the orders system, it seems nifty and like it has a lot of potential.

Something to keep in mind about Take Aim! In particular is that its going to be competing with every other order for stamina usage. From my testing, you can usually pop off 2 orders before hitting stam crit. And perception's scaling isn't quite as strong as the other stats. As for crit weakness, It's kinda the best way to represent the targetting idea and actually reward garrison members for following the order. I *think* It'll be fine. It's fine for these orders to be decently strong imo, as they only have 2 sources and require someone to sit out of combat. Crit resist would be problematic if we still had heart crits, but we don't.

I guess the thing to consider in most situations is "Is popping a order stronger, or is just having the Officer also attack better", and I think in most cases the officer just double teaming the guy would be better. But it's more *fun* to do Orders.

**Comment by JustZoeDotExe** [comment]
Hi! I play man-at-arms a fair bit, so I wanted to offer some feedback that may or may not be welcome! The sergeant stuff? Badass, love to see it in action. The removal of heavy armour and the addition of steel hearted? Peak. My concern comes in with the balance of skirmisher versus footman! 

As it stands, what advantages do I gain from playing footman versus a skirmisher? With the new light armour stuff, we've got some pretty powerful options for doing close quarters with a dodge-based class. Giving them expert in swords + knives alongside higher athletics than the dedicated melee class gives me a little bit of worry about why exactly I'd want to be a footman instead. I've got more stamina usage for offensive and defence as a skirmisher thanks to the athletics I've got, the same weapon skill as footman, and a defensive option that isn't affected by the antag's potentially higher weapon skill, all along with powerful ranged options for versatility in fights. 

My suggestion would be to potentially lower the skirmisher's weapon skill to journeyman level to keep them viable in melee, but let the melee dedicated folk shine. Let them use their higher speed and stamina to move around the opponent and go for backstabs, instead of letting them get through parries just as easily.

**Comment by Onutsio** [comment]
> Hi! I play man-at-arms a fair bit, so I wanted to offer some feedback that may or may not be welcome! The sergeant stuff? Badass, love to see it in action. The removal of heavy armour and the addition of steel hearted? Peak. My concern comes in with the balance of skirmisher versus footman!
> 
> As it stands, what advantages do I gain from playing footman versus a skirmisher? With the new light armour stuff, we've got some pretty powerful options for doing close quarters with a dodge-based class. Giving them expert in swords + knives alongside higher athletics than the dedicated melee class gives me a little bit of worry about why exactly I'd want to be a footman instead. I've got more stamina usage for offensive and defence as a skirmisher thanks to the athletics I've got, the same weapon skill as footman, and a defensive option that isn't affected by the antag's potentially higher weapon skill, all along with powerful ranged options for versatility in fights.
> 
> My suggestion would be to potentially lower the skirmisher's weapon skill to journeyman level to keep them viable in melee, but let the melee dedicated folk shine. Let them use their higher speed and stamina to move around the opponent and go for backstabs, instead of letting them get through parries just as easily.

Hi yea thank u! So, Footmen have medium armor training and the better weapon skills(maces and polearms). And the option to use basically any other melee weapon. Theyre gonna be more reliable frontliners than Skirmishers. Since traditional parry combat has alot more Lasting to it.

Additionally, since skirmishers will probs be dodging, their weapon skill wont matter alot on the defensive.  Most of their strike chance is gonna come out of spd since daggers are swift balanced, so really jman/expert diff would be somewhat neglible if it were to change.

Additionally, while dodge may not be affected by a antags high wep skill, it is affected by antags usually having better spd. Vlords and WWs are usually gonna outspd you, as will lesser vampires. Bandits have their own quick classes who can slap a skirmisher. Or just use one of the heavy counters to dodge setups.

**Pull request merged**
