### PR TITLE
Better rain, Foggy Grimshart

### PR DESCRIPTION
**Pull request by Cleric2145**
## About The Pull Request
Somebody back in Blackstone (I think) salt-PR'd out fog and that seems rude. Maybe it was absolute shart, but I get the feeling they died to something. Reenabled fog with some lower alpha for it to be less intrusive and some more thematic flavortext.
Also revamps the rain sprites to by animated and with a little more variety (the rain weather actually calls two extra sprites that didn't exist, so I added some.) 

https://github.com/user-attachments/assets/4472cc79-81f0-49b6-92de-832750fe5ea0

## Why It's Good For The Game
This will hopefully make rain a little more obvious, and feel more 'stormy.' Currently almost nobody RPs the changes in weather--understandable, since the most obvious clues it's raining is the sound of thunder/lightning, neither of which actually imply the rain is currently falling on top of you instead of a few leagues over in the coast.

### CODE REVIEW

**Comment by Cleric2145** [comment]
I haven't been able to test this at all bc I can't actually seem to get weather to force-run in my test server.

**Comment by kittysmooch** [comment]
aren't we replacing sprite rain with something from vanderlin?

**Comment by Cleric2145** [comment]
> aren't we replacing sprite rain with something from vanderlin?

I haven't heard. This is actually a PR I made a few weeks ago, but was never able to test so I just abandoned it. I drafted it today bc of some discussion about making fog happen again.

**Comment by kittysmooch** [comment]
> > aren't we replacing sprite rain with something from vanderlin?
> 
> I haven't heard. This is actually a PR I made a few weeks ago, but was never able to test so I just abandoned it. I drafted it today bc of some discussion about making fog happen again.

i dont see a pr up but i think its included in luto's big port

**Comment by Lutowski** [comment]
> i dont see a pr up but i think its included in luto's big port

the port in question is a big debloat + some other tg optimizations from vander that'll probably go up today, but the plan is to port pretty much everything else after that to bring the codebase up to speed

**Comment by bearrrrrrrr** [comment]
> aren't we replacing sprite rain with something from vanderlin?

i was gonna do this but im minorly burnt out rn so i don't mind the help here at all

**Comment by dwasint** [comment]
fog I don't think was salt removed as much as it worked badly, the weather system y'all are porting would work better just apply the overlay to the weather plane instead

**Comment by dwasint** [comment]
> fog I don't think was salt removed as much as it worked badly, the weather system y'all are porting would work better just apply the overlay to the weather plane instead

I tried this myself and did not like the look, I think fog requires a unique system to work properly

**Comment by Lutowski** [comment]
Closing this to prevent collusion with particle weather. Won't mind fog returning if an updated iteration is made.

**Pull request closed without merging**
